force-app/main/default/objects/DASALES_Porcentajedecobro__c/DASALES_Porcentajedecobro__c.object-meta.xml
<CustomObject>
    <label>Porcentaje de cobro</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Porcentaje de cobro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porcentajes de cobro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/DSALES_Matriz_de_Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Matriz Item</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matriz Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica cuando una matriz original está activa</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/dsalesAsignacionDeTienda__c.object-meta.xml
<CustomObject>
    <label>Asignación de Tienda</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Asignación de Tienda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignación de Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/fields/dsalesMatriz__c.field-meta.xml
<CustomField>
    <fullName>dsalesMatriz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matriz</label>
    <referenceTo>DSales_Matriz_GEX__c</referenceTo>
    <relationshipLabel>Asignación de Tiendas</relationshipLabel>
    <relationshipName>dsalesMatriz</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionEncuesta__c/dsalesAsignacionEncuesta__c.object-meta.xml
<CustomObject>
    <description>Campo que muestra las asignaciones de encuesta relacionadas al servicio y a la encuesta</description>
    <label>Asignación de Encuesta</label>
    <nameField>
        <displayFormat>Asignación-{00000}</displayFormat>
        <label>Nombre de Asignación de Encuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de Encuesta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesAsignacionEncuesta__c/fields/dsalesEncuestaPISyS__c.field-meta.xml
<CustomField>
    <fullName>dsalesEncuestaPISyS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relación a la encuesta asignada</description>
    <label>Encuesta PISyS</label>
    <referenceTo>dsalesEncuestaPISyS__c</referenceTo>
    <relationshipLabel>Asignaciones de Encuesta</relationshipLabel>
    <relationshipName>Asignaciones_de_Encuesta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionEncuesta__c/fields/dsalesServicio__c.field-meta.xml
<CustomField>
    <fullName>dsalesServicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Servicio relacionado a la asignación</description>
    <label>Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Instalaciones</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignaciones de Encuesta</relationshipLabel>
    <relationshipName>Asignaciones_de_Encuesta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesCP__c/dsalesCP__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Número de  Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesCP__c/fields/dsalesIsActive__c.field-meta.xml
<CustomField>
    <fullName>dsalesIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dsalesEncuestaPISyS__c/dsalesEncuestaPISyS__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los registros de las encuestas para el servicio de Instalaciones en PISyS</description>
    <label>Encuesta PISyS</label>
    <nameField>
        <label>Nombre de Encuesta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encuestas PISyS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesEncuestaPISyS__c/fields/dsalesCotizacion__c.field-meta.xml
<CustomField>
    <fullName>dsalesCotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que muestra la cotización relacionada a la encuesta</description>
    <label>Cotización</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Encuestas PISyS</relationshipLabel>
    <relationshipName>Encuestas_PISyS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesEncuestaPISyS__c/fields/dsalesCuestionario__c.field-meta.xml
<CustomField>
    <fullName>dsalesCuestionario__c</fullName>
    <label>Cuestionario</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_ServEspecifico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ServEspecifico__c</fullName>
    <inlineHelpText>Indique que tipo de servicio se requiere (Ej: GEX, Instalación, Armando)</inlineHelpText>
    <label>Servicio específico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garantía Extendida</fullName>
            </value>
            <value>
                <fullName>Armado de muebles</fullName>
            </value>
            <value>
                <fullName>Instalaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesAR__c.field-meta.xml
<CustomField>
    <fullName>dsalesAR__c</fullName>
    <description>Campo AR para el objeto producto.
Este campo es el tiempo que se tarda en armar el producto.</description>
    <label>AR</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesAR__c.field-meta.xml
<CustomField>
    <fullName>dsalesAR__c</fullName>
    <description>Campo AR para el objeto Partida de presupuesto</description>
    <label>AR</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DSALES_QuoteGexWrapperRequest_Helper.cls
/**
 * @description       : Clase de apoyo para DSALES_QuoteGexWrapperRequest
 * @author            : Juan Antonio Flores
 * @group             : Deloitte
 * @last modified on  : 09-05-2023
 * @last modified by  : Juan Antonio Flores
 * Modifications Log
 * Ver   Date         Author               Modification
 * 1.0   09-05-2023   Juan Antonio Flores  Initial Version
**/ 

public with sharing class DSALES_QuoteGexWrapperRequest_Helper {
    
     public static DSALES_QuoteGexWrapper.Nodos respuestaDescripcion(String nombre, String cotizaId,String tipoServicio){
        List<Quotelineitem> lstSkus = [SELECT id,Product2.StockKeepingUnit,Product2.Description,Product2.DSALES_ServEspecifico__c FROM Quotelineitem WHERE Quoteid=:cotizaId AND Product2.DSales_Tipo_de_Producto__c='Servicio' AND Product2.Description=:nombre WITH SECURITY_ENFORCED];
        DSALES_QuoteGexWrapper.Nodos nodoAux = new DSALES_QuoteGexWrapper.Nodos();
        nodoAux.Description = nombre;
        nodoAux.tipoDeServicio = tipoServicio;
        nodoAux.sku = new List<String>();
        
        for(Quotelineitem valores :lstSkus){
            String subTipoAux = valores.Product2.DSALES_ServEspecifico__c;
            nodoAux.subTipo = subTipoAux;
            
            String skuAux = valores.Product2.StockKeepingUnit;
            nodoAux.sku.add(skuAux);
        }
        return nodoAux;
    }
    
    public static List<DSALES_QuoteGexWrapper.Nodos> responseDescription(String tipoProducto, String cotizaId){
        List<Quotelineitem> valores = [SELECT id,Product2.StockKeepingUnit,Product2.Description FROM Quotelineitem WHERE Quoteid=:cotizaId AND Product2.DSales_Tipo_de_Producto__c=:tipoProducto WITH SECURITY_ENFORCED ORDER BY Product2.Description];
        List<String> valoresBusqueda = new List<String>();
        if(valores.size()>0){
            String valorDescripcion=valores[0].Product2.Description;
            valoresBusqueda.add(valorDescripcion);
            for(Quotelineitem aux :valores){
                if(valorDescripcion!=aux.Product2.Description){
                    valoresBusqueda.add(aux.Product2.Description);
                    valorDescripcion=aux.Product2.Description;
                }
            }
        }
        List<DSALES_QuoteGexWrapper.Nodos> response = new List<DSALES_QuoteGexWrapper.Nodos>();
        for(String aux :valoresBusqueda){
            DSALES_QuoteGexWrapper.Nodos respuesta = respuestaDescripcion(aux, cotizaId,'Servicio');
            response.add(respuesta);
        }
        return response;
    }
    
     public static List<DASALES_Porcentajedecobro__c> obtenerPorcentajeCobro(Id intangibleId) {
        List<DASALES_Porcentajedecobro__c> porcent = [SELECT Id, Name, DSALES_Anios__c, DSALES_Porcentaje__c FROM DASALES_Porcentajedecobro__c WHERE DSALES_Product__c=:intangibleId WITH SECURITY_ENFORCED];
        return porcent;
     }
    
     public static List<DSALES_Matriz_de_Cotizacion__c> obtenerMatricesPrecio(Id matrizId) {
        List<DSALES_Matriz_de_Cotizacion__c> matrizPrecio = [SELECT id, Name, SALES_Precio_GEX__c, DSales_Matriz_GEX__c, DSALES_Rango_interior_GEX__c, DSALES_Rango_Superior_GEX__c, DSALES_Tiempo_de_Garantia_Extendida_GEX__c FROM DSALES_Matriz_de_Cotizacion__c WHERE DSales_Matriz_GEX__c = :matrizId WITH SECURITY_ENFORCED ORDER BY SALES_Precio_GEX__c DESC];
        return matrizPrecio;
     }
    
     public static String matrizArPrice(String skuProd, dsalesAsignacionDeTienda__c asigTienda, QuoteLineItem quoteLineItem){ 
        String skuMatriz;
        Product2 prodAr=[SELECT Id, dsalesAR__c, StockKeepingUnit FROM Product2 WHERE StockKeepingUnit=:skuProd LIMIT 1]; 
        DSALES_Matriz_de_Cotizacion__c matrizCot=[SELECT Id,Name,SALES_Precio_GEX__c FROM DSALES_Matriz_de_Cotizacion__c WHERE SALES_Precio_GEX__c = :quoteLineItem.UnitPrice AND DSales_Matriz_GEX__r.DSALES_Activo__c = true AND DSALES_Rango_Superior_GEX__c >= : prodAr.dsalesAR__c AND DSales_Matriz_GEX__c = :asigTienda.dsalesMatriz__c WITH SECURITY_ENFORCED LIMIT 1]; 
        skuMatriz = matrizCot.Name;   
        return skuMatriz;
      }
    public static List<dsalesCP__c> consultaCodigoPostal(DSALES_QuoteGexWrapper.QuoteGexRequest data){
        List<dsalesCP__c> codigoPos =[SELECT dsalesIsActive__c,Name FROM dsalesCP__c WHERE Name=:data.codigoPostal AND dsalesIsActive__c=true WITH SECURITY_ENFORCED LIMIT 1];
        return codigoPos;
    }
    public static List<DSALES_QuoteGexWrapper.Encuestas> obtenerEncuesta(List<QuoteLineItem> listaPartida, Id productoId, Id QuoteId, String QuoteName) {
        List<DSALES_QuoteGexWrapper.Encuestas> listaEncuestas = new List<DSALES_QuoteGexWrapper.Encuestas>();
                List<dsalesAsignacionEncuesta__c> survey = [SELECT dsalesEncuestaPISyS__c,dsalesEncuestaPISyS__r.dsalesCuestionario__c,dsalesEncuestaPISyS__r.Name,dsalesServicio__c FROM dsalesAsignacionEncuesta__c WHERE dsalesServicio__c=:productoId];
                DSALES_QuoteGexWrapper.Encuestas encuesta = new DSALES_QuoteGexWrapper.Encuestas();
                encuesta.nombreEncuesta = survey[0].dsalesEncuestaPISyS__r.Name;
                encuesta.preguntas = survey[0].dsalesEncuestaPISyS__r.dsalesCuestionario__c;
                listaEncuestas.add(encuesta);
        
        dsalesEncuestaPISyS__c encuestaNew = new dsalesEncuestaPISyS__c();
        String recordTypeId = Schema.SObjectType.dsalesEncuestaPISyS__c.getRecordTypeInfosByName().get('Respuestas').getRecordTypeId();
        encuestaNew.RecordTypeId = recordTypeId;
        encuestaNew.Name = survey[0].dsalesEncuestaPISyS__r.Name+' '+QuoteName;
        encuestaNew.dsalesCuestionario__c = survey[0].dsalesEncuestaPISyS__r.dsalesCuestionario__c;
        encuestaNew.dsalesCotizacion__c = QuoteId;
        insert encuestaNew;
        
        return listaEncuestas;
    }
}