force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Fechadeentregaestimada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeentregaestimada__c</fullName>
    <description>Campo para registrar la fecha estimada de entrega de la moto.</description>
    <label>Fecha de entrega estimada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadeinicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeinicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadetermino__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadetermino__c</fullName>
    <label>Fecha de termino</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_NombreProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NombreProducto__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSALES_NombreProducto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_SKU_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_SKU_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSALES_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>dsalesCiudad__c</fullName>
    <label>Ciudad</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Estado__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>CAMPECHE</fullName>
            </value>
            <value>
                <fullName>CHIAPAS</fullName>
            </value>
            <value>
                <fullName>CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>CIUDAD DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>COAHUILA</fullName>
            </value>
            <value>
                <fullName>COLIMA</fullName>
            </value>
            <value>
                <fullName>DURANGO</fullName>
            </value>
            <value>
                <fullName>ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>GUERRERO</fullName>
            </value>
            <value>
                <fullName>HIDALGO</fullName>
            </value>
            <value>
                <fullName>JALISCO</fullName>
            </value>
            <value>
                <fullName>MICHOACÁN</fullName>
            </value>
            <value>
                <fullName>MORELOS</fullName>
            </value>
            <value>
                <fullName>NAYARIT</fullName>
            </value>
            <value>
                <fullName>NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>OAXACA</fullName>
            </value>
            <value>
                <fullName>PUEBLA</fullName>
            </value>
            <value>
                <fullName>QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>SINALOA</fullName>
            </value>
            <value>
                <fullName>SONORA</fullName>
            </value>
            <value>
                <fullName>TABASCO</fullName>
            </value>
            <value>
                <fullName>TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>TLAXCALA</fullName>
            </value>
            <value>
                <fullName>VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_QuotePdfController_Test.cls
@isTest
public class DSALES_QuotePdfController_Test {
    
    @testSetup 
    static void setUp(){
        // Create test data
        Opportunity opp = new Opportunity(Name='Test Opportunity',StageName='Nuevo',CloseDate=Date.today());
        insert opp;
        
        Product2 prod = new Product2(Name='Test Product', DSales_Tipo_de_Producto__c='Producto');
        insert prod;
        
        String pb2Id=Test.getStandardPricebookId();
        PricebookEntry pb = New PricebookEntry();
        pb.Product2Id = prod.Id;
        pb.PriceBook2Id =pb2Id;
        pb.UseStandardPrice = false;
        pb.UnitPrice=200;
        pb.isActive=true;
        insert pb;
        
        Tienda__c tienda = new Tienda__c( Name= 'Urgarte',dsalesDireccion__c='Test Address', dsalesCodigoPostal__c='12345', DSALES_Ciudad__c='Test City');
        insert tienda;
        
        
        Quote quote = new Quote(Name='Test Quote', OpportunityId=opp.Id,PriceBook2Id=pb2Id,DSales_Tienda__c=tienda.Id );
        insert quote;
        
        
        QuoteLineItem lineItem = new QuoteLineItem(QuoteId=quote.Id, Product2Id=prod.Id, Quantity=1, UnitPrice=10.0, PricebookEntryId=pb.Id);
        insert lineItem;
        
        DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c(DSALES_Oportunidad__c=opp.Id, DSALES_Fechadeentregaestimada__c=Date.today());
        insert pago;
        DSALES_InformacionDePago__c pago1 = new DSALES_InformacionDePago__c(DSALES_Oportunidad__c=opp.Id, DSALES_Fechadeentregaestimada__c=Date.today());
        insert pago1;
    }
    @isTest
    static void createRecordTest(){
        Quote quotes = [SELECT Id, Name, Opportunity.Name,OpportunityId, DSales_Tienda__c,DSales_Tienda__r.Name FROM Quote WHERE Name='Test Quote' WITH SECURITY_ENFORCED LIMIT 1];
        QuoteLineItem quoteLineItems = [SELECT Id,QuoteId,Product2.Name,DSALES_NombreProducto__c,Dsales_Plazo__c, Dsales_Plazo__r.Dsales_Plazo__c,PricebookEntryId,Product2Id,DSALES_SKU__c,Quantity,UnitPrice,DSALES_Fechadeinicio__c,DSALES_Fechadetermino__c,TotalPrice,ListPrice,DSales_SKU_Producto__c,DSALES_Tipodeproducto__c
                                        FROM QuoteLineItem  WITH SECURITY_ENFORCED LIMIT 1];
        id oppId =quotes.OpportunityId;
        Tienda__c tienda = [SELECT Id,Name, dsalesDireccion__c, dsalesCodigoPostal__c, DSALES_Ciudad__c, DSALES_Estado__c FROM Tienda__c WHERE Id=:quotes.DSales_Tienda__c AND Name='Urgarte' WITH SECURITY_ENFORCED LIMIT 1];
        List<DSALES_InformacionDePago__c> paym =[SELECT Id,DSALES_Fechadeentregaestimada__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c=:oppId  WITH SECURITY_ENFORCED LIMIT 1];
        
        
        Test.startTest();
        PageReference pageRef = Page.DSALES_CotizationSm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', quotes.Id);
        DSALES_QuotePdfController controller = new DSALES_QuotePdfController();
        Test.stopTest();
        System.assertEquals(quoteLineItems.QuoteId, quotes.Id, 'La llamada debe devolver un código 200');
        
        
        
        
    }
}