force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Vendedor__c</fullName>
    <description>Número de vendedor</description>
    <label>ID Vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionarlo con el producto seguro</description>
    <label>Seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Seguro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plazos</relationshipLabel>
    <relationshipName>Plazos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Enviarcotizacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Enviarcotizacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cotización enviada al cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadecreacionpresupuesto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecreacionpresupuesto__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de creación cotización</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesColorCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesColorCelular__c</fullName>
    <description>Color de celular comprado</description>
    <label>Color Celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesGenero__c.field-meta.xml
<CustomField>
    <fullName>dsalesGenero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Masculino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesMarcaCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesMarcaCelular__c</fullName>
    <description>Marca de celular comprado</description>
    <label>Marca celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesModeloCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesModeloCelular__c</fullName>
    <description>Modelo de celular comprado</description>
    <label>Modelo Celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesOpcionDePago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionDePago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesPrecioCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesPrecioCelular__c</fullName>
    <description>Precio del celular comprado sin descuentos</description>
    <label>Precio Celular</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Comision__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Comision__c</fullName>
    <description>Campo para registrar la comisión de la póliza</description>
    <label>Comisión</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <description>Campo para recibir las características del seguro</description>
    <label>Descripción</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadeinicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeinicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadetermino__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadetermino__c</fullName>
    <label>Fecha de termino</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_PagoContado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PagoContado__c</fullName>
    <description>Campo para recibir el pago de contado cuando se cotice mensualmente</description>
    <label>Pago de contado</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Pagomensual__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Pagomensual__c</fullName>
    <description>Campo para informar al cliente cuanto pagaría mensualmente</description>
    <label>Pago mensual</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Primaneta__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Primaneta__c</fullName>
    <label>Prima neta</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Recargos__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Recargos__c</fullName>
    <description>Campo para registrar los recargos de la póliza</description>
    <label>Recargos</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Segurogratis__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Segurogratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si el producto lleva seguro gratis</description>
    <label>Seguro gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_TrackingID__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TrackingID__c</fullName>
    <description>Campo para guardar el tracking Id de la solicitud de cotización</description>
    <label>Tracking ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesGastosDeOperacionDelRecibo__c.field-meta.xml
<CustomField>
    <fullName>dsalesGastosDeOperacionDelRecibo__c</fullName>
    <label>Gastos de operación del recibo</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <description>Campo para identificar si la partida es de contado o crédito.</description>
    <label>Opción de pago</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesPagoInicial__c.field-meta.xml
<CustomField>
    <fullName>dsalesPagoInicial__c</fullName>
    <description>Campo para registrar el pago inicial cuando se recibe una cotización a crédito</description>
    <label>Pago inicial</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo para recibir el id de cotización de Interproteccion por cada uno de los paquetes solicitados.</description>
    <label>Quote id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_QuoteDuplicateSC.cls
public with sharing class DSALES_QuoteDuplicateSC { 
    public static Quote cotizacionesNuevas(List<String> partidasSeleccionadas,Datos datos){
        QuoteLineItem cel = new QuoteLineItem();
        List<QuoteLineItem> listaToQuey = new List<QuoteLineItem>();
        List<QuoteLineItem> listToInsert = new List<QuoteLineItem>();
        Quote cotizacionSincronizar = new Quote();
        Quote cotizacionSeguros = new Quote();
        DSALES_QuotePagoSM.updatePago(datos.pago.Id); //verifica que el plazo no sea 0
        Quote cotizacionPrincipal=consultaCotizacion(datos.idCotizacionAnt, datos.idOportunidad);
        QuoteLineItem celular = consultaCelular(datos.pago.DSALES_SKU__c,cotizacionPrincipal.Id);
        if(datos.pago.DSALES_Seguro__c==true && partidasSeleccionadas!=null && partidasSeleccionadas.size()>0){ //compró el seguro; crear solo una cotización extra
            listaToQuey=consultaPartidasSeguro(partidasSeleccionadas,cotizacionPrincipal.Id);
            cotizacionSincronizar= crearNuevaCotizacion(cotizacionPrincipal);
            cel=crearPartidaCelular(celular, cotizacionSincronizar.Id);
            listToInsert=crearPartidasSeguros(listaToQuey,cotizacionSincronizar.Id);
            listToInsert.add(cel);
        }else{ //solo compro el celular; crear dos cotizaciones extras
            System.debug('crea dos cotizaciones_______________');
            listaToQuey = consultaSegurosNoComprados(cotizacionPrincipal.Id,String.valueOf(datos.plazo));
            cotizacionSincronizar =crearNuevaCotizacion(cotizacionPrincipal);
            cotizacionSeguros=crearNuevaCotizacion(cotizacionPrincipal);
            cotizacionSeguros.DSALES_Enviarcotizacion__c=true;
            update cotizacionSeguros;
            cel=crearPartidaCelular(celular, cotizacionSincronizar.Id);
            listToInsert = crearPartidasSeguros(listaToQuey,cotizacionSeguros.Id);
            listToInsert.add(cel);
        }
        if(Schema.sObjectType.QuoteLineItem.isCreateable()) {
            insert listToInsert; 
        }else{
            System.debug('Permisos insuficientes para insertar');
        }
        return cotizacionSincronizar;
    }
    public static List<QuoteLineItem> consultaSegurosNoComprados(String idCotizacion, String plazo){
        System.debug('toma el seguro al plazo de la moto para el correo');
        List<QuoteLineItem> listaSeguros  = new List<QuoteLineItem> ();
        List<QuoteLineItem> seguros =[SELECT Id,LineNumber,DSALES_Tipodeproducto__c,QuoteId,DSALES_TrackingID__c,DSALES_Segurogratis__c,dsalesQuoteId__c,Product2Id,DSALES_SKU__c,
                    DSALES_Fechadeinicio__c,DSALES_Plazo__c,Quantity,ListPrice,DSALES_Fechadetermino__c,dsalesGastosDeOperacionDelRecibo__c,DSALES_Primaneta__c,
                    dsalesDerechosDePoliza__c,DSALES_Comision__c,DSALES_Recargos__c,UnitPrice,TotalPrice,DSALES_Pagomensual__c,DSALES_PagoContado__c,
                    dsalesPagoInicial__c,dsalesOpcionPago__c,DSALES_Descripcion__c,PricebookEntryId
                    FROM QuoteLineItem WHERE QuoteId=:idCotizacion  AND DSALES_Tipodeproducto__c='Seguro' AND Dsales_Plazo__r.Dsales_Plazo__c=:plazo  WITH SECURITY_ENFORCED LIMIT 1];
        if(seguros!=null){
            listaSeguros=seguros;
        }
        System.debug('lista de seguro_____________________'+listaSeguros);
        return listaSeguros;
    }
    public static Quote consultaCotizacion(String idCotizacion, String idOportunidad){
        Quote cotizacionPrincial = new Quote();
        if(!String.isEmpty(idCotizacion)){ 
            cotizacionPrincial= [SELECT Id,AccountId,Name,dsalesGenero__c,DSALES_Fechadenacimiento__c,dsalesListaNegra__c,
                                                    Phone,Email,DSALES_RFC__c,dsalesMotivoDeListaNegra__c,DSales_Vendedor__c,DSales_Tienda__c,DSALES_Fechadecreacionpresupuesto__c,
                                                    dsalesFechaDeComienzoDePoliza__c,dsalesOpcionDePago__c,OpportunityId,Status,ExpirationDate,
                                                    DSALES_Enviarcotizacion__c,dsalesIdentificadorCoppel__c,dsalesIdentificadorVendedor__c,dsalesNumeroSucursal__c,QuoteNumber,IsSyncing,dsalesPrecioCelular__c,dsalesMarcaCelular__c,dsalesModeloCelular__c,dsalesColorCelular__c,dsalesCodigoPostal__c,
                                                    Subtotal,TotalPrice,Discount,RecordTypeId FROM Quote WHERE Id=:idCotizacion AND OpportunityId=:idOportunidad WITH SECURITY_ENFORCED ];
        }
        return cotizacionPrincial;
    }
    public static QuoteLineItem consultaCelular(String sku,String idCotizacion){
        QuoteLineItem partidaCelular= new QuoteLineItem();
        if(!String.isEmpty(sku)){
            partidaCelular=[SELECT Id,LineNumber,DSALES_Tipodeproducto__c,QuoteId,DSALES_TrackingID__c,DSALES_Segurogratis__c,dsalesQuoteId__c,Product2Id,DSALES_SKU__c,
                                            DSALES_Fechadeinicio__c,DSALES_Plazo__c,Quantity,ListPrice,DSALES_Fechadetermino__c,dsalesGastosDeOperacionDelRecibo__c,DSALES_Primaneta__c,
                                            dsalesDerechosDePoliza__c,DSALES_Comision__c,DSALES_Recargos__c,UnitPrice,TotalPrice,DSALES_Pagomensual__c,DSALES_PagoContado__c,
                                            dsalesPagoInicial__c,dsalesOpcionPago__c,DSALES_Descripcion__c,PricebookEntryId
                                            FROM QuoteLineItem WHERE DSALES_SKU__c = :sku AND QuoteId=:idCotizacion WITH SECURITY_ENFORCED LIMIT 1];
        }
        return partidaCelular;
    }
    public static List<QuoteLineItem> consultaPartidasSeguro(List<String> partidasSeleccionadas, String idCotizacion){
        List <QuoteLineItem> partidas = new List <QuoteLineItem>();
        if(partidasSeleccionadas!=null && partidasSeleccionadas.size()>0){
            partidas=[SELECT Id,LineNumber,DSALES_Tipodeproducto__c,QuoteId,DSALES_TrackingID__c,DSALES_Segurogratis__c,dsalesQuoteId__c,Product2Id,DSALES_SKU__c,
                                            DSALES_Fechadeinicio__c,DSALES_Plazo__c,Quantity,ListPrice,DSALES_Fechadetermino__c,dsalesGastosDeOperacionDelRecibo__c,DSALES_Primaneta__c,
                                            dsalesDerechosDePoliza__c,DSALES_Comision__c,DSALES_Recargos__c,UnitPrice,TotalPrice,DSALES_Pagomensual__c,DSALES_PagoContado__c,
                                            dsalesPagoInicial__c,dsalesOpcionPago__c,DSALES_Descripcion__c,PricebookEntryId
                                            FROM QuoteLineItem WHERE Id IN :partidasSeleccionadas AND QuoteId=:idCotizacion WITH SECURITY_ENFORCED];
            
        }
        return partidas;  
    }

    public static List<QuoteLineItem> crearPartidasSeguros(List<QuoteLineItem> listaPartidas,String idCotizacion){
        List<QuoteLineItem> listaNuevasPartidas = new List<QuoteLineItem>();
        for(QuoteLineItem partida:listaPartidas){
            QuoteLineItem partidaNueva = new QuoteLineItem();
            partidaNueva.QuoteId=idCotizacion;
            partidaNueva.dsalesQuoteId__c=partida.dsalesQuoteId__c;
            partidaNueva.Product2Id=partida.Product2Id;
            partidaNueva.PricebookEntryId=partida.PricebookEntryId;
            partidaNueva.DSALES_Plazo__c=partida.DSALES_Plazo__c;
            //partidaNueva.LineNumber=partida.LineNumber;
            //partidaNueva.DSALES_Tipodeproducto__c=partida.DSALES_Tipodeproducto__c;
            //partidaNueva.TotalPrice=partida.TotalPrice;
            //partidaNueva.ListPrice=partida.ListPrice;
            //partidaNueva.DSALES_SKU__c=partida.DSALES_SKU__c;
            partidaNueva.UnitPrice=partida.UnitPrice;
            partidaNueva.DSALES_TrackingID__c=partida.DSALES_TrackingID__c;
            partidaNueva.DSALES_Segurogratis__c=partida.DSALES_Segurogratis__c;
            partidaNueva.DSALES_Fechadeinicio__c=partida.DSALES_Fechadeinicio__c;
            partidaNueva.Quantity=partida.Quantity;
            partidaNueva.DSALES_Fechadetermino__c=partida.DSALES_Fechadetermino__c;
            partidaNueva.dsalesGastosDeOperacionDelRecibo__c=partida.dsalesGastosDeOperacionDelRecibo__c;
            partidaNueva.DSALES_Primaneta__c=partida.DSALES_Primaneta__c;
            partidaNueva.dsalesDerechosDePoliza__c=partida.dsalesDerechosDePoliza__c;
            partidaNueva.DSALES_Comision__c=partida.DSALES_Comision__c;
            partidaNueva.DSALES_Recargos__c=partida.DSALES_Recargos__c;
            partidaNueva.DSALES_Pagomensual__c=partida.DSALES_Pagomensual__c;
            partidaNueva.DSALES_PagoContado__c=partida.DSALES_PagoContado__c;
            partidaNueva.dsalesPagoInicial__c=partida.dsalesPagoInicial__c;
            partidaNueva.dsalesOpcionPago__c=partida.dsalesOpcionPago__c;
            partidaNueva.DSALES_Descripcion__c=partida.DSALES_Descripcion__c;
            listaNuevasPartidas.add(partidaNueva);
            
        }
        return listaNuevasPartidas;
    }
    public static QuoteLineItem crearPartidaCelular(QuoteLineItem celular, String idCotizacion){
        QuoteLineItem partidaNueva = new QuoteLineItem();
        partidaNueva.QuoteId=idCotizacion;
        partidaNueva.dsalesQuoteId__c=celular.dsalesQuoteId__c;
        partidaNueva.Product2Id=celular.Product2Id;
        partidaNueva.PricebookEntryId=celular.PricebookEntryId;
        partidaNueva.DSALES_Plazo__c=celular.DSALES_Plazo__c;
        partidaNueva.UnitPrice=celular.UnitPrice;
        partidaNueva.DSALES_TrackingID__c=celular.DSALES_TrackingID__c;
        partidaNueva.DSALES_Segurogratis__c=celular.DSALES_Segurogratis__c;
        partidaNueva.DSALES_Fechadeinicio__c=celular.DSALES_Fechadeinicio__c;
        partidaNueva.Quantity=celular.Quantity;
        partidaNueva.DSALES_Fechadetermino__c=celular.DSALES_Fechadetermino__c;
        partidaNueva.dsalesGastosDeOperacionDelRecibo__c=celular.dsalesGastosDeOperacionDelRecibo__c;
        partidaNueva.DSALES_Primaneta__c=celular.DSALES_Primaneta__c;
        partidaNueva.dsalesDerechosDePoliza__c=celular.dsalesDerechosDePoliza__c;
        partidaNueva.DSALES_Comision__c=celular.DSALES_Comision__c;
        partidaNueva.DSALES_Recargos__c=celular.DSALES_Recargos__c;
        partidaNueva.DSALES_Pagomensual__c=celular.DSALES_Pagomensual__c;
        partidaNueva.DSALES_PagoContado__c=celular.DSALES_PagoContado__c;
        partidaNueva.dsalesPagoInicial__c=celular.dsalesPagoInicial__c;
        partidaNueva.dsalesOpcionPago__c=celular.dsalesOpcionPago__c;
        partidaNueva.DSALES_Descripcion__c=celular.DSALES_Descripcion__c;
        return partidaNueva;
    }

    public static Quote crearNuevaCotizacion(Quote cotizacionAnterior){
        Quote nuevaCotizacion = new Quote();
        //nuevaCotizacion.AccountId=cotizacionAnterior.AccountId;
        nuevaCotizacion.RecordTypeId=cotizacionAnterior.RecordTypeId;
        nuevaCotizacion.Name=cotizacionAnterior.Name;
        nuevaCotizacion.dsalesGenero__c=cotizacionAnterior.dsalesGenero__c;
        nuevaCotizacion.DSALES_Fechadenacimiento__c=cotizacionAnterior.DSALES_Fechadenacimiento__c;
        nuevaCotizacion.dsalesIdentificadorCoppel__c=cotizacionAnterior.dsalesIdentificadorCoppel__c;
        nuevaCotizacion.dsalesListaNegra__c=cotizacionAnterior.dsalesListaNegra__c;
        nuevaCotizacion.Phone=cotizacionAnterior.Phone;
        nuevaCotizacion.Email=cotizacionAnterior.Email;
        nuevaCotizacion.DSALES_RFC__c=cotizacionAnterior.DSALES_RFC__c;
        nuevaCotizacion.dsalesMotivoDeListaNegra__c=cotizacionAnterior.dsalesMotivoDeListaNegra__c;
        //nuevaCotizacion.QuoteNumber=cotizacionAnterior.QuoteNumber;
        nuevaCotizacion.DSales_Vendedor__c=cotizacionAnterior.DSales_Vendedor__c;
        nuevaCotizacion.DSales_Tienda__c=cotizacionAnterior.DSales_Tienda__c;
        nuevaCotizacion.DSALES_Fechadecreacionpresupuesto__c=cotizacionAnterior.DSALES_Fechadecreacionpresupuesto__c;
        nuevaCotizacion.dsalesFechaDeComienzoDePoliza__c=cotizacionAnterior.dsalesFechaDeComienzoDePoliza__c;
        nuevaCotizacion.dsalesOpcionDePago__c=cotizacionAnterior.dsalesOpcionDePago__c;
        nuevaCotizacion.OpportunityId=cotizacionAnterior.OpportunityId;
        nuevaCotizacion.dsalesIdentificadorVendedor__c=cotizacionAnterior.dsalesIdentificadorVendedor__c;
        nuevaCotizacion.dsalesNumeroSucursal__c=cotizacionAnterior.dsalesNumeroSucursal__c;
        nuevaCotizacion.Status=cotizacionAnterior.Status;
        nuevaCotizacion.ExpirationDate=cotizacionAnterior.ExpirationDate;
        nuevaCotizacion.DSALES_Enviarcotizacion__c=cotizacionAnterior.DSALES_Enviarcotizacion__c;
        //nuevaCotizacion.IsSyncing=cotizacionAnterior.IsSyncing;
        nuevaCotizacion.dsalesPrecioCelular__c=cotizacionAnterior.dsalesPrecioCelular__c;
        nuevaCotizacion.dsalesMarcaCelular__c=cotizacionAnterior.dsalesMarcaCelular__c;
        nuevaCotizacion.dsalesModeloCelular__c=cotizacionAnterior.dsalesModeloCelular__c;
        nuevaCotizacion.dsalesColorCelular__c=cotizacionAnterior.dsalesColorCelular__c;
        nuevaCotizacion.dsalesCodigoPostal__c=cotizacionAnterior.dsalesCodigoPostal__c;
        //nuevaCotizacion.Subtotal=cotizacionAnterior.Subtotal;
        //nuevaCotizacion.TotalPrice=cotizacionAnterior.TotalPrice;
        //nuevaCotizacion.Discount=cotizacionAnterior.Discount;
        if(Schema.sObjectType.Quote.isCreateable()) {
            insert nuevaCotizacion;
        }else{
            System.debug('Permisos insuficientes para insertar');
        }
       
        return nuevaCotizacion;
    }
    
    public class Datos{
        public String idOportunidad {get;set;}
        public String idCotizacionAnt {get;set;}
        public  DSALES_InformacionDePago__c pago {get;set;}
        public Integer plazo {get;set;}

    }
    public class Mapas{
        Map<String, String> product2Map {get;set;}
        Map<String, String> productToPricebookEntryMap {get;set;}
        Map<String, String> plazosMap{get;set;}
    }
    public class ConsultasDatos{
        Quote cotizacionAnterior{get;set;}
        List<QuoteLineItem> partidasSeleccionadas{get;set;}
        QuoteLineItem celular {get;set;}
    }
}