force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal__c</fullName>
    <formula>DSALES_Factura__c  &amp;  DSALES_Clave_Tienda__c  &amp;  TEXT (DAY(DSALES_Fecha__c)) &amp; TEXT (MONTH(DSALES_Fecha__c)) &amp; TEXT (YEAR(DSALES_Fecha__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Universal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/DSALES_Reembolso__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar los reembolso que nos comparte Coppel por cancelaciones o devoluciones.</description>
    <label>Reembolso</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Número de Reembolso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reembolsos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Reembolso__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <description>Importe total de este reembolso.</description>
    <label>Cantidad</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/fields/DSALES_Comentarios__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Comentarios__c</fullName>
    <description>Campo para agregar comentarios para proporcionar detalles adicionales sobre su reembolso</description>
    <label>Comentarios</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/fields/DSALES_Fecha__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha__c</fullName>
    <description>La fecha en que se creó este reembolso.</description>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/fields/DSALES_InformaciondePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformaciondePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionar el reembolso a la información de pago</description>
    <label>Información de pago</label>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Reembolsos</relationshipLabel>
    <relationshipName>Reembolsos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/fields/DSALES_MetododePpago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MetododePpago__c</fullName>
    <description>El método de pago utilizado para crear el pago que se reembolsa.</description>
    <label>Método de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Tarjeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Reembolso__c/fields/DSALES_NumerodeReferencia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NumerodeReferencia__c</fullName>
    <description>ID único para la transacción de reembolso</description>
    <label>Número de referencia</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_ReembolsoWrapperRequest.cls
@RestResource(urlMapping='/insertReembolso/*')
global class DSALES_ReembolsoWrapperRequest {
    @HttpPost
    global static  DSALES_ReembolsoWrapper.ReembolsoResponse createReembolso()
    {
        String id_reembolso='';
        Boolean exito=false;
        String codigo_error='';
        String mensaje_error='';
        
        
        DSALES_ReembolsoWrapper.ReembolsoResponse responsePayload= new DSALES_ReembolsoWrapper.ReembolsoResponse();
        if(RestContext.request != null){
            String Body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(Body)){
                try{
                    DSALES_ReembolsoWrapper.ReembolsoRequest reembolso = (DSALES_ReembolsoWrapper.ReembolsoRequest)JSON.deserialize(body, DSALES_ReembolsoWrapper.ReembolsoRequest.class);
                    //responsePayload = insertReembolso(reembolso);
                    DSALES_Reembolso__c reembolsoRecord = new DSALES_Reembolso__c();
                    List<DSALES_InformacionDePago__c> buscarPago=[SELECT Id FROM DSALES_InformacionDePago__c WHERE DSALES_IDUniversal__c=:reembolso.pago_universal];
                    if(buscarPago.size()>0)
                    {
                        reembolsoRecord.DSALES_InformaciondePago__c=buscarPago[0].id;
                    }
                    reembolsoRecord.DSALES_Comentarios__c=reembolso.comentarios;
                    reembolsoRecord.DSALES_Fecha__c=reembolso.fecha;
                    reembolsoRecord.Cantidad__c=reembolso.cantidad;
                    reembolsoRecord.DSALES_MetododePpago__c=reembolso.metodo_pago;
                    reembolsoRecord.DSALES_NumerodeReferencia__c=reembolso.numero_referencia;
                    
                    insert reembolsoRecord;
                    
                     id_reembolso=reembolsoRecord.Id;
                     exito=true;
                     codigo_error='';
                     mensaje_error='Reembolso creado';
                }
                
                catch(Exception.JSONException e)
                {
                    exito = false;
                    mensaje_error =e.GetMessage();
                    codigo_error=String.valueOf(DSALES_Utility.BAD_REQUEST_CODE);
                    
                }
                catch(Exception e){
                   exito = false;
                  mensaje_error = e.GetMessage();
                    codigo_error=String.valueOf(DSALES_Utility.INTERNAL_ERROR_CODE);
                    
                    
                }
            }
        }
        responsePayload.id_reembolso=id_reembolso;
        responsePayload.exito=exito;
         responsePayload.mensaje_error=mensaje_error;
         responsePayload.codigo_error=codigo_error;
        return responsePayload;
        
    }
    
    
}