force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Plazodecomprademoto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazodecomprademoto__c</fullName>
    <description>Campo para registrar el plazo en que se vendió la moto</description>
    <label>Plazo de compra de moto</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Comision__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Comision__c</fullName>
    <description>Campo para registrar la comisión de la póliza</description>
    <label>Comisión</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Derechosdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Derechosdepliza__c</fullName>
    <label>Derechos de póliza</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Gastosdeoperacindelrecibo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Gastosdeoperacindelrecibo__c</fullName>
    <label>Gastos de operación del recibo</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Impuestos__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Impuestos__c</fullName>
    <label>Impuestos</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_NombreProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NombreProducto__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSALES_NombreProducto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Pagomensual__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Pagomensual__c</fullName>
    <description>Campo para informar al cliente cuanto pagaría mensualmente</description>
    <label>Pago mensual</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Primaneta__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Primaneta__c</fullName>
    <label>Prima neta</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Recargos__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Recargos__c</fullName>
    <description>Campo para registrar los recargos de la póliza</description>
    <label>Recargos</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Segurogratis__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Segurogratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si el producto lleva seguro gratis</description>
    <label>Seguro gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_QuotePagoSMHelper.cls
/**
 * @description       : 
 * @author            : 
 * @group             : 
 * @last modified on  : 04-24-2023
 * @last modified by  : Juan Antonio Flores
 * Modifications Log 
 * Ver   Date          Author             Modification
 * 1.0   04-24-2023                       Initial Version
**/
public with sharing class DSALES_QuotePagoSMHelper {

    private static final  String RC_GRATIS='RC';

    /////////////////////////////-----NEW------/////////////////////////////

    public static void crearCotizacionesNuevas(String idPago, List<String> partidasSeleccionadas, String skuMoto){
        if(skuMoto!=null){
            crearCotNueva2(idPago, partidasSeleccionadas, skuMoto);
        }
        else{
            creacionDePartida(idPago, partidasSeleccionadas, skuMoto);
        }
    }


    public static void crearCotNueva2(String idPago, List<String> partidasSeleccionadas, String skuMoto){
        ////////////////////////
        List<String> listIdCotiza = new List<String>();
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Plazodecomprademoto__c,DSALES_Seguro__c,DSALES_Oportunidad__c,DSALES_Nombre_del_Vendedor__c,DSales_Tienda__c,DSALES_SKU__c  
                                        FROM DSALES_InformacionDePago__c 
                                        WHERE Id=:idPago WITH SECURITY_ENFORCED];
        Quote beforeCot = [SELECT Id,OpportunityId,AccountId FROM Quote WHERE OpportunityId =:pago.DSALES_Oportunidad__c WITH SECURITY_ENFORCED];
        QuoteLineItem producto =[SELECT Id,DSALES_NombreProducto__c, DSALES_Segurogratis__c FROM QuoteLineItem  WHERE DSALES_SKU__c=:skuMoto  AND quoteId=:beforeCot.Id WITH SECURITY_ENFORCED LIMIT 1];
        ////////////////////////
        if(producto.DSALES_Segurogratis__c==true && partidasSeleccionadas!=null && partidasSeleccionadas.size()==1){
            for(Integer i=0;i<2;i++){
                String idCotizacion=DSALES_QuotePagoSM.crearCotizacion(beforeCot.Id,pago.Id);
                listIdCotiza.add(idCotizacion);
            } 
            String idCotSin=DSALES_QuotePagoSM.crear2CotPartidas(beforeCot.Id,listIdCotiza,Integer.valueOf(pago.DSALES_Plazodecomprademoto__c), partidasSeleccionadas,skuMoto);
            if(idCotSin!=null|| idCotSin!=''){
                DSALES_QuotePagoSM.sincronizarOportunidad(idCotSin);
            }
        }
        else if(producto.DSALES_Segurogratis__c==true && partidasSeleccionadas!=null && partidasSeleccionadas.size()==2){
            //solo crear una cotizacion
            creacionDePartida(idPago, partidasSeleccionadas, skuMoto);
        }
        else if(producto.DSALES_Segurogratis__c==false){
            //solo crear una cotizacion
            creacionDePartida(idPago, partidasSeleccionadas, skuMoto);
        }
    }


    public static void creacionDePartida(String idPago, List<String> partidasSeleccionadas, String skuMoto){
        ///////////////
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Plazodecomprademoto__c,DSALES_Seguro__c,DSALES_Oportunidad__c,DSALES_Nombre_del_Vendedor__c,DSales_Tienda__c,DSALES_SKU__c  
                                        FROM DSALES_InformacionDePago__c 
                                        WHERE Id=:idPago WITH SECURITY_ENFORCED];
        Quote beforeCot = [SELECT Id,OpportunityId,AccountId FROM Quote WHERE OpportunityId =:pago.DSALES_Oportunidad__c WITH SECURITY_ENFORCED];
        ///////////////
        String idCotizacion=DSALES_QuotePagoSM.crearCotizacion(beforeCot.Id,pago.Id);
        Map<String, String> ambasCotizaciones=new Map<String, String>();
        ambasCotizaciones.put('beCot',beforeCot.Id);
        ambasCotizaciones.put('cot',idCotizacion);
        DSALES_QuotePagoSM.crearPartidas(ambasCotizaciones, partidasSeleccionadas, skuMoto);
        if(idCotizacion!=null || idCotizacion!=''){
            DSALES_QuotePagoSM.sincronizarOportunidad(idCotizacion);
        } 
    }

    public static QuoteLineItem llenarPartida(QuoteLineItem ql, QuoteLineItem q){
        QuoteLineItem newpartida=new QuoteLineItem();
        if(ql.DSALES_NombreProducto__c == q.DSALES_NombreProducto__c){
            if( ql.DSALES_Plazo__c == q.DSALES_Plazo__c){
                if(ql.DSALES_Segurogratis__c==true && ql.DSALES_Tipodeproducto__c=='Seguro'){
                    ql.UnitPrice=0;
                    ql.DSALES_Gastosdeoperacindelrecibo__c=0;
                    ql.DSALES_Primaneta__c=0;
                    ql.DSALES_Derechosdepliza__c=0;
                    ql.DSALES_Comision__c=0;
                    ql.DSALES_Recargos__c=0;
                    ql.DSALES_Impuestos__c=0;
                    ql.DSALES_Pagomensual__c=0;
                }
                else{
                    ql.UnitPrice=q.UnitPrice;
                }
                newpartida=ql;
            }
        }  
        return newpartida;
    }

}