force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Fechadeentregaestimada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeentregaestimada__c</fullName>
    <description>Campo para registrar la fecha estimada de entrega de la moto.</description>
    <label>Fecha de entrega estimada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_FolioTransaccion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FolioTransaccion__c</fullName>
    <label>Folio de transacción</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Vendedor__c</fullName>
    <description>Número de vendedor</description>
    <label>ID Vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dsalesCiudad__c/dsalesCiudad__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nombre de Ciudad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_EmailNew__c.field-meta.xml
<CustomField>
    <fullName>DSALES_EmailNew__c</fullName>
    <label>Email Solicitante</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_fechadecreacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_fechadecreacion__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de creación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadecreacionpresupuesto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecreacionpresupuesto__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de creación cotización</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Plazoacotizar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazoacotizar__c</fullName>
    <description>Campo para recibir el plazo máximo a cotizar con proveedor.</description>
    <label>Plazo a cotizar</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesOpcionDePago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionDePago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadeinicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeinicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Fechadetermino__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadetermino__c</fullName>
    <label>Fecha de termino</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_NombreProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NombreProducto__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSALES_NombreProducto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_SKU_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_SKU_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSALES_Estado__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>CAMPECHE</fullName>
            </value>
            <value>
                <fullName>CHIAPAS</fullName>
            </value>
            <value>
                <fullName>CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>CIUDAD DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>COAHUILA</fullName>
            </value>
            <value>
                <fullName>COLIMA</fullName>
            </value>
            <value>
                <fullName>DURANGO</fullName>
            </value>
            <value>
                <fullName>ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>GUERRERO</fullName>
            </value>
            <value>
                <fullName>HIDALGO</fullName>
            </value>
            <value>
                <fullName>JALISCO</fullName>
            </value>
            <value>
                <fullName>MICHOACÁN</fullName>
            </value>
            <value>
                <fullName>MORELOS</fullName>
            </value>
            <value>
                <fullName>NAYARIT</fullName>
            </value>
            <value>
                <fullName>NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>OAXACA</fullName>
            </value>
            <value>
                <fullName>PUEBLA</fullName>
            </value>
            <value>
                <fullName>QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>SINALOA</fullName>
            </value>
            <value>
                <fullName>SONORA</fullName>
            </value>
            <value>
                <fullName>TABASCO</fullName>
            </value>
            <value>
                <fullName>TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>TLAXCALA</fullName>
            </value>
            <value>
                <fullName>VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesCiudad__c.field-meta.xml
<CustomField>
    <fullName>dsalesCiudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>dsalesCiudad__c</referenceTo>
    <relationshipLabel>Tiendas</relationshipLabel>
    <relationshipName>Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_QuotePdfController.cls
/*********************************************************************************************************************************************************************
@ Class Name :DSALES_QuotePdfController  
@ Author : Namrata Katore
@ Purpose : controller class to create a vf page
@ Date : 10/5/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/

public with sharing class DSALES_QuotePdfController {
    public Quote quote {get; set;}
    public List<QuoteLineItem> quoteLineItems {get; set;}
    public Tienda__c tienda { get; set; }
    public DSALES_InformacionDePago__c pago {get; set;}
    public string quoteId {get;set;}
    
    public DSALES_QuotePdfController() {
        try{
            Id quoteId = ApexPages.currentPage().getParameters().get('quoteId');
            List<Quote> quotes = [SELECT Id, Name, Opportunity.Name,OpportunityId, DSALES_EmailNew__c, DSales_Tienda__c,DSales_Vendedor__c,DSALES_Plazoacotizar__c,DSALES_Fechadecreacionpresupuesto__c,Opportunity.DSALES_InformacionDePago__r.DSALES_Fechadeentregaestimada__c,
                                  ExpirationDate,QuoteNumber,DSALES_fechadecreacion__c,Email,dsalesOpcionDePago__c, RecordType.Name FROM Quote WHERE Id = :quoteId WITH SECURITY_ENFORCED LIMIT 1];
            
            if (quotes.size() > 0) {
                quote = quotes[0];
                quoteLineItems = [SELECT Id,QuoteId,Product2.Name,DSALES_NombreProducto__c,Dsales_Plazo__c, Dsales_Plazo__r.Dsales_Plazo__c,PricebookEntryId,Product2Id,DSALES_SKU__c,Quantity,UnitPrice,DSALES_Fechadeinicio__c,DSALES_Fechadetermino__c,TotalPrice,ListPrice,DSales_SKU_Producto__c,DSALES_Tipodeproducto__c
                                  FROM QuoteLineItem WHERE QuoteId = :quoteId WITH SECURITY_ENFORCED LIMIT 10];
                tienda = [SELECT Id, Name, dsalesDireccion__c, dsalesCodigoPostal__c, dsalesCiudad__r.Name, DSALES_Estado__c FROM Tienda__c WHERE Id = :quote.DSales_Tienda__c  LIMIT 1];
                System.debug(quote.DSales_Tienda__c);
                pago =[SELECT Id,DSALES_Fechadeentregaestimada__c, DSALES_FolioTransaccion__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c=:quote.OpportunityId WITH SECURITY_ENFORCED LIMIT 1];
                
            }
        } catch(System.QueryException e){
            System.debug('error--------->'+e.getLineNumber() + e.getMessage());
        }
    }
    
    
}