force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_emitir_poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_emitir_poliza__c</fullName>
    <defaultValue>false</defaultValue>
    <description>determina si se manda a emitir la póliza o no.</description>
    <label>Emitir póliza</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.dsalesCliente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_InsurancePolicyAssets.cls
public with sharing class DSALES_InsurancePolicyAssets {
    public static void agregarDatosDeActivo(List<InsurancePolicyAsset> activos){
        for(InsurancePolicyAsset i:activos){
            System.debug('Se agregan datos del activo');
            DSALES_CreateInsurancePolicy.agregarDatosDeActivo(i.Id);
        }
    }
    public static void cancelarPoliza(Map<Id,SObject> existingRecords, List<SObject> records){
        List<InsurancePolicyAsset> listRecord = (List<InsurancePolicyAsset>)records;
        for(InsurancePolicyAsset a:listRecord){
            InsurancePolicyAsset assetOld = (InsurancePolicyAsset)existingRecords.get(a.Id);
            if(assetOld.Estatus__c!=a.Estatus__c){
                if(a.Estatus__c=='Devuelto' ||a.Estatus__c=='Cancelado'){
                    DSALES_CreateInsurancePolicy.cancelarPoliza(a.Id);
                }
                
            }
            
        }
     }
    
    
    public static void emisionDePoliza(List<InsurancePolicyAsset> records){
        System.debug('Se solicita la emisión de póliza');
        List<InsurancePolicyAsset> listRecord = (List<InsurancePolicyAsset>)records;
        List<InsurancePolicyAsset> listaActivos =[SELECT Id,DSALES_Numeroserie__c,DSALES_emitir_poliza__c,DSALES_Motoexterna__c,DSALES_InformacionPago__c FROM InsurancePolicyAsset WHERE Id IN:listRecord];
        System.debug('activo size:'+listaActivos.size());
        List<String> idsPago = new List<String>();
        for(InsurancePolicyAsset a:listaActivos){
           idsPago.add(a.DSALES_InformacionPago__c);
        }
        System.debug('pagos ids size:'+idsPago.size());
       	List<DSALES_InformacionDePago__c> listPagos=[SELECT Id,DSALES_Poliza__c,DSALES_Motoentregada__c FROM DSALES_InformacionDePago__c WHERE Id IN:idsPago AND DSALES_Motoentregada__c=true  AND DSALES_Seguro__c=true ];
		for(InsurancePolicyAsset a:listaActivos){
            System.debug('serie:'+a.DSALES_Numeroserie__c);
            System.debug('emitir?:'+a.DSALES_emitir_poliza__c);
            System.debug('externa?:'+a.DSALES_Motoexterna__c);
            if( a.DSALES_Numeroserie__c!='' && a.DSALES_emitir_poliza__c==true && a.DSALES_Motoexterna__c==false){
                for(DSALES_InformacionDePago__c pago:[SELECT Id,DSALES_Poliza__c,DSALES_Motoentregada__c FROM DSALES_InformacionDePago__c WHERE Id IN:idsPago AND DSALES_Motoentregada__c=true  AND DSALES_Seguro__c=true ]){
                   System.debug('Se emite');
                    DSALES_CreateInsurancePolicy.estatusTramite(pago.DSALES_Poliza__c);
                    DSALES_NuevaPoliza.invokeService(pago.DSALES_Poliza__c);
                }
            }
        }
    }
}