force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
            <value>
                <fullName>Reembolso</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Fechadeentregaestimada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeentregaestimada__c</fullName>
    <description>Campo para registrar la fecha estimada de entrega de la moto.</description>
    <label>Fecha de entrega estimada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_FolioTransaccion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FolioTransaccion__c</fullName>
    <label>Folio de transacción</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal1__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal1__c</fullName>
    <description>Campo para recibir el Id de la venta el cual estará compuesto</description>
    <label>ID Universal</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Plazodecomprademoto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazodecomprademoto__c</fullName>
    <description>Campo para registrar el plazo en que se vendió la moto</description>
    <label>Plazo de compra de moto</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_TipoFolio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoFolio__c</fullName>
    <label>Tipo de folio</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/dsalesContratante__c.field-meta.xml
<CustomField>
    <fullName>dsalesContratante__c</fullName>
    <label>Contratante</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/Pagos_de_Venta_de_SC.recordType-meta.xml
<RecordType>
    <fullName>Pagos_de_Venta_de_SC</fullName>
    <active>true</active>
    <description>Tipo de registro para información de pagos de Seguros de celulares</description>
    <label>Pagos de Venta de SC</label>
</RecordType>

force-app/main/default/objects/DSALES_Partidadepago__c/DSALES_Partidadepago__c.object-meta.xml
<CustomObject>
    <label>Partida de pago</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Partida de pago Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partidas de pagos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Partidadepago__c/fields/DSALES_Pago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Pago__c</fullName>
    <description>Campo para registrar el monto que se abono con la forma de pago</description>
    <label>Pago</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Partidadepago__c/fields/DSALES_Tipodepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodepago__c</fullName>
    <description>Campo para registrar que tipo de pago es.</description>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tarjeta</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Reembolso</fullName>
            </value>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Dolar</fullName>
            </value>
            <value>
                <fullName>Codi</fullName>
            </value>
            <value>
                <fullName>Documentos por Cobrar (Convención y Sedesol)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de celulares del grupo Coppel.</description>
    <label>Seguro de celulares</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_PaymentInfoWrapperRequest.cls
@RestResource(urlMapping='/insertPaymentInformationSM/*')
global with sharing class DSALES_PaymentInfoWrapperRequest {
    @HttpPost
    global static DSALES_PaymentInfoWrapper.PaymentResponse crearPago(){
        DSALES_PaymentInfoWrapper.PaymentResponse responsePago = new DSALES_PaymentInfoWrapper.PaymentResponse();      
        Boolean exito = false;
        String mensajeError = '';
        Integer codigoError;
        String pagoId='';
        if(RestContext.request != null){
            try{
                String body = System.RestContext.request.requestBody.toString();
                if(String.isNotBlank(body)){
                    DSALES_PaymentInfoWrapper.PaymentRequest pago = (DSALES_PaymentInfoWrapper.PaymentRequest)JSON.deserialize(body, DSALES_PaymentInfoWrapper.PaymentRequest.class);            
                    pagoId = insertarPago(pago,'');
                    exito=true;
                }
            }catch(Exception.JSONException jsonException){
                exito = false;
                mensajeError = DSALES_Utility.BAD_REQUEST_MSJ;
                codigoError = DSALES_Utility.BAD_REQUEST_CODE; 
            }catch(Exception e){
                exito = false;
                mensajeError = DSALES_Utility.INTERNAL_ERROR_MSJ;
                codigoError = DSALES_Utility.INTERNAL_ERROR_CODE;
            }
        }
        responsePago.pagoId=pagoId;
        responsePago.exito = exito;
        responsePago.mensajeError = mensajeError;
        responsePago.codigoError = codigoError;
        
        
        return responsePago;
    }
    public static String insertarPago(DSALES_PaymentInfoWrapper.PaymentRequest pago,String contratante){
        Boolean exito = false;
        String mensajeError = '';
        Integer codigoError;
        DSALES_InformacionDePago__c nuevoPago = new DSALES_InformacionDePago__c();
        List<DSALES_Partidadepago__c> listaPartidasPago = new List<DSALES_Partidadepago__c>();
        try{
            String recordTypePagoSM = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();
            String recordTypePagoSC =Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('Pagos_de_Venta_de_SC').getRecordTypeId();
            Opportunity oportunidad =[SELECT Id,AccountId,RecordTypeId FROM Opportunity WHERE Id=:pago.idOportunidad WITH SECURITY_ENFORCED];
            String recordTypeOpportSC =Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('dsalesSeguroCelulares').getRecordTypeId();
            String recordTypeOpportSM =Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Seguro_de_Moto').getRecordTypeId();
            Tienda__c tienda =[SELECT Id,DSales_TiendaID__c FROM Tienda__c WHERE DSales_TiendaID__c=:pago.claveTienda WITH SECURITY_ENFORCED];
            Account cliente=[SELECT Id,	FinServ__BillingAddress__pc FROM Account WHERE Id=:oportunidad.AccountId WITH SECURITY_ENFORCED];
            String tipoDeRegOpp=oportunidad.RecordTypeId;
            if(tipoDeRegOpp==recordTypeOpportSM){
                nuevoPago.RecordTypeId=recordTypePagoSM;
                nuevoPago.DSALES_Plazodecomprademoto__c=pago.plazos;
            }
            else if(tipoDeRegOpp==recordTypeOpportSC){
                nuevoPago.RecordTypeId=recordTypePagoSC;
            }
            nuevoPago.DSALES_Cliente__c=cliente.Id;
            nuevoPago.DSALES_Oportunidad__c=pago.idOportunidad;
            
            nuevoPago.DSALES_Estatus__c='Acreditado';
            nuevoPago.DSALES_SKU__c=pago.sku;
            nuevoPago.DSALES_Montototal__c=pago.totalFactura;
            nuevoPago.DSALES_Nombre_del_Vendedor__c=pago.nombreVendedor;
            nuevoPago.DSALES_Caja__c=pago.numeroCaja;
            nuevoPago.DSALES_Seguro__c=pago.seguro;
            
            if(pago.fechaEntrega!=null){
              nuevoPago.DSALES_Fechadeentregaestimada__c=pago.fechaEntrega;   
            }
            nuevoPago.DSALES_Fecha__c=pago.fechaVenta;
           	nuevoPago.DSales_Tienda__c=tienda.Id;
            nuevoPago.DSALES_IDUniversal1__c=pago.idUniversal;
            nuevoPago.DSALES_FolioTransaccion__c=pago.folioTransaccion;
           
            nuevoPago.DSALES_TipoFolio__c=pago.tipoFolio;
            nuevoPago.dsalesContratante__c=contratante;
            if(cliente.FinServ__BillingAddress__pc!=null){
                String direcion =cliente.FinServ__BillingAddress__pc.replace('<br>', ',');
                nuevoPago.DSALES_DireccionCliente__c=direcion;
            }
            if(Schema.sObjectType.DSALES_InformacionDePago__c.isCreateable()) {
                insert nuevoPago;
                System.debug('pago creado');
            }else{
                System.debug('Permisos insuficientes para insertar');
            }
            if(pago.ListaDePagos!=null){
                for(DSALES_PaymentInfoWrapper.listaDePago part : pago.listaDePagos){
                    DSALES_Partidadepago__c partida = new DSALES_Partidadepago__c();
                    partida.DSALES_Informaciondepago__c=nuevoPago.Id;
                    partida.DSALES_Tipodepago__c=part.metodoPago;
                    partida.DSALES_Pago__c=part.pago;
                    listaPartidasPago.add(partida);
                }
                if(Schema.sObjectType.DSALES_Partidadepago__c.isCreateable()) {
                    insert listaPartidasPago;
                }else{
                    System.debug('Permisos insuficientes para insertar');
                }
                
            }
        }catch(Exception e){
            System.debug('ERROR EN PAGO_______'+e.getLineNumber()+e.getMessage());
            if(nuevoPago!=null && nuevoPago.Id!=null){
                delete nuevoPago;
            }
        }
        
        return nuevoPago.Id;
    }
}