force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Plazodecomprademoto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazodecomprademoto__c</fullName>
    <description>Campo para registrar el plazo en que se vendió la moto</description>
    <label>Plazo de compra de moto</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Vendedor__c</fullName>
    <description>Número de vendedor</description>
    <label>ID Vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/DSALES_TipodeUso__c/DSALES_TipodeUso__c.object-meta.xml
<CustomObject>
    <description>Objeto para tener el registro de los tipos de uso de vehículos</description>
    <label>Tipo de Uso</label>
    <nameField>
        <label>Nombre de Tipo de uso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Usos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/DSALES_Cdigopostal__c.field-meta.xml
<CustomField>
    <fullName>dsalesCodigoPostal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadecomienzodepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecomienzodepliza__c</fullName>
    <label>Fecha de comienzo de póliza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Gnero__c.field-meta.xml
<CustomField>
    <fullName>dsalesGenero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_IDdelvehculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDdelvehculo__c</fullName>
    <label>ID del vehículo</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Opcindepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcindepago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Plazoacotizar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazoacotizar__c</fullName>
    <description>Campo para recibir el plazo máximo a cotizar con proveedor.</description>
    <label>Plazo a cotizar</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_PlazoacotizarRC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PlazoacotizarRC__c</fullName>
    <label>Plazo a cotizar RC</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Tipodeuso__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoUso__c</fullName>
    <description>Campo para identificar cual es el tipo de uso del vehículo para la cotización.</description>
    <label>Tipo de uso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Particular</fullName>
            </value>
            <value>
                <fullName>Reparto de comida</fullName>
            </value>
            <value>
                <fullName>Todo terreno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Tipodeveihculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeveihculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionar el tipo del vehículo a la cotización</description>
    <label>Tipo de vehículo</label>
    <referenceTo>DSALES_Tipodevehculo__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_TipoUso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoUso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Uso</label>
    <referenceTo>dsalesTipoUso__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_TrakingID__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TrakingID__c</fullName>
    <description>Campo para registrar el ID de solicitud de cotización del proveedor</description>
    <label>Tracking ID</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lista_negra__c.field-meta.xml
<CustomField>
    <fullName>dsalesListaNegra__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lista negra</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Motivo_de_lista_negra__c.field-meta.xml
<CustomField>
    <fullName>dsalesMotivoDeListaNegra__c</fullName>
    <label>Motivo de lista negra</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSALES_Cdigopostal__c.field-meta.xml
<CustomField>
    <fullName>dsalesCodigoPostal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_QuotePagoSmTest.cls
@isTest
public with sharing class DSALES_QuotePagoSmTest {
    @TestSetup
    static void makeData(){
        Account acc = new Account();
        acc.Name='testL';
        acc.BillingCity = 'test';
        acc.BillingStreet = 'calle 3 test';
        acc.BillingState = 'CDMX';
        acc.BillingPostalCode = '666666';
        acc.BillingCountry='México';
        insert acc;
        String recordTypeId = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'testL';
        opp.AccountId = acc.Id;
        opp.CloseDate = Date.Today();
        opp.StageName = 'Nuevo';
        insert opp;
        
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  'CPPL-UGARTE';
        insert t;

        Quote cotizacion = new Quote();
        cotizacion.OpportunityId=opp.Id;
        cotizacion.Name='Test';
        cotizacion.DSALES_Fechadenacimiento__c='2022/01/01';
        cotizacion.Email='pruebas@inv.com';
        cotizacion.DSALES_Cobertura__c='A';
        cotizacion.DSALES_Opcindepago__c='Mensual';
        cotizacion.DSALES_Gnero__c='F';
        cotizacion.Phone='9564562123';
        cotizacion.DSALES_Cdigopostal__c=12;
        cotizacion.DSALES_Fechadecomienzodepliza__c=beforeCot.DSALES_Fechadecomienzodepliza__c;
        cotizacion.Lista_negra__c=beforeCot.Lista_negra__c;
        cotizacion.Motivo_de_lista_negra__c=beforeCot.Motivo_de_lista_negra__c;
        cotizacion.DSALES_TrakingID__c=beforeCot.DSALES_TrakingID__c;
        cotizacion.DSales_Vendedor__c=pago.DSALES_Nombre_del_Vendedor__c;
        cotizacion.DSales_Vendedor__c=beforeCot.DSales_Vendedor__c;
        cotizacion.DSales_Tienda__c=pago.DSales_Tienda__c;
        cotizacion.DSales_Tienda__c=beforeCot.DSales_Tienda__c;
        cotizacion.Tax=beforeCot.Tax;
        cotizacion.DSALES_IDdelvehculo__c=beforeCot.DSALES_IDdelvehculo__c;
        cotizacion.DSALES_Plazoacotizar__c=pago.DSALES_Plazodecomprademoto__c;
        cotizacion.DSALES_PlazoacotizarRC__c=beforeCot.DSALES_PlazoacotizarRC__c;
        cotizacion.DSALES_Tipodeuso__c=beforeCot.DSALES_Tipodeuso__c;
        cotizacion.DSALES_RFC__c=beforeCot.DSALES_RFC__c;
        cotizacion.DSALES_TipoUso__c=beforeCot.DSALES_TipoUso__c;
        cotizacion.DSALES_Tipodeveihculo__c=beforeCot.DSALES_Tipodeveihculo__c;
        insert cotizacion;
    }
    
}