force-app/main/default/objects/Account/fields/CP_BillingStateCode__c.field-meta.xml
<CustomField>
    <fullName>CP_BillingStateCode__c</fullName>
    <description>Código de Estado del sistema de Cartera</description>
    <label>Código de Estado de Residencia</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesActividad__c.field-meta.xml
<CustomField>
    <fullName>dsalesActividad__c</fullName>
    <label>Actividad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tienda Departamental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesCodigoColonia__c.field-meta.xml
<CustomField>
    <fullName>dsalesCodigoColonia__c</fullName>
    <description>Campo para registrar el código de la colonia</description>
    <label>Código de colonia</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesFechaConstitucion__c.field-meta.xml
<CustomField>
    <fullName>dsalesFechaConstitucion__c</fullName>
    <label>Fecha de Constitución</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesGiroComercial__c.field-meta.xml
<CustomField>
    <fullName>dsalesGiroComercial__c</fullName>
    <label>Giro comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0020 Comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesNacionalidadSociedad__c.field-meta.xml
<CustomField>
    <fullName>dsalesNacionalidadSociedad__c</fullName>
    <label>Nacionalidad de la Sociedad</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesNombreApoderadoLegal__c.field-meta.xml
<CustomField>
    <fullName>dsalesNombreApoderadoLegal__c</fullName>
    <label>Nombre del apoderado legal</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesNumeroExterior__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroExterior__c</fullName>
    <description>Campo para recibir el numero exterior</description>
    <label>Número exterior</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesNumeroInterior__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroInterior__c</fullName>
    <description>Campo para recibir el numero interior</description>
    <label>Número interior</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesRfc__c.field-meta.xml
<CustomField>
    <fullName>dsalesRfc__c</fullName>
    <label>RFC</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesSegundoCorreo__c.field-meta.xml
<CustomField>
    <fullName>dsalesSegundoCorreo__c</fullName>
    <label>Segundo correo</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesTipoPersona__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoPersona__c</fullName>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Física</fullName>
            </value>
            <value>
                <fullName>Moral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal1__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal1__c</fullName>
    <description>Campo para recibir el Id de la venta el cual estará compuesto</description>
    <label>ID Universal</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Plazodecomprademoto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazodecomprademoto__c</fullName>
    <description>Campo para registrar el plazo en que se vendió la moto</description>
    <label>Plazo de compra de moto</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Aseguradora__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Aseguradora__c</fullName>
    <formula>LOWER(TEXT(SourceQuote.DSALES_Aseguradora__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aseguradora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Opcionpago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcionpago__c</fullName>
    <formula>TEXT(SourceQuote.dsalesOpcionDePago__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opción de pago</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Tipovehiculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipovehiculo__c</fullName>
    <formula>SourceQuote.dsalesTipoDeVehiculo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de vehículo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesEstatusPoliza__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstatusPoliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepoliza</fullName>
                <default>true</default>
                <label>Prepóliza</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <label>En trámite</label>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>En solicitud</fullName>
                <isActive>false</isActive>
                <label>En solicitud</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesIMEI__c.field-meta.xml
<CustomField>
    <fullName>dsalesIMEI__c</fullName>
    <description>IMEI del producto (Identificador único)</description>
    <label>IMEI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo que almacena el ID de la cotización del seguro ganador y compartirlo en la emisión de póliza.</description>
    <label>Quote id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesTipoServicio__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoServicio__c</fullName>
    <formula>TEXT(SourceQuote.dsalesTipoDeServicioDelVehiculo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de servicio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesTipoUso__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoUso__c</fullName>
    <formula>SourceQuote.DSALES_TipoUso__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de uso</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <description>Registros de seguro de celulares</description>
    <label>Seguro de Celulares</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/dsalesNumeroSucursal__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroSucursal__c</fullName>
    <description>Número de Sucursal de la tienda Coppel</description>
    <label>Numero de sucursal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de celulares del grupo Coppel.</description>
    <label>Seguro de celulares</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Product2/fields/dsalesImei__c.field-meta.xml
<CustomField>
    <fullName>dsalesImei__c</fullName>
    <description>IMEI de dispositivo registrado</description>
    <label>IMEI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <inlineHelpText>A=Anual
C=Contado
M=Mensual</inlineHelpText>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Contado</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <description>tipo de registro para generación de seguros para celulares</description>
    <label>Seguro de Celulares</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSALES_Aseguradora__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Aseguradora__c</fullName>
    <label>Aseguradora</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualitas</fullName>
                <default>true</default>
                <label>qualitas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_IDdelasociado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDdelasociado__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>ID del asociado</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Negocio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coppel</fullName>
                <default>true</default>
                <label>Coppel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesCodigoDePromocion__c.field-meta.xml
<CustomField>
    <fullName>dsalesCodigoDePromocion__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Código de promoción</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesIdDeVehiculo__c.field-meta.xml
<CustomField>
    <fullName>dsalesIdDeVehiculo__c</fullName>
    <label>ID del vehículo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesValorFactura__c.field-meta.xml
<CustomField>
    <fullName>dsalesValorFactura__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar si estamos recibiendo el valor de la factura</description>
    <label>Valor de la factura</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/DSALES_VentaSM.recordType-meta.xml
<RecordType>
    <fullName>DSALES_VentaSM</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones del producto SM.</description>
    <label>Venta de Seguro de Motos</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_TrackingID__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TrackingID__c</fullName>
    <description>Campo para guardar el tracking Id de la solicitud de cotización</description>
    <label>Tracking ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <description>Campo para identificar si la partida es de contado o crédito.</description>
    <label>Opción de pago</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo para recibir el id de cotización de Interproteccion por cada uno de los paquetes solicitados.</description>
    <label>Quote id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_VentaSMRest.cls
@RestResource(urlMapping='/ventaSM/*')
global without sharing class DSALES_VentaSMRest {
    public static final String NOMBRE_CONTRATANTE =DSALES_Utility.getNombreContratante('dsalesNombre');
    public static final String CONDUCTOR='Conductor';
    @HttpPost
    global static DSALES_VentaSM.VentaSMResponse crearVenta() {
        DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c();
        DSALES_VentaSM.VentaSMResponse ventaSM= new DSALES_VentaSM.VentaSMResponse();
        DSALES_VentaSM.IdsARetornar idsLista = new DSALES_VentaSM.IdsARetornar();
        DSALES_VentaSM.DatosParaEmitir datosEmitir = new DSALES_VentaSM.DatosParaEmitir();
         List<DSALES_VentaSM.DatosParticipante> datos = new List<DSALES_VentaSM.DatosParticipante>();
        List<DSALES_VentaSM.ListaPartidasOportunidad> listaPartidas = new List<DSALES_VentaSM.ListaPartidasOportunidad>();
        Boolean exito=false;
        String mensajeError='';
        Integer codigoError;
        String idUniversal='';
        Quote cotizacion= new Quote ();
        Opportunity oppor= new  Opportunity ();
        DatosRetornoVenta datosx = new  DatosRetornoVenta();
        if(RestContext.request != null){
            String body = System.RestContext.request.requestBody.toString();
            if(String.isNotBlank(body)){
                try{
                    DSALES_VentaSM.VentaSMRequest venta = (DSALES_VentaSM.VentaSMRequest)JSON.deserialize(body, DSALES_VentaSM.VentaSMRequest.class);
                    System.debug('venta request: '+body);
                    String idUnico=venta.pagos.idUniversal;
                    List<DSALES_InformacionDePago__c> verificaIdUniversal =[SELECT Id,DSALES_IDUniversal1__c FROM DSALES_InformacionDePago__c WHERE DSALES_IDUniversal1__c =: idUnico WITH SECURITY_ENFORCED LIMIT 1];
                    if(verificaIdUniversal!=null && verificaIdUniversal.size()>0){
                        mensajeError='El id universal: '+idUnico+ ' ya existe' ;
                        System.debug('El id universal: ' +idUnico+ ' ya existe');
                        exito=false;
                        codigoError=401;
                    }
                    else{
                        idUniversal=venta.pagos.idUniversal;
                        cotizacion=[SELECT  Id,OpportunityId FROM Quote WHERE Id=:venta.idCotizacion WITH SECURITY_ENFORCED];
                        oppor=[SELECT Id,StageName,SyncedQuoteId,RecordTypeId,RecordType.DeveloperName FROM Opportunity WHERE Id=:cotizacion.OpportunityId WITH SECURITY_ENFORCED ];
                        datosx= seleccionaVenta(venta,oppor);
                        listaPartidas=DSALES_VentaSMRestAux.obtenerPartidas(oppor.Id);
                        exito=true;
                    }
                }catch(Exception.JSONException e){
                    exito = false;
                    mensajeError= DSALES_Utility.BAD_REQUEST_MSJ+' '+e.getLineNumber()+ ': '+e.getMessage()+' '+e.getCause();
                    codigoError=DSALES_Utility.BAD_REQUEST_CODE; 
                }
                catch(Exception e){
                    
                    System.debug('**ERROR VENTA**'+e.getLineNumber()+ ': '+e.getMessage());
                    exito = false;
                    listaPartidas=null;
                    mensajeError = DSALES_Utility.INTERNAL_ERROR_MSJ+' '+e.getLineNumber()+ ': '+e.getMessage();
                    codigoError=DSALES_Utility.INTERNAL_ERROR_CODE;
                    idUniversal='';
                    Quote cotSincro = [SELECT Id FROM Quote WHERE OpportunityId=:oppor.Id AND IsSyncing=true WITH SECURITY_ENFORCED ];
                    DSALES_EliminarRegistrosDeVenta.IdsBorrar datosE = new DSALES_EliminarRegistrosDeVenta.IdsBorrar();
                    datosE.idCotPrincipal=cotizacion.Id;
                    datosE.idCotSincro=cotSincro.Id;
                    DSALES_EliminarRegistrosDeVenta.eliminarRegistros(oppor,datosE);
                }
            }
        }
        System.debug('datos recived: '+datosEmitir);
       // ventaSM.datosParaEmitir=datosEmitir;
        ventaSM.datosParaEmitir=datosx.datosEmitir;
        ventaSM.exito=exito;
        ventaSM.codigoError=codigoError;
        ventaSM.mensajeError=mensajeError;
        ventaSM.idUniversal =idUniversal;
       // ventaSM.idClienteSalesforce=idCliente;
        ventaSM.idClienteSalesforce=datosx.idCliente;
        ventaSM.listaPartidasOportunidad=listaPartidas;
        return ventaSM;
    }
    private static Boolean sincronizarOportunidad(String quoteId, String accountId){
        Quote cotizacion = [SELECT Id,AccountId,OpportunityId,Opportunity.AccountId FROM Quote WHERE Id= :quoteId WITH SECURITY_ENFORCED]; 
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = accountId;
        oportunidad.Id = cotizacion.OpportunityId;
        if(Opportunity.SObjectType.getDescribe().isUpdateable()) {
            update oportunidad;   
        }else{
            System.debug('Permisos insuficientes para actualizar');   
        }
        return true; 
    }

    public static List<WrapperDatosProductos> obtenerProductosEnPartidasOportunidad(Id opportunityId) {
        List<WrapperDatosProductos> listaWrapperProducto = new List<WrapperDatosProductos>();
        List<OpportunityLineItem> oliLista = [SELECT Id, Product2Id FROM OpportunityLineItem WHERE OpportunityId = :opportunityId WITH SECURITY_ENFORCED];
        List<Id> listaIdsProducto = new List<Id>();
        for(OpportunityLineItem oli : oliLista) {
            listaIdsProducto.add(oli.Product2Id);
        }
        Map<Id, String> mapaNombresProductos = new Map<Id, String>();
        Map<Id, String> mapaSkuProductos = new Map<Id, String>();
        if(listaIdsProducto.size() > 0) {
            List<Product2> listaProductos = [SELECT Id, Name,StockKeepingUnit FROM Product2 WHERE Id IN :listaIdsProducto WITH SECURITY_ENFORCED];
            for(Product2 producto : listaProductos) {
                mapaNombresProductos.put(producto.Id, producto.Name);
                mapaSkuProductos.put(producto.Id,producto.StockKeepingUnit);
            }
        }
        for(OpportunityLineItem oli : oliLista) {
            WrapperDatosProductos productoWrapper = new WrapperDatosProductos();
            productoWrapper.idPartidaDeOportunidad = oli.Id;
            productoWrapper.nombreProducto = mapaNombresProductos.get(oli.Product2Id);
            productoWrapper.sku=mapaSkuProductos.get(oli.Product2Id);
            listaWrapperProducto.add(productoWrapper);
        }
        
        return listaWrapperProducto;
    }

    public static String crearCliente(List<DSALES_VentaSM.DatosParticipante> participantes, String recortypeName){
        DSALES_VentaSM.DatosParticipante participante = new DSALES_VentaSM.DatosParticipante();
        DSALES_AccountWrapper.AccountRequest cliente= new DSALES_AccountWrapper.AccountRequest();
        for(DSALES_VentaSM.DatosParticipante item: participantes){
            if((item.figura==CONDUCTOR && recortypeName=='Seguro_de_Moto') || (item.figura==DSALES_Utility.FIGURA_CONTRATANTE && recortypeName=='dsalesSeguroCelulares')){
                participante.numeroCliente=item.numeroCliente;
                participante.nombre = item.nombre;
                participante.apellidoPaterno = item.apellidoPaterno;
                participante.apellidoMaterno = item.apellidoMaterno;
                participante.telefono = item.telefono;
                participante.correoElectronico = item.correoElectronico;
                participante.genero = item.genero;
                participante.fechaNacimiento = item.fechaNacimiento;
                participante.calle = item.calle;
                participante.codigoCiudad =  item.codigoCiudad;
                participante.codigoPostal = item.codigoPostal;
                participante.numeroInterior=item.numeroInterior;
                participante.numeroExterior=item.numeroExterior;
                participante.codigoEstado=item.codigoEstado; //clave de estado en SM
                participante.codigoColonia=item.codigoColonia; //clave colonia SM
                participante.rfc=item.rfc;
                participante.codigoMunicipio=item.codigoMunicipio;
            }
        } 
        cliente.numeroCliente=participante.numeroCliente;
        cliente.nombre = participante.nombre;
        cliente.apellidoPaterno=participante.apellidoPaterno;
        cliente.apellidoMaterno=participante.apellidoMaterno;
        cliente.telefono=participante.telefono;
        cliente.correoElectronico =participante.correoElectronico;
        cliente.genero=participante.genero;
        system.debug('genero ');
        cliente.fechaNacimiento=participante.fechaNacimiento;
        cliente.calle=participante.calle;
        cliente.nombreCiudad=participante.codigoCiudad;
        cliente.codigoPostal=String.valueOf(participante.codigoPostal);
        cliente.numeroInterior=participante.numeroInterior;
        cliente.numeroExterior =participante.numeroExterior;
        cliente.codigoEstado=participante.codigoEstado; //clave de estado en SM
        cliente.codigoColonia=participante.codigoColonia; //clave colonia SM
        cliente.codigoMunicipio=participante.codigoMunicipio; //clave municipio SM
        cliente.rfc=participante.rfc;
        System.debug('participante cliente: '+cliente);
        DSALES_AccountWrapper.AccountResponse response= DSALES_AccountWrapperRequest.upsertAccount(cliente);
        return response.idCuenta;
    }
    public static DSALES_VentaSM.DatosParaEmitir datosParaEmitir(DSALES_VentaSM.VentaSMRequest venta,String idPoliza){ 
        DSALES_VentaSM.DatosParaEmitir response = new DSALES_VentaSM.DatosParaEmitir();
        DSALES_VentaSM.DatosSeguro datosSeguro= new DSALES_VentaSM.DatosSeguro();
        //DSALES_VentaSM.DatosVehiculo vehiculo = new DSALES_VentaSM.DatosVehiculo();
        //DSALES_VentaSM.DatosCelular celular = new DSALES_VentaSM.DatosCelular();
        List<DSALES_VentaSM.DatosParticipante> datos = new List<DSALES_VentaSM.DatosParticipante>();
        DSALES_VentaSM.DatosParticipante contratante = new DSALES_VentaSM.DatosParticipante();
        DSALES_VentaSM.DatosParaEmitir pruenas = new DSALES_VentaSM.DatosParaEmitir();
        DSALES_VentaSM.DatosConductor datosConductor = new DSALES_VentaSM.DatosConductor();
        DSALES_VentaSM.DatosContratante datosContratante = new DSALES_VentaSM.DatosContratante();
        ValoresParaAsignar valores = new ValoresParaAsignar();
        if(venta.activo.emitirPoliza==true){
            Insurancepolicy poliza =[SELECT Id,dsalesIMEI__c,DSALES_Modelo__c,RecordType.DeveloperName, dsalesEstatusPoliza__c,DSALES_Uso__c,PlanType,DSALES_Tipovehiculo__c,DSALES_Servicio__c,DSALES_Placas__c,DSALES_Numeroserie__c,SourceQuoteId,DSALES_Aseguradora__c,DSALES_Cobertura__c,dsalesFechaDeEmision__c,EffectiveDate,DSALES_Negocio__c,DSALES_Opcionpago__c,dsalesTipoServicio__c,dsalesTipoUso__c FROM Insurancepolicy WHERE Id=:idPoliza WITH SECURITY_ENFORCED];
            Quote cotizacion =[SELECT Id,dsalesIdDeVehiculo__c,dsalesNumeroSucursal__c,	dsalesCodigoDePromocion__c,DSALES_IDdelasociado__c,DSALES_RFC__c,dsalesFechaDeComienzoDePoliza__c,dsalesValorFactura__c FROM Quote WHERE Id=:poliza.SourceQuoteId WITH SECURITY_ENFORCED];
            QuoteLineItem seguro =[SELECT Id,dsalesQuoteId__c,UnitPrice,	DSALES_TrackingID__c,dsalesOpcionPago__c FROM QuoteLineItem WHERE QuoteId=:cotizacion.Id AND DSALES_Tipodeproducto__c=:'Seguro' WITH SECURITY_ENFORCED LIMIT 1];
            poliza.dsalesEstatusPoliza__c='En tramite';
            if(Insurancepolicy.SObjectType.getDescribe().isUpdateable()) {
                update poliza;  
            }else{
                System.debug('Permisos insuficientes para actualizar');   
            }
            
            FiguraAEnviar figuras=asignarParticipante(venta.datosParticipantes,poliza,venta.envioContratante);
            datosConductor=figuras.datosConductor;
            datosContratante=figuras.datosContratante;
            System.debug('datosContratante_______________________'+datosContratante);
            System.debug('datosConductor_________________________'+datosConductor);
            datosContratante=validarContratante(venta.envioContratante,datosContratante);
            datosSeguro.quote_id=seguro.dsalesQuoteId__c;
            datosSeguro.fechaEmision=poliza.dsalesFechaDeEmision__c;
            datosSeguro.aseguradora=poliza.DSALES_Aseguradora__c;
            datosSeguro.negocio=poliza.DSALES_Negocio__c;
            datosSeguro.opcionPago=seguro.dsalesOpcionPago__c;
            datosSeguro.paquete=poliza.DSALES_Cobertura__c;
            valores.poliza=poliza;
            valores.cotizacion=cotizacion;
            valores.seguro=seguro;
            response=asignarDatos(valores,venta,datosConductor);
            response.datosContratante=datosContratante; 
            response.datosSeguro=datosSeguro;       
        }
        System.debug('response: '+response);
        return response;
    }
    public static FiguraAEnviar asignarParticipante(List<DSALES_VentaSM.DatosParticipante> datosParticipantes,Insurancepolicy poliza, Boolean envioContratante){
        DSALES_VentaSM.DatosConductor datosConductor = new DSALES_VentaSM.DatosConductor ();
        DSALES_VentaSM.DatosContratante datosContratante = new DSALES_VentaSM.DatosContratante();
        FiguraAEnviar figuras= new FiguraAEnviar();
        for(DSALES_VentaSM.DatosParticipante p:datosParticipantes){
            if(p.figura==DSALES_Utility.FIGURA_CONDUCTOR ){
                datosConductor.nombre=p.nombre;
                datosConductor.apellidoPaterno=p.apellidoPaterno;
                datosConductor.apellidoMaterno=p.apellidoMaterno;
                datosConductor.telefono=p.telefono;
                datosConductor.correoElectronico=p.correoElectronico;
                datosConductor.genero=p.genero;
                datosConductor.fechaNacimiento=p.fechaNacimiento;
                datosConductor.rfc=p.rfc;
                datosConductor.codigoPostal=p.codigoPostal;
                datosConductor.calle=p.calle;
                datosConductor.codigoEstado=p.codigoEstado;
                datosConductor.codigoCiudad=p.codigoCiudad;
                datosConductor.codigoColonia=p.codigoColonia;
                datosConductor.numeroInterior=p.numeroInterior;
                datosConductor.numeroExterior=p.numeroExterior;
                datosConductor.codigoMunicipio=p.codigoMunicipio;
                figuras.datosConductor=datosConductor;
            }
            if(envioContratante==true && p.figura==DSALES_Utility.FIGURA_CONTRATANTE ){
                if(poliza.RecordType.DeveloperName=='dsalesSeguroCelulares'){
                    datosContratante.nombre=p.nombre;
                    datosContratante.apellidoPaterno=p.apellidoPaterno;
                    datosContratante.apellidoMaterno=p.apellidoMaterno;
                    datosContratante.regimenFiscal=p.regimenFiscal;
                    datosContratante.nacionalidad=p.nacionalidad;
                    datosContratante.codigoMunicipio=p.codigoMunicipio;
                }
                datosContratante.telefono=p.telefono;
                datosContratante.correoElectronico=p.correoElectronico;
                datosContratante.genero=p.genero;
                datosContratante.fechaNacimiento=p.fechaNacimiento;
                datosContratante.rfc=p.rfc;
                datosContratante.codigoPostal=p.codigoPostal;
                datosContratante.calle=p.calle;
                datosContratante.codigoEstado=p.codigoEstado;
                datosContratante.codigoCiudad=p.codigoCiudad;
                datosContratante.codigoColonia=p.codigoColonia;
                datosContratante.numeroInterior=p.numeroInterior;
                datosContratante.numeroExterior=p.numeroExterior;
                figuras.datosContratante=datosContratante;
            }
        }
        return figuras;

    }
    public static DSALES_VentaSM.DatosParaEmitir asignarDatos(ValoresParaAsignar valores,DSALES_VentaSM.VentaSMRequest venta,DSALES_VentaSM.DatosConductor datosConductor ){
        DSALES_VentaSM.DatosSeguro datosSeguro = new DSALES_VentaSM.DatosSeguro();
        DSALES_VentaSM.DatosVehiculo vehiculo = new DSALES_VentaSM.DatosVehiculo();
        DSALES_VentaSM.DatosCelular celular = new  DSALES_VentaSM.DatosCelular ();
        DSALES_VentaSM.DatosParaEmitir response = new DSALES_VentaSM.DatosParaEmitir();
        if(valores.poliza.RecordType.DeveloperName=='dsalesSeguroMotos'){
            datosSeguro.valorfactura=String.valueOf(valores.cotizacion.dsalesValorFactura__c);
            datosSeguro.trackingId=valores.seguro.DSALES_TrackingID__c;
            datosSeguro.codigoPromocion=valores.cotizacion.dsalesCodigoDePromocion__c;
            datosSeguro.fechaInicio=valores.cotizacion.dsalesFechaDeComienzoDePoliza__c;
            datosSeguro.idAsociado=valores.cotizacion.DSALES_IDdelasociado__c;
            datosSeguro.planPago='';
            datosSeguro.tarjetaPago='';
            datosSeguro.sumaAsegurada=0;
            vehiculo.idVehiculo=valores.cotizacion.dsalesIdDeVehiculo__c;
            vehiculo.modelo=valores.poliza.DSALES_Modelo__c;
            vehiculo.numeroSerie=valores.poliza.DSALES_Numeroserie__c;
            vehiculo.placas=valores.poliza.DSALES_Placas__c;
            vehiculo.sevicio=valores.poliza.dsalesTipoServicio__c;
            vehiculo.tipo=valores.poliza.DSALES_Tipovehiculo__c;
            vehiculo.uso=valores.poliza.dsalesTipoUso__c;
            response.datosVehiculo=vehiculo;
            response.beneficiarioPreferente=String.valueOf(venta.beneficiarioPreferente);
            response.contratante=venta.contratante;
            response.datosConductor=datosConductor;
        }
        else if(valores.poliza.RecordType.DeveloperName=='dsalesSeguroCelulares'){
            datosSeguro.montoSeguro=valores.seguro.UnitPrice;
            response.sucursal=valores.cotizacion.dsalesNumeroSucursal__c;
            celular.imei=valores.poliza.dsalesIMEI__c;
            celular.marcacelular=venta.activo.marca;
            celular.modeloCelular=venta.activo.modelo;
            //celular.numeroCredito=venta.activo.
            celular.numeroSerie=venta.activo.numeroSerie;
            celular.plazoCredito=venta.pagos.plazos;
            response.datosCelular=celular;
        }
        return response;

    }
    public static DSALES_VentaSM.DatosContratante validarContratante(Boolean envioContratante, DSALES_VentaSM.DatosContratante participante){
        DSALES_VentaSM.DatosContratante contratante = new DSALES_VentaSM.DatosContratante();
        if(envioContratante==true){
           contratante=participante;
        }else{
            Account item =[SELECT Id,CP_WalletCustomerNumber__c,dsalesRfc__c,FirstName,LastName,Suffix,PersonMobilePhone,PersonEmail,CP_Gender__pc,PersonBirthdate,BillingStreet,BillingCity,BillingState,BillingPostalCode,dsalesNumeroInterior__c,
            dsalesNumeroExterior__c,CP_BillingStateCode__c,dsalesCodigoColonia__c,dsalesSegundoCorreo__c,dsalesNacionalidadSociedad__c,dsalesFechaConstitucion__c,dsalesGiroComercial__c,dsalesTipoPersona__c,dsalesNombreApoderadoLegal__c,dsalesActividad__c 
            FROM Account WHERE FirstName=:NOMBRE_CONTRATANTE WITH SECURITY_ENFORCED LIMIT 1];
            contratante.rfc=item.dsalesRfc__c;
            //contratante.nombre = item.FirstName;
            //contratante.apellidoPaterno = item.LastName;
            //contratante.apellidoMaterno = item.Suffix;
            contratante.telefono = item.PersonMobilePhone;
            contratante.correoElectronico = item.PersonEmail;
            contratante.genero = item.CP_Gender__pc;
            contratante.fechaNacimiento = item.PersonBirthdate;
            contratante.calle = item.BillingStreet;
            contratante.codigoCiudad =  item.BillingCity;
            contratante.codigoPostal = Integer.valueOf(item.BillingPostalCode);
            contratante.numeroInterior=String.valueOf(item.dsalesNumeroInterior__c);
            contratante.numeroExterior=String.valueOf(item.dsalesNumeroExterior__c);
            contratante.codigoEstado=item.BillingState;
            contratante.codigoColonia=String.valueOf(item.dsalesCodigoColonia__c); 
            contratante.segundoCorreoContratante=item.dsalesSegundoCorreo__c;
            contratante.nacionalidadSociedad=item.dsalesNacionalidadSociedad__c;
            contratante.fechaConstitucion=item.dsalesFechaConstitucion__c;
            contratante.giroComercial=item.dsalesGiroComercial__c;
            contratante.tipoPersona=item.dsalesTipoPersona__c;
            contratante.nombreApoderadoLegal=item.dsalesNombreApoderadoLegal__c;
            contratante.contratante=item.FirstName +''+ item.LastName + ''+ item.Suffix;
            contratante.actividad=item.dsalesActividad__c;

        }
        return contratante;
    }
    public class WrapperDatosProductos {
        public Id idPartidaDeOportunidad { get; set; }
        public String nombreProducto { get; set; }
        public String sku {get;set;}
    }
    public class DatosPrepoliza{
        public String idPago{get;set;}
        public Boolean enviaContratante{get;set;}
        public Boolean beneficiarioPreferente {get;set;}
        public Integer plazo{get;set;}
    } 
    public class DatosParticipantes{
        DSALES_VentaSM.DatosParticipante conductor{get;set;}
        DSALES_VentaSM.DatosParticipante contratante{get;set;}
    }
    private static  DatosRetornoVenta ventaMotos(DSALES_VentaSM.VentaSMRequest venta, Opportunity oppor){
        DSALES_VentaSM.DatosParaEmitir datosEmitir = new DSALES_VentaSM.DatosParaEmitir();
        DSALES_VentaSM.DatosParaEmitir recived = new DSALES_VentaSM.DatosParaEmitir();
        DSALES_VentaSM.DatosSeguro datosSeguro= new DSALES_VentaSM.DatosSeguro();
        DSALES_VentaSM.DatosVehiculo vehiculo = new DSALES_VentaSM.DatosVehiculo();
        DatosRetornoVenta datosx = new  DatosRetornoVenta();
        String idCliente=crearCliente(venta.datosParticipantes,oppor.RecordType.DeveloperName);
        sincronizarOportunidad(venta.idCotizacion, idCliente);
        String idUniversal=venta.pagos.idUniversal;
        venta.pagos.idOportunidad=oppor.Id;
        List<String> partidasSeleccionadas= venta.idPartidaPresupuesto;
        String pagoId= DSALES_PaymentInfoWrapperRequest.insertarPago(venta.pagos,venta.contratante);
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Factura__c,DSALES_IDUniversal1__c,DSALES_Oportunidad__c,DSALES_Plazodecomprademoto__c,DSALES_Poliza__c,DSALES_Seguro__c,DSALES_SKU__c  
                                FROM DSALES_InformacionDePago__c 
                                WHERE Id=:pagoId WITH SECURITY_ENFORCED];
        String idPago=pago.Id;
        DSALES_VentaSMRestAux.cotizacionesNuevas(pago, partidasSeleccionadas,venta.pagos.precioRedondeado);
        DatosPrepoliza datosPrepoliza= new DatosPrepoliza();
        datosPrepoliza.enviaContratante=venta.envioContratante;
        datosPrepoliza.beneficiarioPreferente=venta.beneficiarioPreferente;
        String polizaId=DSALES_VentaSMRestAux.crearPrePoliza(pago,venta.datosParticipantes,datosPrepoliza);
        String idActivo= DSALES_VentaSMRestAux.crearActivo(pago,venta.activo,polizaId);
        if(String.isNotEmpty(idActivo)){
            recived=datosParaEmitir(venta, polizaId);
            datosSeguro=recived.datosSeguro;
            vehiculo=recived.datosVehiculo;
            datosEmitir=recived;
        }
        datosx.datosEmitir=datosEmitir;
        datosx.idCliente=idCliente;
        return datosx;

    }
    private static DatosRetornoVenta  seleccionaVenta(DSALES_VentaSM.VentaSMRequest venta, Opportunity oppor){
        DSALES_VentaSM.DatosParaEmitir datosEmitir = new DSALES_VentaSM.DatosParaEmitir();
        DatosRetornoVenta  retorno = new DatosRetornoVenta ();
        if(!String.isEmpty(venta.servico) && venta.servico=='CELULAR'){ //venta celulares
            DSALES_VentaSM.VentaSMResponse responseCelular= DSALES_VentaSCRest.crearVenta(venta);
            retorno.idCliente=responseCelular.idClienteSalesforce;
            retorno.datosEmitir=responseCelular.datosParaEmitir;
        }
        else{ //venta motos
            retorno= ventaMotos(venta,oppor);
        }
        return retorno;
    }

    public class DatosRetornoVenta{
        public DSALES_VentaSM.DatosParaEmitir datosEmitir {get;set;}
        public String idCliente{get;set;}
    }
    private class ValoresParaAsignar{
        Insurancepolicy poliza{get;set;}
        Quote cotizacion{get;set;}
        QuoteLineItem seguro{get;set;}
    }
    private class FiguraAEnviar{
        DSALES_VentaSM.DatosConductor datosConductor {get;set;}
        DSALES_VentaSM.DatosContratante datosContratante {get;set;}
    }
}