force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/DSALES_Garantia_Extendida.recordType-meta.xml
<RecordType>
    <fullName>DSALES_Garantia_Extendida</fullName>
    <active>true</active>
    <description>Tipo de registro para Garantía Extendida</description>
    <label>Garantia Extendida</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal1__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal1__c</fullName>
    <description>Campo para recibir el Id de la venta el cual estará compuesto</description>
    <label>ID Universal</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_Pagos_en_NPV.recordType-meta.xml
<RecordType>
    <fullName>DSALES_Pagos_en_NPV</fullName>
    <active>true</active>
    <description>Aquí se registrarán los pagos de la venta</description>
    <label>Pagos de venta de servicios</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/InsurancePolicy/fields/dsalesEstatusPoliza__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstatusPoliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepoliza</fullName>
                <default>true</default>
                <label>Prepóliza</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <label>En trámite</label>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>En solicitud</fullName>
                <isActive>false</isActive>
                <label>En solicitud</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.dsalesCliente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para informar que el plazo esta desactivado.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionarlo con el producto seguro</description>
    <label>Seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Seguro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plazos</relationshipLabel>
    <relationshipName>Plazos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/DSales_Garantia_Extendida.recordType-meta.xml
<RecordType>
    <fullName>DSales_Garantia_Extendida</fullName>
    <active>true</active>
    <description>Productos para Garantía Extendida</description>
    <label>Garantía Extendida</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/DSALES_ProdIntangible.recordType-meta.xml
<RecordType>
    <fullName>DSALES_ProdIntangible</fullName>
    <active>true</active>
    <description>Tipo de registro para los productos intangibles</description>
    <label>Producto Intangible</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/DSales_Seguro_de_Motos.recordType-meta.xml
<RecordType>
    <fullName>DSales_Seguro_de_Motos</fullName>
    <active>true</active>
    <description>Productos para Seguro de Motos</description>
    <label>Seguro de Motos</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Segurogratis__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Segurogratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si el producto lleva seguro gratis</description>
    <label>Seguro gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CancelacionControllerTest.cls
@isTest
public class DSALES_CancelacionControllerTest {
    @testSetup
    static void configuracionRegistro(){
        String tipoProducto = 'Producto';
        String message = '';
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Seguro_de_Moto').getRecordTypeId();
        String recordTypeIdGex = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('DSales_Garantia_Extendida').getRecordTypeId();
		String recordTypeIdPagoM = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();
        String recordTypeIdPagoG = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_Pagos_en_NPV').getRecordTypeId();
		String recordTypeIdAsset = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Garantia Extendida').getRecordTypeId();
        String recordTypeIdProd = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('DSales_Garantia_Extendida').getRecordTypeId();
        String recordTypeProdMotos = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('DSales_Seguro_de_Motos').getRecordTypeId();
        String recordTypeProdSeg = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('DSALES_ProdIntangible').getRecordTypeId();
        Account acc = new Account();
        acc.Name='Sayra Martinez Quiroz';
        acc.CP_WalletCustomerNumber__c=45654;
        acc.DSALES_ClienteCoppel__c='90001';
        insert acc;
        Contact con = new Contact(lastname= 'Test', AccountId= acc.Id, Email= 'johndoeus@salesforce.com');
        insert con;
        Product2 prodAmp = new Product2(Name ='AMP',dsalesVehiculo__c='23d23d23', StockKeepingUnit='123444',DSales_Tipo_de_Producto__c='Seguro',IsActive=true,RecordTypeId=recordTypeProdSeg);
		insert prodAmp;
        
        Product2 prodM = new Product2(Name ='Moto Vento',dsalesVehiculo__c='lasicndsldicsid',StockKeepingUnit='121213',DSales_Tipo_de_Producto__c='Producto',IsActive=true );
		insert prodM;
        
        Product2 pr= new Product2(Name='Lavadora',StockKeepingUnit='123451',DSales_Tipo_de_Producto__c='Producto',RecordTypeId=recordTypeIdProd,IsActive=true);
		insert pr;
       	Product2 gex= new Product2(Name='GEX',StockKeepingUnit='123406',DSales_Tipo_de_Producto__c='Servicio',RecordTypeId=recordTypeIdProd,IsActive=true);
		insert gex;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = prodM.Id;
        standardPrice.UnitPrice = 1200;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        PricebookEntry standardPriceMoto = new PricebookEntry();
        standardPriceMoto.Pricebook2Id = pricebookId;
        standardPriceMoto.Product2Id = prodAMP.Id;
        standardPriceMoto.UnitPrice = 1000;
        standardPriceMoto.IsActive = true;
        insert standardPriceMoto;
        
        PricebookEntry standardPricePG = new PricebookEntry();
        standardPricePG.Pricebook2Id = pricebookId;
        standardPricePG.Product2Id = pr.Id;
        standardPricePG.UnitPrice = 1200;
        standardPricePG.IsActive = true;
        insert standardPricePG;
        
        PricebookEntry standardPriceGex = new PricebookEntry();
        standardPriceGex.Pricebook2Id = pricebookId;
        standardPriceGex.Product2Id = gex.Id;
        standardPriceGex.UnitPrice = 1200;
        standardPriceGex.IsActive = true;
        insert standardPriceGex;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name='Standard Price Book';
        customPB.isActive=true;
        insert customPB;
        
        PricebookEntry customPriceM = new PricebookEntry();
        customPriceM.Pricebook2Id = customPB.Id;
        customPriceM.Product2Id = prodM.Id;
        customPriceM.UnitPrice = 1000;
        customPriceM.IsActive = true;
        insert customPriceM;
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.Product2Id = prodAmp.Id;
        customPrice.UnitPrice = 1000;
        customPrice.IsActive = true;
        insert customPrice;
        
        PricebookEntry customPricePG = new PricebookEntry();
        customPricePG.Pricebook2Id = customPB.Id;
        customPricePG.Product2Id = pr.Id;
        customPricePG.UnitPrice = 1000;
        customPricePG.IsActive = true;
        insert customPricePG;
        
        PricebookEntry customPriceGex = new PricebookEntry();
        customPriceGex.Pricebook2Id = customPB.Id;
        customPriceGex.Product2Id = gex.Id;
        customPriceGex.UnitPrice = 1000;
        customPriceGex.IsActive = true;
        insert customPriceGex;
        
        Opportunity opp = new Opportunity(Name='Venta moto', AccountId=acc.Id, CloseDate=Date.Today(), StageName='Nuevo', Pricebook2Id=customPB.Id,RecordTypeId=recordTypeId);
        insert opp;
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  '1';
        insert t;
        DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c(
                                      	DSALES_IDUniversal1__c='0000000000000000000001',
              							DSALES_Cliente__c=acc.Id,
              							DSALES_Oportunidad__c=opp.Id,
              							DSALES_Seguro__c=true,
            							DSALES_Motoentregada__c=true,
            							DSALES_Motoexterna__c=false,
              							RecordTypeId=recordTypeIdPagoM
                                      
                                      
          );
        insert pago;
       
        Quote cotizacion = new Quote(OpportunityId=opp.Id,Name='test',DSales_Tienda__c=t.Id);
        insert cotizacion;
     
		Plazo__c plazoAMP12 = new Plazo__c(Name='12',Dsales_Plazo__c='12',dsalesSeguro__c=prodAmp.Id,dsales_Activo__c=true);
        insert plazoAMP12;
        
        QuoteLineItem moto = new QuoteLineItem();
        moto.QuoteId = cotizacion.Id;
        moto.PricebookEntryId = customPriceM.Id;
        moto.Product2Id = prodM.Id;
        moto.Quantity = 1.0;
        moto.UnitPrice = customPriceM.UnitPrice;
        moto.DSALES_Segurogratis__c=false;
        insert moto;
        opp.SyncedQuoteId  = cotizacion.Id;     
       	update opp;
      	InsurancePolicy poliza = new InsurancePolicy(
				SourceOpportunityId=opp.Id,
            	dsalesEstatusPoliza__c='Prepoliza',
        		NameInsuredId=acc.Id,
                DSALES_Tipodepersona__c='Física',
            	DSALES_CorreoElectronico__c='saymartinez@deloittemx.com',
            	Name='1234567890',
            	SourceQuoteId=cotizacion.Id
                
        );
        insert poliza;
        pago.DSALES_Poliza__c=poliza.Id;
        update pago;
        InsurancePolicyAsset activo = new InsurancePolicyAsset (
            					
                            	InsurancePolicyId=poliza.Id,
            					AssetName='MOTO VENTO',
            					DSALES_InformacionPago__c=pago.Id,
            					dsalesCliente__c=acc.Id,
            					dsalesEstatus__c='Activo',
            					DSALES_Motoexterna__c=false
        );
        insert activo;
        poliza.dsalesActivoPolizaSeguro__c=activo.Id;
        update poliza;
        
    }
    @isTest
    public static void cancelarPolizaTest(){
        Opportunity op =[SELECT Id FROM Opportunity WHERE Name='Venta moto' LIMIT 1 ];
        List<OpportunityLineItem> partidas =[SELECT Id,Name,Product2.Id FROM OpportunityLineItem WHERE OpportunityId=:op.Id];
        InsurancePolicy poliza =[SELECT Id,dsalesActivoPolizaSeguro__c FROM InsurancePolicy LIMIT 1];
        System.debug(partidas.size()+'Name: '+ partidas);
        Product2 prod =[SELECT Id,DSales_Tipo_de_Producto__c FROM Product2 WHERE Id =:partidas[0].Product2.Id];
        System.debug('prod: '+ prod);
        DSALES_CancelacionController.escenarioPolizaActRegistros(partidas,poliza);
        //DSALES_CancelacionController.obtenerActivo(partidas);
    }
     @isTest
    public static void obtenerActivo(){
        Opportunity op =[SELECT Id FROM Opportunity WHERE Name='Venta moto' LIMIT 1 ];
        List<OpportunityLineItem> partidas =[SELECT Id,Name,Product2.Id FROM OpportunityLineItem WHERE OpportunityId=:op.Id];
        InsurancePolicy poliza =[SELECT Id,dsalesActivoPolizaSeguro__c FROM InsurancePolicy LIMIT 1];
        System.debug(partidas.size()+'Name: '+ partidas);
        Product2 prod =[SELECT Id,DSales_Tipo_de_Producto__c FROM Product2 WHERE Id =:partidas[0].Product2.Id];
        System.debug('prod: '+ prod);
        DSALES_CancelacionController.obtenerActivo(partidas);
        DSALES_CancelacionController.obtenerIdPago(partidas);
    }

}