force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <formula>PersonContact.Birthdate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/DSales_Asignacion_de_Productos__c.object-meta.xml
<CustomObject>
    <label>Asignación de Productos</label>
    <nameField>
        <label>Nombre de Asignación de Productos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSales_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignaciones de Productos</relationshipLabel>
    <relationshipName>Asignaciones_de_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSales_Servicio_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSales_Servicio_Seguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicio/Seguro</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignaciones de Productos (Servicio/Seguro)</relationshipLabel>
    <relationshipName>Asignaciones_de_Productos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/dsalesAsignacionDeTienda__c.object-meta.xml
<CustomObject>
    <label>Asignación de Tienda</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Asignación de Tienda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignación de Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/fields/dsalesTienda__c.field-meta.xml
<CustomField>
    <fullName>dsalesTienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Asignación de Tiendas</relationshipLabel>
    <relationshipName>Asignacion_de_Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Seguro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignación de Tiendas</relationshipLabel>
    <relationshipName>Asignacion_de_Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/dsalesIdentificadorCoppel__c.field-meta.xml
<CustomField>
    <fullName>dsalesIdentificadorCoppel__c</fullName>
    <description>Número de identificador para Coppel</description>
    <label>Identificador Coppel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de celulares del grupo Coppel.</description>
    <label>Seguro de celulares</label>
</RecordType>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para informar que el plazo esta desactivado.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionarlo con el producto seguro</description>
    <label>Seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Seguro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plazos</relationshipLabel>
    <relationshipName>Plazos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <inlineHelpText>A=Anual
C=Contado
M=Mensual</inlineHelpText>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Contado</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <description>tipo de registro para generación de seguros para celulares</description>
    <label>Seguro de Celulares</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSALES_Plazoacotizar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazoacotizar__c</fullName>
    <description>Campo para recibir el plazo máximo a cotizar con proveedor.</description>
    <label>Plazo a cotizar</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesValorFactura__c.field-meta.xml
<CustomField>
    <fullName>dsalesValorFactura__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar si estamos recibiendo el valor de la factura</description>
    <label>Valor de la factura</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <description>Campo para recibir las características del seguro</description>
    <label>Descripción</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Impuestos__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Impuestos__c</fullName>
    <label>Impuestos</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_ListaArticulo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ListaArticulo__c</fullName>
    <description>Ayuda a definir el artículo seleccionado y a separarlo con su listado correspondiente</description>
    <inlineHelpText>Un artículo como Refrigerador o Cafetera, caería en producto</inlineHelpText>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>GEX</fullName>
                <isActive>false</isActive>
                <label>GEX</label>
            </value>
            <value>
                <fullName>Producto (Seguro de Motos)</fullName>
                <isActive>false</isActive>
                <label>Producto (Seguro de Motos)</label>
            </value>
            <value>
                <fullName>Seguro Motos</fullName>
                <isActive>false</isActive>
                <label>Seguro Motos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Segurogratis__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Segurogratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si el producto lleva seguro gratis</description>
    <label>Seguro gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <description>Campo para identificar si la partida es de contado o crédito.</description>
    <label>Opción de pago</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo para recibir el id de cotización de Interproteccion por cada uno de los paquetes solicitados.</description>
    <label>Quote id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_QuoteScWrapperRequest_Test.cls
@isTest 
public class DSALES_QuoteScWrapperRequest_Test {
    
    @testSetup 
    static void setUp(){
        String tipoProducto = 'Producto';
        String message = '';
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('dsalesSeguroCelulares').getRecordTypeId();
        String recordTypeAccountId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        
        Product2 prodCell = new Product2();
        prodCell.Name ='Iphone';
        prodCell.StockKeepingUnit='123122';
        prodCell.DSales_Tipo_de_Producto__c='Producto';
        prodCell.DSales_Articulo__c='test2';
        prodCell.IsActive=true;
        insert prodCell;
        
        
        Product2 prodSeguro = new Product2();
        prodSeguro.Name ='Seguro Celular';
        prodSeguro.StockKeepingUnit='000089';
        prodSeguro.DSales_Tipo_de_Producto__c='Seguro';
        prodSeguro.DSales_Articulo__c='Test';
        prodSeguro.IsActive=true;
        prodSeguro.dsalesOpcionPago__c='M';
        insert prodSeguro;
        
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = prodSeguro.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        PricebookEntry standardPriceGEX = new PricebookEntry();
        standardPriceGEX.Pricebook2Id = pricebookId;
        standardPriceGEX.Product2Id = prodCell.Id;
        standardPriceGEX.UnitPrice = 1000;
        standardPriceGEX.IsActive = true;
        insert standardPriceGEX;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name='Standard Price Book';
        customPB.isActive=true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.Product2Id = prodSeguro.Id;
        customPrice.UnitPrice = 1200;
        customPrice.IsActive = true;
        insert customPrice;
        
        
        
        PricebookEntry customPriceMoto = new PricebookEntry();
        customPriceMoto.Pricebook2Id = customPB.Id;
        customPriceMoto.Product2Id = prodCell.Id;
        customPriceMoto.UnitPrice = 2000;
        customPriceMoto.IsActive = true;
        insert customPriceMoto;
        
        Account acc = new Account();
        acc.Name = 'test';
        acc.CP_WalletCustomerNumber__c=45654;
        acc.DSALES_ClienteCoppel__c='90001';
        insert acc;
        
        Account accCont = new Account();
        accCont.FirstName = 'Daniela1';
        accCont.LastName = 'Gallegos1';
        accCont.Suffix = 'Ho1';
        accCont.PersonEmail = 'danigallegos@deloittemx.com';
        accCont.Phone = '5563452135';
        accCont.PersonBirthdate = date.today();
        accCont.DSALES_ClienteCoppel__c=null;
        accCont.CP_WalletCustomerNumber__c=null;
        insert accCont;
        
        Account accContado = new Account();
        accContado.FirstName = 'Daniela';
        accContado.LastName = 'Gallegos';
        accContado.Suffix = 'Ho';
        accContado.PersonEmail = 'danigallegos@deloittemx.com';
        accContado.Phone = '5563452135';
        accContado.PersonBirthdate = date.today();
        accContado.DSALES_ClienteCoppel__c=null;
        accContado.CP_WalletCustomerNumber__c=null;
        insert accContado;
        
        Account accContado2 = new Account();
        accContado2.FirstName = 'Daniela';
        accContado2.LastName = 'Gallegos';
        accContado2.Suffix = 'Ho';
        accContado2.PersonEmail = 'danigegos@deloittemx.com';
        insert accContado2;
        
        Opportunity opp = new Opportunity();
        opp.Name='TestOpportunity';
        opp.AccountId=acc.Id;
        opp.CloseDate=Date.Today();
        opp.StageName='Nuevo';
        opp.Pricebook2Id=customPB.Id;
        opp.RecordTypeId=recordTypeId;
        insert opp;
        
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  '1';
        insert t;
        
        Plazo__c plazo1 = new Plazo__c();
        plazo1.Name='12';
        plazo1.dsalesSeguro__c=prodSeguro.Id;
        plazo1.Dsales_Plazo__c='12';
        plazo1.DSALES_Activo__c=true;
        insert plazo1;
        
        Plazo__c plazo = new Plazo__c();
        plazo.Name='18';
        plazo.dsalesSeguro__c=prodSeguro.Id;
        plazo.Dsales_Plazo__c='18';
        plazo.DSALES_Activo__c=true;
        insert plazo;
        
        Quote cotizacion = new Quote();
        cotizacion.Name='test';
        cotizacion.OpportunityId = opp.Id;
        cotizacion.DSales_Tienda__c=t.Id;
        cotizacion.dsalesValorFactura__c=true;
        cotizacion.Pricebook2Id =pricebookId;
        cotizacion.DSALES_RFC__c='testRFC';
        cotizacion.DSALES_Plazoacotizar__c= 12;
        cotizacion.DSales_Vendedor__c='Luis Perez Sanchez';
        cotizacion.dsalesIdentificadorCoppel__c = 011;
        insert cotizacion;
        
        QuoteLineItem presupuesto = new QuoteLineItem();
        presupuesto.QuoteId = cotizacion.Id;
        presupuesto.PricebookEntryId = standardPrice.Id;
        presupuesto.Product2Id = prodSeguro.Id;
        presupuesto.Quantity = 1;
        presupuesto.UnitPrice = standardPrice.UnitPrice;
        presupuesto.DSALES_ListaArticulo__c = 'Producto';
        presupuesto.DSALES_Plazo__c= plazo1.Id;
        presupuesto.dsalesOpcionPago__c='M';
        presupuesto.dsalesQuoteId__c= cotizacion.Id;
        presupuesto.DSALES_Segurogratis__c = false;
        presupuesto.DSALES_Descripcion__c = 'test Description';
        presupuesto.DSALES_Impuestos__c = 125.00;
        insert presupuesto;
        
        
        
        DSales_Asignacion_de_Productos__c asigProducto = new DSales_Asignacion_de_Productos__c();
        asigProducto.DSALES_Activo__c=true;
        asigProducto.DSales_Servicio_Seguro__c=prodSeguro.Id;
        asigProducto.DSales_Producto__c=ProdCell.Id;
        asigProducto.Name='Seguro Celular';
        insert asigProducto;
        
        dsalesAsignacionDeTienda__c asigTienda = new dsalesAsignacionDeTienda__c();
        asigTienda.dsalesActivo__c=true;
        asigTienda.Producto__c=prodSeguro.Id;
        asigTienda.dsalesTienda__c=t.Id;
        insert asigTienda;
        
    }
    @isTest 
    static void createQuoteTest(){
        String seguro ='Seguro';
        Product2 producto = [SELECT Id, Name, StockKeepingUnit,DSales_Tipo_de_Producto__c, DSALES_Seguro__c, DSales_Articulo__c FROM Product2 WHERE StockKeepingUnit='123122' LIMIT 1];
        Quote cotiza =[SELECT Id, Name FROM Quote WHERE Name='test'];        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String body = '{"idTienda":"1", "numeroCliente":"7934", "nombreVendedor":"Luis Perez Sanchez", "identificadorCoppel":"011", "nombre":"Ana", "apellidoPaterno":"Alivia",  "apellidoMaterno":"Test", "correoElectronico":"martin.perest@gmail.com", "telefonoCelular":"123456789", "fechaNacimiento":"1975-01-17", "rfc":"MIVE901010", "precioCelular":4000,"sku":"123122", "marcaCelular":"Apple", "modeloCelular":"Iphone", "colorCelular":"Blanco", "plazoCotizar":"18", "opcionPago":"Mensual","fechaDeVenta":"", "identificadorDelVendedor":"12", "numeroDeSucursal":"22"}';
        req.requestURI = '/apexrest/insertQuoteSC';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.response= res;
        DSALES_QuoteScWrapper.QuoteScRequest data =(DSALES_QuoteScWrapper.QuoteScRequest)JSON.deserialize(body, DSALES_QuoteScWrapper.QuoteScRequest.class);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(1));
        DSALES_QuoteScWrapper.QuoteScResponse response = DSALES_QuoteScWrapperRequest.createQuoteSc();
        QuoteLineItem item = DSALES_QuoteScWrapperRequestHelper.insertQuoteLineItem(cotiza, producto.StockKeepingUnit,data.precioCelular);
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200'); 
        
    }
    @isTest 
    static void nullNumeroClienteTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String body = '{"idTienda":"1", "numeroCliente":null, "nombreVendedor":"Luis Perez Sanchez", "identificadorCoppel":"011", "nombre":"Daniela", "apellidoPaterno":"Gallegos",  "apellidoMaterno":"Ho", "correoElectronico":"martin.perest@gmail.com", "telefonoCelular":"123456789", "fechaNacimiento":"1975-01-17", "rfc":"MIVE901010", "precioCelular":4000,"sku":"123122", "marcaCelular":"Apple", "modeloCelular":"Iphone", "colorCelular":"Blanco", "plazoCotizar":"18", "opcionPago":"Mensual","fechaDeVenta":"", "identificadorDelVendedor":"12", "numeroDeSucursal":"22"}';
        req.requestURI = '/apexrest/insertQuoteSC';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.response= res;
        DSALES_QuoteScWrapper.QuoteScRequest data =(DSALES_QuoteScWrapper.QuoteScRequest)JSON.deserialize(body, DSALES_QuoteScWrapper.QuoteScRequest.class);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(1));
        DSALES_QuoteScWrapper.QuoteScResponse response = DSALES_QuoteScWrapperRequest.createQuoteSc();
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200'); 
        
    }
    
    @isTest 
    static void quoteScTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String body = '{"idTienda":"1", "numeroCliente":null, "nombreVendedor":"Luis Perez Sanchez", "identificadorCoppel":"011", "nombre":"Daniela", "apellidoPaterno":"Gallegos",  "apellidoMaterno":"Ho", "correoElectronico":"danigegos@deloittemx.com", "telefonoCelular":"5563452135", "fechaNacimiento":"1975-01-17", "rfc":"MIVE901010", "precioCelular":4000,"sku":"123122", "marcaCelular":"Apple", "modeloCelular":"Iphone", "colorCelular":"Blanco", "plazoCotizar":"18", "opcionPago":"Mensual","fechaDeVenta":"", "identificadorDelVendedor":"12", "numeroDeSucursal":"22"}';
        req.requestURI = '/apexrest/insertQuoteSC';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.response= res;
        DSALES_QuoteScWrapper.QuoteScRequest data =(DSALES_QuoteScWrapper.QuoteScRequest)JSON.deserialize(body, DSALES_QuoteScWrapper.QuoteScRequest.class);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(1));
        DSALES_QuoteScWrapper.QuoteScResponse response = DSALES_QuoteScWrapperRequest.createQuoteSc();
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200'); 
        
    }
     @isTest
    static void quoteScTest1() {
        List<Account> resul = [Select Id, firstName, suffix, lastName, Fecha_de_Nacimiento__c, Phone, PersonEmail from Account WHERE firstName='Daniela1' AND suffix='Ho1' AND lastName='Gallegos1'];
        Product2 producto = [SELECT Id, Name, StockKeepingUnit,DSales_Tipo_de_Producto__c, DSALES_Seguro__c, DSales_Articulo__c FROM Product2 WHERE Name='Seguro Celular' LIMIT 1];
        Quote quote= [SELECT Id, Name FROM Quote LIMIT 1];
        String body = '{"idTienda":"1", "numeroCliente":null, "nombreVendedor":"Luis Perez Sanchez", "identificadorCoppel":"011", "nombre":"Daniela1", "apellidoPaterno":"Gallegos1",  "apellidoMaterno":"Ho1", "correoElectronico":"danigegos@deloittemx.com", "telefonoCelular":"5563452135", "fechaNacimiento":"1975-01-17", "rfc":"MIVE901010", "precioCelular":4000,"sku":"123122", "marcaCelular":"Apple", "modeloCelular":"Iphone", "colorCelular":"Blanco", "plazoCotizar":"18", "opcionPago":"Mensual","fechaDeVenta":"", "identificadorDelVendedor":"12", "numeroDeSucursal":"22"}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/apexrest/insertQuoteSC'; 
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.request = req;
        RestContext.response = res;
        DSALES_QuoteScWrapper.QuoteScRequest data =(DSALES_QuoteScWrapper.QuoteScRequest)JSON.deserialize(body, DSALES_QuoteScWrapper.QuoteScRequest.class);
        List<DSALES_QuoteScWrapper.InsurancePremium> priceSeg = new List<DSALES_QuoteScWrapper.InsurancePremium>();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(11));
        DSALES_QuoteScWrapper.QuoteScResponse response = DSALES_QuoteScWrapperRequest.createQuoteSC();
        List<DSALES_QuoteScWrapper.Plazo>  plz =DSALES_QuoteScWrapperRequestHelper.insertPlazos(producto.Name,quote, priceSeg,data.quoteId, data.opcionPago, data.plazoCotizar);
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200'); 
        
    }
    
    @isTest
    static void quoteScTest2() {
        List<Account> result = [Select Id,firstName,suffix,lastName from Account WHERE CP_WalletCustomerNumber__c =45654];
        String body = '{"idTienda":"1", "numeroCliente":45654, "nombreVendedor":"Luis Perez Sanchez", "identificadorCoppel":"011", "nombre":"Dani", "apellidoPaterno":"Min",  "apellidoMaterno":"Ho", "correoElectronico":"danigegos@deloittemx.com", "telefonoCelular":"5563452135", "fechaNacimiento":"1975-01-17", "rfc":"MIVE901010", "precioCelular":4000,"sku":"123122", "marcaCelular":"Apple", "modeloCelular":"Iphone", "colorCelular":"Blanco", "plazoCotizar":"18", "opcionPago":"Mensual","fechaDeVenta":"", "identificadorDelVendedor":"12", "numeroDeSucursal":"22"}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/apexrest/insertQuoteSC';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(3));
        DSALES_QuoteScWrapper.QuoteScResponse response = DSALES_QuoteScWrapperRequest.createQuoteSC();
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200'); 
        
    }
    
    @isTest 
    static void exceptionTest(){
        RestResponse res = new RestResponse();
        String requestBody = 'invalid body';
        RestRequest req = new RestRequest();
        req.requestURI = '/apexrest/insertQuoteSC';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(requestBody);
        RestContext.request = req;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseQuoteSc(9));
        DSALES_QuoteScWrapper.QuoteScResponse response= DSALES_QuoteScWrapperRequest.createQuoteSC();
        Test.stopTest();
        System.assertNotEquals(200, res.statusCode, 'La llamada no debe devolver un código 200');
    }
    
}