force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal__c</fullName>
    <formula>DSALES_Factura__c  &amp;  DSALES_Clave_Tienda__c  &amp;  TEXT (DAY(DSALES_Fecha__c)) &amp; TEXT (MONTH(DSALES_Fecha__c)) &amp; TEXT (YEAR(DSALES_Fecha__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Universal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_ReembolsoWrapperTest.cls
@isTest
global with sharing class DSALES_ReembolsoWrapperTest {
    @testSetup
    static void SetUp()
    {
        Opportunity opp = new Opportunity(Name='Danny',StageName='Closed',CloseDate=Date.today());
        insert opp;
        Account ac= new Account(Name='DannyTest',CP_WalletCustomerNumber__c=123456);  
        insert ac;
         DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c(DSALES_Oportunidad__c=opp.id,DSALES_Factura__c='1234',DSALES_Clave_Tienda__c='1234');
        insert pago;
        
    }
    
    @isTest static void createRecordTest()
        {
            DSALES_InformacionDePago__c pago= [SELECT DSALES_IDUniversal__c FROM DSALES_InformacionDePago__c WHERE DSALES_Factura__c='1234' LIMIT 1];
            RestRequest request = new RestRequest();
            RestResponse response= new RestResponse();
            request.requestURI='/apexrest/insertReembolso';
            request.httpMethod='POST';
            RestContext.request=request;
             String body = '{"pago_universal": "'+pago.DSALES_IDUniversal__c+'","comentarios": "El cliente decidió cancelar el producto","fecha": "2023-02-24",'+
  '"metodo_pago": "Efectivo","numero_referencia": "1123456621","cantidad": 15005}';
            request.requestBody=blob.valueOf(body);
            RestContext.response=response;
            DSALES_ReembolsoWrapper.ReembolsoRequest reembolso =  (DSALES_ReembolsoWrapper.ReembolsoRequest)JSON.deserialize (body,DSALES_ReembolsoWrapper.ReembolsoRequest.class);
            Test.startTest();
            DSALES_ReembolsoWrapperRequest.createReembolso();
            Test.stopTest();
            RestContext.request = request;
        RestContext.response= response;
            
        }
      
}