force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/DSALES_VentaSM.recordType-meta.xml
<RecordType>
    <fullName>DSALES_VentaSM</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones del producto SM.</description>
    <label>Venta de Seguro de Motos</label>
</RecordType>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CrearParticipanteTest.cls
@isTest
public class DSALES_CrearParticipanteTest {
    @testSetup
    public static void crearRegistros(){
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Seguro_de_Moto').getRecordTypeId();
		Account acc = new Account();
        acc.FirstName='Sayra';
        acc.LastName='Martinez';
        acc.Suffix='Quiroz';
        acc.CP_WalletCustomerNumber__c=45654;
        acc.DSALES_Clientecoppel__c='90001';
        acc.PersonEmail='saymartinez@deloittemx.com';
        insert acc;
        Account coppel = new Account();
        coppel.FirstName='COPPEL';
        coppel.LastName='SA';
        coppel.Suffix='DE CV';
        //coppel.CP_WalletCustomerNumber__c=45654;
        //coppel.DSALES_Clientecoppel__c='90001';
        //coppel.PersonEmail='saymartinez@deloittemx.com';
        insert coppel;
        Pricebook2 customPB = new Pricebook2();
        customPB.Name='Standard Price Book';
        customPB.isActive=true;
        insert customPB;
        Opportunity oportunidad = new Opportunity(Name='Testoportunidadortunity', AccountId=acc.Id, CloseDate=Date.Today(), StageName='Nuevo', Pricebook2Id=customPB.Id,RecordTypeId=recordTypeId);
        insert oportunidad;
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  '1';
        insert t;
        DSALES_InformaciondePago__c pago = new DSALES_InformaciondePago__c(DSALES_Oportunidad__c=oportunidad.id,DSALES_Cliente__c=acc.Id,DSALES_Seguro__c=true);
        insert pago;
        Quote cotizacion = new Quote(opportunityId=oportunidad.Id,Name='test',DSales_Tienda__c=t.Id);
        insert cotizacion;
        InsurancePolicy poliza = new Insurancepolicy();
        poliza.Name='0001';
        poliza.NameInsuredId=acc.Id;
        poliza.DSALES_CorreoElectronico__c='saymartinez@deloittemx.com';
        insert poliza;
        pago.DSALES_Poliza__c=poliza.Id;
        update pago;
    }
    @isTest
    public static void crearConductorTest(){
        Account cliente=[SELECT Id, Name FROM Account LIMIT 1];
        Insurancepolicy poliza=[SELECT Id FROM Insurancepolicy LIMIT 1];
        DSALES_CrearParticipantesPoliza.crearConductor(cliente.Id,poliza.Id);        
    }
    @isTest
    public static void buscarConductorTest(){
        DSALES_CrearParticipantesPoliza.DatosConductor cond= new DSALES_CrearParticipantesPoliza.DatosConductor();
        cond.nombre='Sayra';
        cond.apellidoMaterno='Quiroz';
        cond.apellidoPaterno='Martinez';
        cond.correo='saymartinez@deloittemx.com';
        DSALES_CrearParticipantesPoliza.busquedaCuentaConductor(cond, null);
    } 
    @isTest
    public static void crearParticipantesTest(){
        List<DSALES_VentaSM.DatosParticipante> listaParticipante = new List<DSALES_VentaSM.DatosParticipante>();
        DSALES_VentaSM.DatosParticipante part = new DSALES_VentaSM.DatosParticipante();
        part.figura='Conductor';
        part.nombre='Sayra';
        part.apellidoPaterno='Martinez';
        part.apellidoMaterno='Quiroz';
        part.relacionConParticipante='';
        part.porcentaje='0';
        part.telefono='4325808753';
        part.correoElectronico='saymartinez@deloittemx.com';
        part.genero='Femenino';
        part.fechaNacimiento=Date.today();
        part.rfc='123678';
        part.codigoPostal=22854;
        part.codigoEstado='12';
        part.codigoCiudad='12';
        part.codigoColonia='12';
        part.calle='calle';
        part.numeroExterior='12';
        part.numeroInterior='12';
        DSALES_VentaSM.DatosParticipante part2 = new DSALES_VentaSM.DatosParticipante();
        part2.figura='Beneficiario';
        part2.nombre='Carlos';
        part2.apellidoPaterno='Ramos';
        part2.apellidoMaterno='Cruz';
        part2.relacionConParticipante='Padre';
        part2.porcentaje='0';
        part2.telefono='4325808753';
        part2.correoElectronico='saymartinez@deloittemx.com';
        part2.genero='Masculino';
        part2.fechaNacimiento=Date.today();
        part2.rfc='123678';
        part2.codigoPostal=22854;
        part2.codigoEstado='12';
        part2.codigoCiudad='12';
        part2.codigoColonia='12';
        part2.calle='calle';
        part2.numeroExterior='12';
        part2.numeroInterior='12';
        listaParticipante.add(part);
        listaParticipante.add(part2);
        Insurancepolicy poliza=[SELECT Id FROM Insurancepolicy LIMIT 1];
		DSALES_CrearParticipantesPoliza.crearParticipantes(listaParticipante, poliza.Id, false);
    }
}