force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal1__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal1__c</fullName>
    <description>Campo para recibir el Id de la venta el cual estará compuesto</description>
    <label>ID Universal</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_IPAssetWrapperTest.cls
@isTest
public with sharing class DSALES_IPAssetWrapperTest {
    @testSetup
    static void setUp(){
        Account ac= new Account(Name='DannyTest',CP_WalletCustomerNumber__c=90229562);  
        insert ac;
        Opportunity op = new Opportunity(Name='Danny',CloseDate=Date.today(),StageName='Nuevo');
        insert op;
         InsurancePolicy ip = new InsurancePolicy(Name='Danny',NameInsuredId=ac.id,DSALES_CorreoElectronico__c='kvothe.sanmiguel@gmail.com');
        insert ip;
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  'CPPL-UGARTE';
        insert t;
        DSALES_InformaciondePago__c pago = new DSALES_InformaciondePago__c(DSALES_Oportunidad__c=op.id,DSALES_Cliente__c=ac.Id,DSALES_Poliza__c=ip.id,DSALES_Seguro__c=true,DSALES_IDUniversal1__c='123456');
        insert pago;
    }
    @isTest static void createRecordTest()
    {
        RestRequest request=new RestRequest();
        RestResponse response = new RestResponse();
        DSALES_InformaciondePago__c pago = [SELECT id,DSALES_Poliza__c,DSALES_IDUniversal1__c FROM  DSALES_InformaciondePago__c  LIMIT 1];
        Tienda__c tienda =[SELECT Id FROM Tienda__c LIMIT 1];
        String body='{"emitirPoliza":false,"idUniversal":"'+pago.DSALES_IDUniversal1__c+'","uso":"Personal","claveTienda":"1","servicio":"Particular","numeroSerie":"12345678","numeroMotor":"8","modelo":"2022","placas":"AS-4567","claveVehicular":"098765432","valorFactura":8000,"bajoDemanda":false,"descripcion":"moto Vitalia azul","marca":"VITALIA","nombreActivo":"MOTO VITALIA"}}';
        request.requestURI='/apexrest/insertIPAsset'; 
        request.httpMethod='POST';
        RestContext.request=request;
        request.requestBody=Blob.valueOf(body);
        RestContext.response=response;
        DSALES_IPAssetWrapper.IPAssetRequest policyAsset =  (DSALES_IPAssetWrapper.IPAssetRequest)JSON.deserialize (body,DSALES_IPAssetWrapper.IPAssetRequest.class);
        //policyAsset.payment_info=pago.id;
        Test.startTest();
        DSALES_IPAssetWrapperRequest.createIPAsset();
        //Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponsePolizaTest());
        Test.stopTest();
        RestContext.request = request;
        RestContext.response= response;
        System.assertNotEquals(200, response.statusCode, 'La llamada no debe devolver un código 200');
    }
}