force-app/main/default/objects/Account/fields/CP_WalletCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CP_WalletCustomerNumber__c</fullName>
    <description>Número de cliente crédito (Sistema Cartera).</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de cliente crédito (Sistema Cartera).</inlineHelpText>
    <label>#Cliente Crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DSALES_Tiend__c.field-meta.xml
<CustomField>
    <fullName>dsalesTienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/dsalesIdentificadorCoppel__c.field-meta.xml
<CustomField>
    <fullName>dsalesIdentificadorCoppel__c</fullName>
    <description>Número de identificador para Coppel</description>
    <label>Identificador Coppel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/dsalesNumeroSucursal__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroSucursal__c</fullName>
    <description>Número de Sucursal de la tienda Coppel</description>
    <label>Numero de sucursal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plazo__c/Plazo__c.object-meta.xml
<CustomObject>
    <description>Objeto para activar o desactivar los plazos de seguros</description>
    <label>Plazo</label>
    <nameField>
        <label>Número de plazo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plazo__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para informar que el plazo esta desactivado.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/Dsales_Plazo__c.field-meta.xml
<CustomField>
    <fullName>Dsales_Plazo__c</fullName>
    <description>Campo para indicar el plazo en que se vende el seguro</description>
    <label>Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionarlo con el producto seguro</description>
    <label>Seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Seguro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plazos</relationshipLabel>
    <relationshipName>Plazos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plazo__c/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <inlineHelpText>A=Anual
C=Contado
M=Mensual</inlineHelpText>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Contado</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadecreacionpresupuesto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecreacionpresupuesto__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de creación cotización</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_ID_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_ID_Tienda__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Plazoacotizar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazoacotizar__c</fullName>
    <description>Campo para recibir el plazo máximo a cotizar con proveedor.</description>
    <label>Plazo a cotizar</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesColorCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesColorCelular__c</fullName>
    <description>Color de celular comprado</description>
    <label>Color Celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesGenero__c.field-meta.xml
<CustomField>
    <fullName>dsalesGenero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Masculino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesMarcaCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesMarcaCelular__c</fullName>
    <description>Marca de celular comprado</description>
    <label>Marca celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesModeloCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesModeloCelular__c</fullName>
    <description>Modelo de celular comprado</description>
    <label>Modelo Celular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesOpcionDePago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionDePago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesPrecioCelular__c.field-meta.xml
<CustomField>
    <fullName>dsalesPrecioCelular__c</fullName>
    <description>Precio del celular comprado sin descuentos</description>
    <label>Precio Celular</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Plazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plazo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plazo</label>
    <referenceTo>Plazo__c</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Segurogratis__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Segurogratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si el producto lleva seguro gratis</description>
    <label>Seguro gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <description>Campo para identificar si la partida es de contado o crédito.</description>
    <label>Opción de pago</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo para recibir el id de cotización de Interproteccion por cada uno de los paquetes solicitados.</description>
    <label>Quote id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DSALES_QuoteScWrapperRequestHelper.cls
/*********************************************************************************************************************************************************************
@ Class Name :  DSALES_QuoteScWrapperRequestHelper
@ Author : Namrata Katore
@ Purpose : Helper class to insert Quote & QuoteLineItem of Seguro de Celular in salesforce
@ Date : 30/8/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/

public without sharing class DSALES_QuoteScWrapperRequestHelper{
    public static final String SEGURO ='Seguro Celular';   
    
    /*********************************************************************************************************************************************************************
@ Method Name : insertQuote
@ Author : Namrata Katore
@ Purpose :insert quote in Salesforce 
@ Date : 30/8/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/    
    public static Quote insertQuote(DSALES_QuoteScWrapper.QuoteScRequest data,Id opportunityId, Tienda__c tienda){
        Boolean listaNegra = false;
        
        Quote quoteRecord = new Quote();
        
        String recordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Venta de Seguro de Celulares').getRecordTypeId();
        try{
            quoteRecord.Name = data.nombre;
            if(data.apellidoMaterno != null ){
                quoteRecord.Name+=' '+data.apellidoPaterno + ' '+data.apellidoMaterno;
            }
            else{
                quoteRecord.Name+= ' '+data.apellidoPaterno;
            }
            
            quoteRecord.OpportunityId =opportunityId;
            quoteRecord.ExpirationDate = date.today()+7;
            quoteRecord.RecordTypeId = recordTypeId;
            date dat = date.today();
            quoteRecord.DSALES_Fechadecreacionpresupuesto__c = date.newInstance(dat.year(), dat.month(), dat.day());
            quoteRecord.dsalesListaNegra__c = listaNegra;
            quoteRecord.dsalesMotivoDeListaNegra__c= 'Sin Definir';
            quoteRecord.DSALES_Fechadenacimiento__c = Date.valueOf(data.fechaNacimiento);
            quoteRecord.dsalesOpcionDePago__c = data.opcionPago;
            quoteRecord.DSales_Vendedor__c = data.nombreVendedor;
            //quoteRecord.dsalesGenero__c = data.generoContacto;
            //quoteRecord.dsalesFechaDeComienzoDePoliza__c = Date.valueOf(data.fechaInicio);
            quoteRecord.DSales_ID_Tienda__c = data.idTienda;
            quoteRecord.DSales_Tienda__c = tienda.Id;
            quoteRecord.Phone = data.telefonoCelular;
            
            quoteRecord.Email = data.correoElectronico;
            quoteRecord.DSALES_RFC__c = data.rfc;
            quoteRecord.dsalesIdentificadorCoppel__c = decimal.valueOf(data.identificadorCoppel);
            quoteRecord.DSALES_Plazoacotizar__c= decimal.valueOf(data.plazoCotizar); 
            quoteRecord.dsalesPrecioCelular__c = data.precioCelular;
            quoteRecord.dsalesColorCelular__c = data.colorCelular;
            quoteRecord.dsalesMarcaCelular__c = data.marcaCelular;
            quoteRecord.dsalesModeloCelular__c = data.modeloCelular;
            quoteRecord.dsalesNumeroSucursal__c = Decimal.valueOf(data.numeroDeSucursal);
            quoteRecord.dsalesIdentificadorVendedor__c = Decimal.valueOf(data.identificadorDelVendedor);
            if(Schema.sObjectType.Quote.isCreateable()){
                insert quoteRecord; 
            }
            else{            
                System.debug('Permisos insuficientes para insertar');           
            }
            
        }catch(Exception e){
            System.debug('Error---->'+e.getMessage()+','+e.getLineNumber());
        }
        return quoteRecord;
    }
    /************************************************************************************************************************************************************************
@ Method Name :  insertAccount
@ Author : Namrata Katore
@ Purpose : insert Account in Salesforce
@ Date : 1/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/    
    
    public static Account insertAccount (DSALES_QuoteScWrapper.QuoteScRequest data){
        Account cliente = new Account();
        cliente.CP_WalletCustomerNumber__c = Decimal.valueOf(data.numeroCliente);
        cliente.FirstName = data.nombre;
        cliente.LastName = data.apellidoPaterno;
        cliente.Suffix = data.apellidoMaterno;
        cliente.PersonBirthdate = Date.valueOf(data.fechaNacimiento);
        cliente.PersonEmail = data.correoElectronico;
        cliente.AccountNumber = data.numeroCliente;
        cliente.PersonMobilePhone = data.telefonoCelular;
        if(Schema.sObjectType.Account.isCreateable()) {
            insert cliente;
        }
        else{            
            System.debug('Permisos insuficientes para insertar');           
        }
        
        return cliente;
    }
    
    /*********************************************************************************************************************************************************************
@ Method Name :  insertOpportunity
@ Author : Namrata Katore
@ Purpose : cell phone sales Opportunity generated in Salesforce
@ Date : 1/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/    
    
    public static Opportunity insertOpportunity (DSALES_QuoteScWrapper.QuoteScRequest data, Id clienteId, Tienda__c tienda){
        Opportunity oppor = new Opportunity();
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Seguro de celulares').getRecordTypeId();
        Pricebook2 precioLista = [SELECT id,Name FROM Pricebook2 WHERE Name= 'Standard Price Book' and IsActive=true WITH SECURITY_ENFORCED LIMIT 1];
        oppor.AccountId = clienteId;
        oppor.Name = data.nombre;
        //oppor.Name+=' '+lastName;
        if(data.apellidoMaterno != null ){
            oppor.Name+=' '+data.apellidoPaterno+ ' '+data.apellidoMaterno;
        }
        else{
                oppor.Name+= ' '+data.apellidoPaterno;
            }
        oppor.CloseDate = date.today()+30;
        oppor.StageName = 'Nuevo';
        oppor.RecordTypeId = recordTypeId;
        oppor.DSALES_Tiend__c = tienda.Id;
        oppor.Pricebook2Id = precioLista.Id;
        if(Schema.sObjectType.Opportunity.isCreateable())
        {
            insert oppor;        
        }
        return oppor;
    }
    
    /*********************************************************************************************************************************************************************
@ Method Name :  createQuote
@ Author : Namrata Katore
@ Purpose :Quote request send to Cardiff
@ Date : 1/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/    
    
    public static DSALES_QuoteScWrapper.CardifResponse createQuote(DSALES_QuoteScWrapper.QuoteScRequest obj){
        String body = JSON.serialize(obj);
        System.debug('body: '+body);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = 'https://dc2f757c-06da-4b1a-8451-234565748544.mock.pstmn.io/QuoteSeguroCelular';
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setBody(body);
        request.setTimeout(120000);
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201 ){
            DSALES_QuoteScWrapper.CardifResponse respuesta = (DSALES_QuoteScWrapper.CardifResponse) JSON.deserialize(response.getbody(), DSALES_QuoteScWrapper.CardifResponse.class);
            System.debug('Received by Cardiff----> '+response.getBody());
            return respuesta;
        }else{
            System.debug('Communication failed---> ' + response.getStatusCode()+','+response.getBody());
            return null;
        }     
    }
    /*********************************************************************************************************************************************************************
@ Method Name :  insertQuoteLineItem
@ Author : Namrata Katore
@ Purpose : insert mobile product only
@ Date : 1/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/    
    
    public static QuoteLineItem insertQuoteLineItem(Quote cotiza,String sku,Double price){
        Product2 producto = [SELECT Id, Name, StockKeepingUnit, dsalesOpcionPago__c,DSALES_Seguro__c, DSales_Articulo__c FROM Product2 WHERE StockKeepingUnit=:sku WITH SECURITY_ENFORCED LIMIT 1];
        PricebookEntry precio = [SELECT Id, Name, UnitPrice, Product2Id FROM PricebookEntry WHERE Product2Id =:producto.Id WITH SECURITY_ENFORCED LIMIT 1];
        QuoteLineItem item = new QuoteLineItem();
        try{
            item.QuoteId = cotiza.Id;
            item.PricebookEntryId = precio.Id;
            item.Product2Id = precio.Product2Id;
            item.Quantity = 1;
            item.DSALES_Segurogratis__c = false;
            item.UnitPrice = decimal.valueOf(price);
            if(Schema.sObjectType.QuoteLineItem.isCreateable()){
                insert item;
            }else{            
                System.debug('Permisos insuficientes para insertar');           
            }
        }catch(Exception e){
            System.debug('Error---->'+e.getMessage()+','+e.getLineNumber());
        }
        
        return item;
    }
   
    /*********************************************************************************************************************************************************************
@ Method Name : insertPlazos
@ Author : Namrata Katore
@ Purpose :Add all the plazo & payment option of the insurance in salesforce 
@ Date : 4/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/      
    public static List<DSALES_QuoteScWrapper.Plazo> insertPlazos(String seguro,Quote cotiza, List<DSALES_QuoteScWrapper.InsurancePremium> priceSeg,String obj, String opPagoRecibido, String plazoMaxima) {
        Product2 producto = [SELECT Id, Name, StockKeepingUnit, DSALES_Seguro__c, DSales_Articulo__c, dsalesOpcionPago__c FROM Product2 WHERE Name=:seguro WITH SECURITY_ENFORCED LIMIT 1];
        PricebookEntry precio = [SELECT Id, Name, UnitPrice, Product2Id FROM PricebookEntry WHERE Product2Id = :producto.Id WITH SECURITY_ENFORCED LIMIT 1];
        List<Plazo__c> plazos = [SELECT Id, Name, DSALES_Activo__c, dsalesOpcionPago__c,Dsales_Plazo__c, dsalesSeguro__r.Name FROM Plazo__c WHERE dsalesSeguro__r.Name = :seguro AND DSALES_Activo__c = true AND Dsales_Plazo__c<=:plazoMaxima WITH SECURITY_ENFORCED LIMIT 10];
        
        List<QuoteLineItem> listaPartidas = new List<QuoteLineItem>();
        List<DSALES_QuoteScWrapper.Plazo> listaSeguros = new List<DSALES_QuoteScWrapper.Plazo>();
        List<DSALES_QuoteScWrapper.OpcionPago> opcionesPagoLst = new List<DSALES_QuoteScWrapper.OpcionPago>();
        for(Plazo__c plazo:plazos){
            QuoteLineItem partida = new QuoteLineItem();
            partida.QuoteId = cotiza.Id;
            partida.PricebookEntryId = precio.Id;
            partida.Product2Id = precio.Product2Id;
            partida.Quantity = 1;
            partida.DSALES_Segurogratis__c = false;
            partida.dsalesQuoteId__c = obj;     
       
            DSALES_QuoteScWrapper.OpcionPago paquetesOpcionesPago = new DSALES_QuoteScWrapper.OpcionPago();
            if (producto != null && producto.dsalesOpcionPago__c != null) {
                List<String> opcionPago = producto.dsalesOpcionPago__c.split(';');
                if (opPagoRecibido == 'Mensual') {
                    partida.DSALES_Plazo__c = plazo.Id;
                    DSALES_QuoteScWrapper.opcionPago opcion = new DSALES_QuoteScWrapper.opcionPago();
                    opcion.opcionPago = plazo.Dsales_Plazo__c + 'M';
                    paquetesOpcionesPago= opcion;
                    opcionesPagoLst.add(opcion);
                } 
                else if (opPagoRecibido == 'Contado' && plazo.DSALES_Plazo__c=='12') {
                    partida.DSALES_Plazo__c = plazo.Id;
                    DSALES_QuoteScWrapper.opcionPago opcion = new DSALES_QuoteScWrapper.opcionPago();
                    opcion.opcionPago = '12C';
                    paquetesOpcionesPago=opcion;
                    opcionesPagoLst.add(opcion);
                }
            }
            partida.dsalesOpcionPago__c= paquetesOpcionesPago.opcionPago;
            if(priceSeg.size()>0){
           partida.UnitPrice = priceSeg[0].seguroPrice;
                }
            
            if(partida.DSALES_Plazo__c!=null){
                listaPartidas.add(partida);
            }
            
        }
        
        List<String> pagolst = new List<String>();
        for(DSALES_QuoteScWrapper.OpcionPago pl:opcionesPagoLst){
            pagoLst.add(String.valueOf(pl));
        }
        
        
        for (String paquete : pagolst) {
            DSALES_QuoteScWrapper.Plazo aux = new DSALES_QuoteScWrapper.Plazo();
            aux.paquete = paquete;
            aux.opcionesPago = opcionesPagoLst; 
            listaSeguros.add(aux);
        }
        
        try {
            insert listaPartidas;
            
        } catch (Exception e) {
            System.debug('Error inserting Partida: ' + e.getMessage()+ ' '+e.getLineNumber());
        }
        
        return listaSeguros;
    }
    
    /**************************************************************************************************************************************************************************
@ Method Name : productCelular
@ Author : Namrata Katore
@ Purpose :method return only celular product form the salesforce
@ Date : 1/9/2023
--------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
@ Change History :
**********************************************************************************************************************************************************************/        
    public static Product2 productCelular(String sku){
        Product2 celular=new Product2();
        if(!String.isEmpty(sku)){
            try{
                celular =[SELECT Id, Name, StockKeepingUnit, DSales_Modelo__c,DSales_Marca__c, DSALES_Seguro__c, DSales_Articulo__c,DSales_Tipo_de_Producto__c, dsalesOpcionPago__c FROM Product2 WHERE StockKeepingUnit=:sku AND DSales_Tipo_de_Producto__c='Producto' WITH SECURITY_ENFORCED LIMIT 1];
            }catch (Exception e){
                system.debug('Error de Query: '+e.getMessage() + e.getLineNumber());
            }
        }
        return celular;
    }
    
}