force-app/main/default/objects/Account/fields/dsalesNumeroExterior__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroExterior__c</fullName>
    <description>Campo para recibir el numero exterior</description>
    <label>Número exterior</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dsalesRfc__c.field-meta.xml
<CustomField>
    <fullName>dsalesRfc__c</fullName>
    <label>RFC</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesCalle__c.field-meta.xml
<CustomField>
    <fullName>dsalesCalle__c</fullName>
    <description>Campo para registrar la calle  del participante</description>
    <label>Calle</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesClaveEstado__c.field-meta.xml
<CustomField>
    <fullName>dsalesClaveEstado__c</fullName>
    <description>Campo para registrar la clave del estado del participante</description>
    <label>Clave de estado</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesCodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>dsalesCodigoPostal__c</fullName>
    <description>Campo para registrar el código postal del participante</description>
    <label>Código postal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesCorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>dsalesCorreoElectronico__c</fullName>
    <description>Campo para registrar el email del participante</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesFechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>dsalesFechaNacimiento__c</fullName>
    <description>Campo para registrar l fecha de nacimiento  del participante</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesGenero__c.field-meta.xml
<CustomField>
    <fullName>dsalesGenero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Masculino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesNombre__c.field-meta.xml
<CustomField>
    <fullName>dsalesNombre__c</fullName>
    <description>Campo parar registrar el nombre del participante de la póliza</description>
    <label>Nombre</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesNumeroExterior__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroExterior__c</fullName>
    <description>Campo para registrar el número externo de su casa del participante</description>
    <label>Número exterior</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesNumeroTelefono__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroTelefono__c</fullName>
    <description>Campo para registrar el teléfono del participante</description>
    <label>Número de teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesPrimerApellido__c.field-meta.xml
<CustomField>
    <fullName>dsalesPrimerApellido__c</fullName>
    <description>Campo para recibir el primer apellido del participante de la póliza</description>
    <label>Primer apellido</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesRfc__c.field-meta.xml
<CustomField>
    <fullName>dsalesRfc__c</fullName>
    <description>Campo para registrar el RFC del  participante</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyParticipant/fields/dsalesSegundoApellido__c.field-meta.xml
<CustomField>
    <fullName>dsalesSegundoApellido__c</fullName>
    <description>Campo para registrar el segundo apellido del participante</description>
    <label>Segundo apellido</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CrearParticipantesPoliza.cls
public with sharing class DSALES_CrearParticipantesPoliza {
    public static final String NOMBRE_CONTRATANTE =DSALES_Utility.getNombreContratante('dsalesNombre');
    public static void crearConductor(String idClienteConductor,String idPoliza){
        InsurancePolicyParticipant nuevoParticipante = new InsurancePolicyParticipant();
        nuevoParticipante.InsurancePolicyId=idPoliza;
        nuevoParticipante.PrimaryParticipantAccountId=idClienteConductor;
        nuevoParticipante.Role=DSALES_Utility.FIGURA_CONDUCTOR;

        if(Schema.sObjectType.InsurancePolicyParticipant.isCreateable()) {
            insert nuevoParticipante;
        }else{
            System.debug('Permisos insuficientes para insertar');
        }
    }

    public static void crearOtrosParticipantes(List<DSALES_VentaSM.DatosParticipante> participantes,DSALES_CreateInsurancePolicy.DatosParaParticipantes datos){
        List<InsurancePolicyParticipant> listaParticipantes = new List<InsurancePolicyParticipant>();
        DatosConductor datosCliente = new DatosConductor();
        Decimal numeroCliente ;
        String recortypeOpp= datos.oportunidad.RecordType.DeveloperName;
        if(participantes!=null){
           for(DSALES_VentaSM.DatosParticipante item:participantes){
                InsurancePolicyParticipant participante= new InsurancePolicyParticipant();    
                participante.InsurancePolicyId=datos.poliza.Id;
                participante.dsalesNombre__c=item.nombre;
                participante.dsalesPrimerApellido__c=item.apellidoPaterno;
                participante.dsalesSegundoApellido__c=item.apellidoMaterno;
                participante.dsalesGenero__c=asignarGenero(item.genero);
                participante.Role=item.figura;
                participante.dsalesNumeroTelefono__c=item.telefono;
                participante.dsalesCorreoElectronico__c=item.correoElectronico;
                participante.dsalesFechaNacimiento__c=item.fechaNacimiento;
                participante.dsalesRfc__c=item.rfc;
                participante.dsalesCodigoPostal__c=item.codigoPostal;
                participante.dsalesClaveEstado__c=item.codigoEstado;
                participante.dsalesCalle__c=item.calle;
                participante.dsalesNumeroExterior__c=item.numeroExterior;
                participante.RelationshipToInsured=item.relacionConParticipante;
                participante.BeneficiarySharePercentage=Decimal.valueOf(item.porcentaje);
                System.debug('tipo de registro en oportunidad_____--'+recortypeOpp);
                if((item.figura==DSALES_Utility.FIGURA_CONDUCTOR && recortypeOpp=='Seguro_de_Moto') || (datos.enviaContratante==true && item.figura==DSALES_Utility.FIGURA_CONTRATANTE &&  recortypeOpp== 'dsalesSeguroCelulares')){
                    participante.PrimaryParticipantAccountId=datos.poliza.NameInsuredId;
                }

                listaParticipantes.add(participante);
                
            }
            if(Schema.sObjectType.InsurancePolicyParticipant.isCreateable()) {
                insert listaParticipantes;
            }else{
                System.debug('Permisos insuficientes para insertar');
            }
            
        }

    }
    private static String asignarGenero(String genero){
        if(genero=='F'){
            genero='Femenino';
        }
        else if(genero=='M'){
            genero='Masculino';
        } else if(genero=='Femenino' || genero=='Masculino'){
            genero=genero;
        }
        return genero;
    }
    public static void crearContratante(String idPoliza){
        Account contratante =[SELECT Id FROM Account WHERE FirstName=:NOMBRE_CONTRATANTE WITH SECURITY_ENFORCED LIMIT 1];
        InsurancePolicyParticipant participante = new InsurancePolicyParticipant(
            InsurancePolicyId=idPoliza,
            RelatedParticipantAccountId=contratante.Id,
            Role=DSALES_Utility.FIGURA_CONTRATANTE
        );
        if(Schema.sObjectType.InsurancePolicyParticipant.isCreateable()) {
            insert participante;
        }else{
            System.debug('Permisos insuficientes para insertar');
        }  
    }
    public  class DatosConductor{
        public String nombre{get;set;}
        public String apellidoPaterno {get;set;}
        public String apellidoMaterno {get;set;}
        public String correo{get;set;}
        public Decimal numeroCliente{get;set;}
    }

}