force-app/main/default/objects/Account/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <formula>PersonContact.Birthdate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Seguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_Tipodevehculo__c/DSALES_Tipodevehculo__c.object-meta.xml
<CustomObject>
    <label>Tipo de vehículo</label>
    <nameField>
        <label>Nombre de Tipo de vehículo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Opcionpago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcionpago__c</fullName>
    <formula>TEXT(SourceQuote.dsalesOpcionDePago__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opción de pago</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesBeneficiarioPreferente__c.field-meta.xml
<CustomField>
    <fullName>dsalesBeneficiarioPreferente__c</fullName>
    <label>Beneficiario preferente</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesEstatusPoliza__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstatusPoliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepoliza</fullName>
                <default>true</default>
                <label>Prepóliza</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <label>En trámite</label>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>En solicitud</fullName>
                <isActive>false</isActive>
                <label>En solicitud</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesIMEI__c.field-meta.xml
<CustomField>
    <fullName>dsalesIMEI__c</fullName>
    <description>IMEI del producto (Identificador único)</description>
    <label>IMEI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesNumeroCredito__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroCredito__c</fullName>
    <description>Número de crédito solicitado</description>
    <label>Número de credito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesNumeroDeMotor__c.field-meta.xml
<CustomField>
    <fullName>dsalesNumeroDeMotor__c</fullName>
    <description>Campo para ingresar el número de motor</description>
    <label>Número de motor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesPlazoCredito__c.field-meta.xml
<CustomField>
    <fullName>dsalesPlazoCredito__c</fullName>
    <description>Número de plazos de credito</description>
    <label>Plazo Credito</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo que almacena el ID de la cotización del seguro ganador y compartirlo en la emisión de póliza.</description>
    <label>Quote id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <description>Registros de seguro de celulares</description>
    <label>Seguro de Celulares</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyAsset/fields/dsalesIMEI__c.field-meta.xml
<CustomField>
    <fullName>dsalesIMEI__c</fullName>
    <description>IMEI de dispositivo</description>
    <label>IMEI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de celulares del grupo Coppel.</description>
    <label>Seguro de celulares</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Product2/fields/DSALES_Seguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesSeguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesImei__c.field-meta.xml
<CustomField>
    <fullName>dsalesImei__c</fullName>
    <description>IMEI de dispositivo registrado</description>
    <label>IMEI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <inlineHelpText>A=Anual
C=Contado
M=Mensual</inlineHelpText>
    <label>Opción de pago</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Contado</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/dsalesSeguroCelulares.recordType-meta.xml
<RecordType>
    <fullName>dsalesSeguroCelulares</fullName>
    <active>true</active>
    <description>tipo de registro para generación de seguros para celulares</description>
    <label>Seguro de Celulares</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_TipoUso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoUso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Uso</label>
    <referenceTo>dsalesTipoUso__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/dsalesTipoDeVehiculo__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoDeVehiculo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionar el tipo del vehículo a la cotización</description>
    <label>Tipo de vehículo</label>
    <referenceTo>DSALES_Tipodevehculo__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/DSALES_VentaSM.recordType-meta.xml
<RecordType>
    <fullName>DSALES_VentaSM</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones del producto SM.</description>
    <label>Venta de Seguro de Motos</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <description>Campo para recibir las características del seguro</description>
    <label>Descripción</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_NombreProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NombreProducto__c</fullName>
    <formula>Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DSALES_NombreProducto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_Tipodeproducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeproducto__c</fullName>
    <formula>TEXT(Product2.DSales_Tipo_de_Producto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesOpcionPago__c.field-meta.xml
<CustomField>
    <fullName>dsalesOpcionPago__c</fullName>
    <description>Campo para identificar si la partida es de contado o crédito.</description>
    <label>Opción de pago</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/dsalesQuoteId__c.field-meta.xml
<CustomField>
    <fullName>dsalesQuoteId__c</fullName>
    <description>Campo para recibir el id de cotización de Interproteccion por cada uno de los paquetes solicitados.</description>
    <label>Quote id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CreateInsurancePolicy.cls
public without sharing class DSALES_CreateInsurancePolicy{

    public static InsurancePolicy crearPoliza(List<DSALES_VentaSM.DatosParticipante> participantes, DSALES_VentaSMRest.DatosPrepoliza banderas) {
        InsurancePolicy poliza = new InsurancePolicy();
        String polizaSMRecordTypeId = Schema.SObjectType.InsurancePolicy.getRecordTypeInfosByDeveloperName().get('dsalesSeguroMotos').getRecordTypeId();
        String polizaSMCecordTypeId = Schema.SObjectType.InsurancePolicy.getRecordTypeInfosByDeveloperName().get('dsalesSeguroCelulares').getRecordTypeId();
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Oportunidad__c,DSALES_Motoexterna__c,DSALES_Poliza__c FROM DSALES_InformacionDePago__c WHERE Id=:banderas.idPago WITH SECURITY_ENFORCED];
        Opportunity oportunidad =[SELECT Id,AccountId,SyncedQuoteId,RecordTypeId,RecordType.DeveloperName FROM Opportunity WHERE Id=:pago.DSALES_Oportunidad__c WITH SECURITY_ENFORCED];
        OpportunityLineItem oliList = [SELECT Id, OpportunityId, Product2.Name FROM OpportunityLineItem WHERE OpportunityId =:oportunidad.Id AND Product2.DSales_Tipo_de_Producto__c ='Seguro' WITH SECURITY_ENFORCED LIMIT 1];
        Account cliente =[SELECT Id,RecordTypeId, Name,FirstName,MiddleName,LastName,Suffix,PersonEmail,Fecha_de_Nacimiento__c,CP_Gender__pc FROM Account WHERE Id=:oportunidad.AccountId WITH SECURITY_ENFORCED];
        Quote cotizacion=[SELECT Id,DSALES_RFC__c,dsalesTipoDeVehiculo__r.Name,DSALES_TipoUso__r.Name FROM Quote WHERE Id=:oportunidad.SyncedQuoteId WITH SECURITY_ENFORCED LIMIT 1 ]; 
        QuoteLineItem partidas =[SELECT Id,DSALES_Tipodeproducto__c,DSALES_NombreProducto__c,dsalesQuoteId__c,dsalesOpcionPago__c FROM QuoteLineItem WHERE QuoteId=:cotizacion.Id AND DSALES_Tipodeproducto__c='Seguro' WITH SECURITY_ENFORCED LIMIT 1 ];
        poliza.DSALES_RFC__c=cotizacion.DSALES_RFC__c;
        String recortypeOpp=oportunidad.RecordType.DeveloperName;
        if(recortypeOpp=='Seguro_de_Moto'){
            poliza.RecordTypeId=polizaSMRecordTypeId;
        }
        else if(recortypeOpp=='dsalesSeguroCelulares'){
            poliza.RecordTypeId=polizaSMCecordTypeId;
            poliza.dsalesPlazoCredito__c=String.valueOf(banderas.plazo);
            poliza.dsalesNumeroCredito__c=Double.valueOf(banderas.plazo);
        }
        System.debug('tipo de registro de prepoliza_____________'+poliza.RecordTypeId);
        poliza.Name='0001';
        poliza.NameInsuredId=cliente.Id;
        poliza.dsalesEstatusPoliza__c='Prepoliza';
        poliza.DSALES_CorreoElectronico__c=cliente.PersonEmail;
        String recordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        if(cliente.RecordTypeId==recordTypeId){
            poliza.DSALES_Tipodepersona__c='Física';
        }else {
            poliza.DSALES_Tipodepersona__c='Moral';
        }
        poliza.SourceOpportunityId=oportunidad.Id;
        poliza.SourceQuoteId=cotizacion.Id;
        poliza.dsalesFechaDeEmision__c=Date.today();
        poliza.dsalesQuoteId__c=partidas.dsalesQuoteId__c;
        poliza.dsalesBeneficiarioPreferente__c =String.valueOf(banderas.beneficiarioPreferente);
        //poliza.DSALES_Opcionpago__c=partidas.dsalesOpcionPago__c;
        if(oliList!= null){
            poliza.DSALES_Cobertura__c= oliList.Product2.Name;
        }
        DatosParaParticipantes datos= new DatosParaParticipantes();
        datos.oportunidad=oportunidad;
        datos.poliza=poliza;
        datos.enviaContratante=banderas.enviaContratante;
        if(Schema.sObjectType.InsurancePolicy.isCreateable()) {
            insert poliza;
            DSALES_CrearParticipantesPoliza.crearOtrosParticipantes(participantes,datos);
        }else{
            System.debug('Permisos insuficientes para insertar');   
        }
        return poliza;
    }
    
    
    public static void relacionarPolizaAPago(InsurancePolicy poliza){
        try{
            InsurancePolicy polizaActual =[SELECT Id,SourceOpportunityId FROM InsurancePolicy WHERE Id=:poliza.Id WITH SECURITY_ENFORCED];
            List<DSALES_InformacionDePago__c>  pagos =[SELECT Id,DSALES_Oportunidad__c,DSALES_Poliza__c,DSALES_Seguro__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c=:polizaActual.SourceOpportunityId WITH SECURITY_ENFORCED ];
            List<DSALES_InformacionDePago__c> listaParaActualizar = new List<DSALES_InformacionDePago__c>();
            for(DSALES_InformacionDePago__c pago:pagos){
                if(pago.DSALES_Poliza__c==null && pago.DSALES_Seguro__c==true){
                    pago.DSALES_Poliza__c=poliza.Id;
                    listaParaActualizar.add(pago);
                }
            }
            if(DSALES_InformacionDePago__c.SObjectType.getDescribe().isUpdateable()) {
                update listaParaActualizar;
            }else{
                System.debug('Permisos insuficientes para actualizar');   
            }
        }catch(Exception e){
            System.debug(e.getLineNumber()+':'+e.getMessage());
        }
        
    }
    
    public static InsurancePolicy agregarDatosDeActivo(InsurancePolicyAsset activo,String idPoliza){
        InsurancePolicy poliza = new InsurancePolicy();
        if(activo!=null){
            poliza= [SELECT Id,dsalesIMEI__c,dsalesPlazoCredito__c,dsalesNumeroCredito__c,dsalesActivoPolizaSeguro__c,DSALES_Clavevehicular__c,DSALES_Modelo__c,DSALES_Numeroserie__c,	dsalesNumeroDeMotor__c,DSALES_Descripcion__c,
                     DSALES_Servicio__c,RecordType.DeveloperName,DSALES_Placas__c,DSALES_Marca__c,DSALES_Uso__c,DSALES_ClaveAMIS__c
                     FROM InsurancePolicy WHERE Id=:idPoliza WITH SECURITY_ENFORCED];
            poliza.dsalesActivoPolizaSeguro__c=activo.Id;
            if(poliza.RecordType.DeveloperName=='dsalesSeguroMotos'){
                poliza.DSALES_Clavevehicular__c=activo.DSALES_Clavevehicular__c;
                poliza.DSALES_Modelo__c=activo.DSALES_Modelo__c;
                poliza.DSALES_Numeroserie__c=activo.DSALES_Numeroserie__c;
                poliza.dsalesNumeroDeMotor__c=activo.DSALES_Numeromotor__c;
                poliza.DSALES_Descripcion__c=activo.DSALES_Descripcion__c;
                //poliza.DSALES_Servicio__c=activo.DSALES_Servicio__c;
                poliza.DSALES_Placas__c=activo.DSALES_Placas__c;
                poliza.DSALES_Marca__c=activo.DSALES_Marca__c;
                //poliza.DSALES_Uso__c=activo.DSALES_Uso__c;
            }
            else if(poliza.RecordType.DeveloperName=='dsalesSeguroCelulares'){
                poliza.DSALES_Marca__c=activo.DSALES_Marca__c;
                poliza.DSALES_Modelo__c=activo.DSALES_Modelo__c;
                poliza.DSALES_Numeroserie__c=activo.DSALES_Numeroserie__c;
                poliza.DSALES_Descripcion__c=activo.DSALES_Descripcion__c;
                poliza.dsalesIMEI__c=activo.dsalesIMEI__c;
                //poliza.dsalesPlazoCredito__c=activo.;
                //poliza.dsalesNumeroCredito__c=activo.;
            }
            if(InsurancePolicy.SObjectType.getDescribe().isUpdateable()) {
                update poliza;
            }else{
                System.debug('Permisos insuficientes para actualizar');   
            }
            
            
        }
        return poliza;
    }
    
    public static void cambiarEstatusPoliza(String idPoliza){
        InsurancePolicy poliza=[SELECT Id,DSALES_VigenciacumplidaSM__c,dsalesEstatusPoliza__c,EffectiveDate FROM InsurancePolicy WHERE Id=:idPoliza WITH SECURITY_ENFORCED];
        if(poliza.DSALES_VigenciacumplidaSM__c==true){
            poliza.dsalesEstatusPoliza__c='Vencida';
            if(InsurancePolicy.SObjectType.getDescribe().isUpdateable()) {
                update poliza;
            }else{
                System.debug('Permisos insuficientes para actualizar');   
            }
        }
    }

    public  class DatosParaParticipantes{
       public   Opportunity oportunidad {get;set;}
       public   Boolean enviaContratante{get;set;}
        public  Insurancepolicy poliza{get;set;}
    }
}