force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/DSALES_Matriz_de_Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Matriz Item</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matriz Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica cuando una matriz original está activa</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/dsalesAsignacionDeTienda__c.object-meta.xml
<CustomObject>
    <label>Asignación de Tienda</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Asignación de Tienda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignación de Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/fields/dsalesMatriz__c.field-meta.xml
<CustomField>
    <fullName>dsalesMatriz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matriz</label>
    <referenceTo>DSales_Matriz_GEX__c</referenceTo>
    <relationshipLabel>Asignación de Tiendas</relationshipLabel>
    <relationshipName>dsalesMatriz</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesAsignacionDeTienda__c/fields/dsalesTienda__c.field-meta.xml
<CustomField>
    <fullName>dsalesTienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Asignación de Tiendas</relationshipLabel>
    <relationshipName>Asignacion_de_Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_QuoteGexHelperQuery.cls
public class DSALES_QuoteGexHelperQuery {
    public static dsalesAsignacionDeTienda__c obtenerIdMatrizPrecio(Id tiendaId, Id IntangibleId) {
        List<dsalesAsignacionDeTienda__c> asignaciones = [SELECT dsalesMatriz__c
                                                         FROM dsalesAsignacionDeTienda__c 
                                                         WHERE dsalesTienda__c = :tiendaId 
                                                         AND dsalesMatriz__c <> null
                                                         AND dsalesMatriz__r.DSALES_Servicio__c = :IntangibleId 
                                                         WITH SECURITY_ENFORCED LIMIT 1];
        
        if (!asignaciones.isEmpty()) {
            return asignaciones[0];
        } else {
            return null;
        }
    }
    
    public static DSALES_Matriz_de_Cotizacion__c obtenerSkuPrecio(Decimal resIntangible, Decimal resTangible, Id idMat) {
    List<DSALES_Matriz_de_Cotizacion__c> matrices = [
        SELECT Id, Name, DSALES_Rango_interior_GEX__c, DSALES_Rango_Superior_GEX__c, DSALES_Tiempo_de_Garantia_Extendida_GEX__c, SALES_Precio_GEX__c, DSales_Matriz_GEX__c 
        FROM DSALES_Matriz_de_Cotizacion__c 
        WHERE SALES_Precio_GEX__c = :resIntangible 
            AND DSales_Matriz_GEX__r.DSALES_Activo__c = true 
            AND DSALES_Rango_Superior_GEX__c >= :resTangible 
            AND DSales_Matriz_GEX__c = :idMat
        WITH SECURITY_ENFORCED
        LIMIT 1
    ];

    if (!matrices.isEmpty()) {
        return matrices[0];
    } else {
        return null;
    }
    }

}