force-app/main/default/objects/DSALES_Cancelacion__c/DSALES_Cancelacion__c.object-meta.xml
<CustomObject>
    <label>Cancelación</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Número de Cancelación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancelaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_Canal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSF</fullName>
            </value>
            <value>
                <fullName>.EXE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_FechaCancelacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FechaCancelacion__c</fullName>
    <description>Campo para saber que fecha se cancelo la compra en Coppel</description>
    <label>Fecha de cancelación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_FolioCancelacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FolioCancelacion__c</fullName>
    <description>Campo para registrar el folio de cancelación</description>
    <label>Folio de cancelación</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_Informaciondepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Informaciondepago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionar la cancelación a un pago</description>
    <label>Información de pago</label>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Cancelaciones</relationshipLabel>
    <relationshipName>Cancelaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_MotivoCancelacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MotivoCancelacion__c</fullName>
    <description>Campo para indicar cual fue el motivo de la cancelación</description>
    <label>Motivo de cancelación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto dañado</fullName>
            </value>
            <value>
                <fullName>Precio mas económico en otro establecimiento</fullName>
            </value>
            <value>
                <fullName>Demora de entrega</fullName>
            </value>
            <value>
                <fullName>A petición del cliente</fullName>
                <default>true</default>
                <label>A petición del cliente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_NombreVendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NombreVendedor__c</fullName>
    <description>Campo para identificar la persona quien realizo la cancelación</description>
    <label>Nombre del vendedor</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_NumeroVendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NumeroVendedor__c</fullName>
    <description>Clave del vendedor</description>
    <label>Número de vendedor</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Cancelacion__c/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para identificar que tienda esta solicitando la cancelación</description>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cancelaciones</relationshipLabel>
    <relationshipName>Cancelaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
            <value>
                <fullName>Reembolso</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_IDUniversal1__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDUniversal1__c</fullName>
    <description>Campo para recibir el Id de la venta el cual estará compuesto</description>
    <label>ID Universal</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_Pagos_en_NPV.recordType-meta.xml
<RecordType>
    <fullName>DSALES_Pagos_en_NPV</fullName>
    <active>true</active>
    <description>Aquí se registrarán los pagos de la venta</description>
    <label>Pagos de venta de servicios</label>
</RecordType>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivoPolizaSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepoliza</fullName>
                <default>true</default>
                <label>Prepóliza</label>
            </value>
            <value>
                <fullName>En trámite</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>En solicitud</fullName>
                <isActive>false</isActive>
                <label>En solicitud</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.dsalesCliente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Capo para indicar en que proceso se encuentra el producto que adquirió el cliente</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Por entregar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CancelacionProductosRequest.cls
@RestResource(urlMapping='/cancelacionProductos/*')
global with sharing class DSALES_CancelacionProductosRequest {
    static final String estatusPoliza='Cancelada';
    @HttpPost
    global static DSALES_CancelacionProductosWrapper.response cancelar(){
        DSALES_CancelacionProductosWrapper.response response = new DSALES_CancelacionProductosWrapper.response();
        List<OpportunityLineItem> listaActualizar = new List<OpportunityLineItem>();
        Boolean success = false;
        String errorMessage = '';
        Integer code;
        String idCancelacion='';
        String recordTypeIdMoto = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();
        String recordTypeIdGex = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_Pagos_en_NPV').getRecordTypeId();
        
        if(RestContext.request != null){
            String Body = System.RestContext.request.requestBody.toString();
            if(String.isNotBlank(Body)){
                try{
                    DSALES_CancelacionProductosWrapper.request datos = (DSALES_CancelacionProductosWrapper.request)JSON.deserialize(body,DSALES_CancelacionProductosWrapper.request.class);
                    List<DSALES_CancelacionProductosWrapper.ListaProducto> listaProductos = datos.ListaProductos;
                    DSALES_InformacionDePago__c pago =[SELECT Id, RecordTypeId FROM DSALES_InformacionDePago__c WHERE 	DSALES_IDUniversal1__c=:datos.idUniversal];
                    if(pago!=null ){
                        idCancelacion =crearCancelacion(datos);
                        if(idCancelacion!=''){
                            if(pago.RecordTypeId==recordTypeIdGex){
                                //llamar método de Dani para cancelar Gex
                                DSALES_CertificadoWrapperRequest.putCertificado(datos.idUniversal,listaProductos,datos.estatus,datos.motivoCancelacion);
                            }else if(pago!=null && pago.RecordTypeId==recordTypeIdMoto){
                                actualizarOportunidades(listaProductos);
                            }
                            success=true;
                        }
                        
                    }
                }catch(Exception.JSONException e){
                    System.debug('ERROR JSON'+e.getLineNumber()+e.getMessage());
                    success = false;
                    errorMessage = DSALES_Utility.BAD_REQUEST_MSJ;
                    code = DSALES_Utility.BAD_REQUEST_CODE; 
                }
                catch(Exception e){
                    System.debug('ERROR INTERNO'+ e.getLineNumber()+e.getMessage());
                    success = false;
                    errorMessage =e.getMessage() + e.getLineNumber();
                    code = DSALES_Utility.INTERNAL_ERROR_CODE;
                }
            }
        }
        
        
        response.codigoError=code;
        response.mensajeError=errorMessage;
        response.success=success;
        return response;
    }
    public static void actualizarOportunidades(List<DSALES_CancelacionProductosWrapper.ListaProducto> productosSincro) {
        Map<Id, String> mapaProductos = new Map<Id, String>();
        Map<Id, String> mapaProduct2 = new Map<Id, String>();
        List<Product2> prodRelacionados  = new List<Product2>();
        InsurancePolicyAsset activo  = new InsurancePolicyAsset();
        DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c();
        String idPaOp='';
        for (DSALES_CancelacionProductosWrapper.ListaProducto producto : productosSincro) {
            mapaProductos.put(producto.idPartidaOportunidad, producto.estatus);
        }
        List<OpportunityLineItem> olis = [SELECT Id,Name, OpportunityId, Product2Id, Product2.DSales_Tipo_de_Producto__c, DSALES_Estatus__c
                                          FROM OpportunityLineItem
                                          WHERE Id IN :mapaProductos.keySet()]; 
        if(olis.size()==1 && olis[0].Product2.DSales_Tipo_de_Producto__c=='Producto'){
            pago = [SELECT Id,DSALES_Motoentregada__c,DSALES_Motoexterna__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c =:olis[0].OpportunityId];
            if(pago.DSALES_Motoentregada__c==true){
                activo = [SELECT Id,Estatus__c FROM InsurancePolicyAsset WHERE DSALES_InformacionPago__c=:pago.Id];
                if (activo!=null){
                    pago = [SELECT Id,DSALES_Poliza__c,DSALES_Poliza__r.DSALES_Estatusdepliza__c,DSALES_Poliza__r.PolicyName,DSALES_Poliza__r.DSALES_Activodeplizadeseguro__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c =:olis[0].OpportunityId];
                }
            }
            
        }
        else if(olis.size()>1){
            pago = [SELECT Id,DSALES_Poliza__r.DSALES_Estatusdepliza__c,DSALES_Poliza__r.PolicyName,DSALES_Poliza__r.DSALES_Activodeplizadeseguro__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c =:olis[0].OpportunityId];
            if(pago.DSALES_Poliza__c!=null && pago.DSALES_Poliza__r.DSALES_Activodeplizadeseguro__c!=null && pago.DSALES_Poliza__r.DSALES_Estatusdepliza__c!='Prepoliza' ){
                activo = [SELECT Id,Estatus__c FROM InsurancePolicyAsset WHERE DSALES_InformacionPago__c=:pago.Id];
            }
        }
        for (OpportunityLineItem  prod: olis) {
            mapaProduct2.put(prod.Product2Id,prod.Id);
        }
        prodRelacionados = [SELECT Id,DSales_Tipo_de_Producto__c,Name FROM Product2 WHERE Id IN:mapaProduct2.keySet() AND DSales_Tipo_de_Producto__c=:'Producto' ];
        if(prodRelacionados!=null){
            for(Product2 pd:prodRelacionados){
                idPaOp =mapaProduct2.get(pd.Id);
            }
        }
        if(olis!=null){
            for (OpportunityLineItem oli : olis) {
                String estatus = mapaProductos.get(oli.Id);
                oli.DSALES_Estatus__c = estatus;
                if(activo!=null && idPaOp!=''){
                    activo.Estatus__c=estatus;
                    if(oli.Id==idPaOp){
                        activo.Estatus__c=estatus;
                    }  
                }
                
                
            }
        }
        update olis;
        if(activo.Id!=null){
            update activo;
        }
        
    }
    
    public static String crearCancelacion(DSALES_CancelacionProductosWrapper.request datos){
        DSALES_InformacionDePago__c pago = [SELECT Id FROM 	DSALES_InformacionDePago__c WHERE DSALES_IDUniversal1__c =:datos.idUniversal];
        Tienda__c tienda =[SELECT Id FROM Tienda__c WHERE DSales_TiendaID__c=:datos.idTienda];
        DSALES_Cancelacion__c cancelacion = new DSALES_Cancelacion__c(
            DSALES_Canal__c= datos.canal,
            DSALES_FechaCancelacion__c =datos.fechaCancelacion,
            DSALES_FolioCancelacion__c =datos.folioCancelacion,    
            DSALES_NumeroVendedor__c=datos.numeroVendedor,
            DSALES_NombreVendedor__c = datos.nombreVendedor,
            DSALES_Tienda__c=tienda.Id
        ) ;
        if(datos.ListaProductos.size()>0){
            cancelacion.DSALES_Estatus__c=datos.ListaProductos[0].estatus;
            cancelacion.DSALES_MotivoCancelacion__c=datos.ListaProductos[0].motivoCancelacion;
        }
        else{
            cancelacion.DSALES_Estatus__c=datos.estatus;
            cancelacion.DSALES_MotivoCancelacion__c=datos.motivoCancelacion;
        }
            
        if(pago!=null){
            cancelacion.DSALES_Informaciondepago__c=pago.Id;
        }
        insert cancelacion;
        if(datos.ListaReembolso!=null){
            for(DSALES_ReembolsoWrapper.ReembolsoRequest rmb:datos.ListaReembolso){
                rmb.numeroCancelacion=cancelacion.Id;
            }
            DSALES_ReembolsoWrapperRequest.insertReembolso(datos.ListaReembolso);
        }
        return cancelacion.Id;
    }
    
    
    public static void cancelarPartidaDeSeguro(InsurancePolicy poliza){
        InsurancePolicyAsset activo = new InsurancePolicyAsset();
        if(poliza.DSALES_Estatusdepliza__c ==estatusPoliza ){
            List<OpportunityLineItem> partidasActualizadas = new List<OpportunityLineItem>();
            for(OpportunityLineItem oli: [SELECT Id,Name, Product2Id, Product2.DSales_Tipo_de_Producto__c, DSALES_Estatus__c
                                          FROM OpportunityLineItem
                                          WHERE OpportunityId=:poliza.SourceOpportunityId ]){
                                              if(oli.Product2.DSales_Tipo_de_Producto__c=='Seguro'){
                                                  oli.DSALES_Estatus__c='Cancelado';
                                              }
                                              if(poliza.DSALES_Activodeplizadeseguro__c!=null){
                                                  activo = [SELECT Id,Estatus__c,	DSALES_Motoexterna__c FROM InsurancePolicyAsset WHERE Id=:poliza.DSALES_Activodeplizadeseguro__c];
                                                  if (activo.DSALES_Motoexterna__c==true) {
                                                      activo.Estatus__c='Cancelado';
                                                  }
                                              }
                                              partidasActualizadas.add(oli);
                                              
                                              
                                          }
            update partidasActualizadas;
            if(activo!=null){
                update activo;
            }
        }
    }
}