force-app/main/default/objects/DSALES_Generador__c/DSALES_Generador__c.object-meta.xml
<CustomObject>
    <label>Generador Plantillas</label>
    <nameField>
        <label>Nombre de Generador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generador de Plantillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Fechadeentregaestimada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadeentregaestimada__c</fullName>
    <description>Campo para registrar la fecha estimada de entrega de la moto.</description>
    <label>Fecha de entrega estimada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_EmailCliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_EmailCliente__c</fullName>
    <formula>&apos;dsanmiguel@deloittemx.com&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Enviarcotizacion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Enviarcotizacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cotización enviada al cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_ControladorCotizacionGexTest.cls
@istest
public class DSALES_ControladorCotizacionGexTest {
    @testSetup
    static void testSetup()   
    { 
        Id rtGex = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Venta de Garantía Extendida').getRecordTypeId();
         Id rtSg = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Venta de Seguro de Motos').getRecordTypeId();
        //Quote obj creation
        Opportunity op = new Opportunity(Name='Danny',StageName='Nuevo',CloseDate=Date.today());
        insert op;
        //QuoteLineItemCreation
       // PriceBook2 pb2 = new PriceBook2(Name='Danny');
        //Insert pb2;
        //Product
        Tienda__c tienda = new Tienda__c(DSales_TiendaID__c='20');
		insert tienda;
        
        Product2 prod = new Product2(Name = 'Laptop X26', 
            Family = 'Hardware', DSales_Tipo_de_Producto__c='Producto');
        
        insert prod;
        
         Product2 prod2 = new Product2(Name = 'Laptop X27', 
            Family = 'Hardware', DSales_Tipo_de_Producto__c='Producto');
        
        insert prod2;
        
           Product2 prod3 = new Product2(Name = 'Servicio', 
            Family = 'Hardware', DSales_Tipo_de_Producto__c='Servicio');
        
        insert prod3;
        
        String pb2Id=Test.getStandardPricebookId();
        //PriceBookEntry
        PricebookEntry pb = New PricebookEntry();
        pb.Product2Id = prod.Id;
        pb.PriceBook2Id =pb2Id;//Test.getStandardPricebookId();
        pb.UseStandardPrice = false;
        pb.UnitPrice=200;
        //pb.UnitPrice=35;//when we use standarprice book =true thenunit price is readonly field
        pb.isActive=true;
       	insert pb;
        DSALES_InformacionDePago__c pago = new DSALES_InformacionDePago__c(DSALES_Oportunidad__c=op.Id,DSALES_Fechadeentregaestimada__c=Date.today());
		insert pago;
        Quote qtGex = new Quote(name='DannyGex',OpportunityId=op.Id,PriceBook2Id=pb2Id,RecordTypeId=rtGex,DSales_Tienda__c=tienda.Id,DSALES_Enviarcotizacion__c=false);
        insert qtGex;
         Quote qtSg = new Quote(name='DannySG',OpportunityId=op.Id,PriceBook2Id=pb2Id,RecordTypeId=rtSg,DSales_Tienda__c=tienda.Id,DSALES_Enviarcotizacion__c=false);
        insert qtSg;

        Quote qtSg2 = new Quote(name='DannySG2',OpportunityId=op.Id,PriceBook2Id=pb2Id,RecordTypeId=rtSg,DSales_Tienda__c=tienda.Id);
        insert qtSg2;
        
        QuoteLineItem quote= new QuoteLineItem(QuoteId=qtGex.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod.id,Vigencia_meses__c='12');
        insert quote;
        
        QuoteLineItem quote1= new QuoteLineItem(QuoteId=qtGex.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod2.id,Vigencia_meses__c='24');
        insert quote1;
        QuoteLineItem quote2= new QuoteLineItem(QuoteId=qtGex.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod3.id,Vigencia_meses__c='12');
        insert quote2;
        
        QuoteLineItem quote3= new QuoteLineItem(QuoteId=qtSg.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod.id,Vigencia_meses__c='12');
        insert quote3;
        
        QuoteLineItem quote4= new QuoteLineItem(QuoteId=qtSg.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod2.id,Vigencia_meses__c='24');
        insert quote4;
        
        
          QuoteLineItem quote6= new QuoteLineItem(QuoteId=qtSg2.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod.id,Vigencia_meses__c='12');
        insert quote6;
        
        QuoteLineItem quote7= new QuoteLineItem(QuoteId=qtSg2.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod2.id,Vigencia_meses__c='24');
        insert quote7;
        QuoteLineItem quote8= new QuoteLineItem(QuoteId=qtSg2.Id,UnitPrice=2,Quantity=2,PricebookEntryId=pb.Id,Product2Id=prod2.id,Vigencia_meses__c='24');
        insert quote8;
        
        DSALES_Generador__c gen = new DSALES_Generador__c();
        gen.Name='Cotizacion Gex';
        gen.DSALES_Plantilla__c='Cotizacion';
        
        
        insert gen;
        
         DSALES_Generador__c gen2 = new DSALES_Generador__c();
        gen2.Name='Cotizacion SG';
        gen2.DSALES_Plantilla__c='Cotizacion';
        insert gen2;
        
        DSALES_Generador__c gen3= new DSALES_Generador__c();
        gen3.Name='DSALES_EnvioCotizacionSm';
        gen3.DSALES_Plantilla__c='Cotizacion';
        insert gen3;
   	}
        @istest public  static void controladorCotizacionGex()
        {
            Test.startTest();
            List<Product2> pd=[SELECT Name,Family, DSales_Tipo_de_Producto__c FROM Product2 WHERE DSales_Tipo_de_Producto__c='Producto' LIMIT 1];
            Quote qt= [SELECT Id, DSALES_EmailCliente__c,DSALES_Enviarcotizacion__c FROM QUOTE WHERE NAME='DannyGex' LIMIT 1	];
             Quote qt2= [SELECT Id, DSALES_EmailCliente__c,DSALES_Enviarcotizacion__c FROM QUOTE WHERE NAME='DannyGex' LIMIT 1	];
            System.debug('quote: '+qt.Id);
            List<QuoteLineItem> qline =[SELECT Id, QuoteId,UnitPrice,Quantity,PricebookEntryId,Product2Id FROM QuoteLineItem];
           qt.DSALES_Enviarcotizacion__c=true;
            qt2.DSALES_Enviarcotizacion__c=true;
            
            DSALES_Generador__c gene=[SELECT Id,Name,DSALES_Plantilla__c FROM DSALES_Generador__c   WHERE Name='Cotizacion Gex' LIMIT 1];
             System.debug('generador: '+gene.Id);
            PageReference pageRef = Page.Cotizacion;
            Test.setCurrentPage(pageRef);
            // put the certificado id as a parameter
            ApexPages.currentPage().getParameters().put('quoteId',qt.Id);
            // Call your apex method here and you will get code coverage
            
            DSALES_ControladorCotizacionGex controlador = new DSALES_ControladorCotizacionGex();
            
           
            Test.stopTest();
            System.assertEquals(qt.id, qt.Id, '');
        }
     @istest public  static void controladorCotizacionSG()
        {
            Test.startTest();
            List<Product2> pd=[SELECT Name,Family, DSales_Tipo_de_Producto__c FROM Product2 WHERE DSales_Tipo_de_Producto__c='Producto' LIMIT 1];
           
            Quote qt=[SELECT Id, DSALES_EmailCliente__c FROM QUOTE WHERE NAME='DannySg' LIMIT 1	];
            System.debug('quote: '+qt.Id);
            List<QuoteLineItem> qline =[SELECT Id, QuoteId,UnitPrice,Quantity,PricebookEntryId,Product2Id FROM QuoteLineItem];
           
            DSALES_Generador__c gene=[SELECT Id,Name,DSALES_Plantilla__c FROM DSALES_Generador__c WHERE Name='Cotizacion SG' LIMIT 1];
             System.debug('generador: '+gene.Id);
            PageReference pageRef = Page.Cotizacion;
            
            Test.setCurrentPage(pageRef);
           
            // put the certificado id as a parameter
            
            ApexPages.currentPage().getParameters().put('quoteId',qt.Id);
            // Call your apex method here and you will get code coverage
            
            DSALES_ControladorCotizacionGex controlador = new DSALES_ControladorCotizacionGex();
            
           
            Test.stopTest();
            System.assertEquals(qt.Id, qt.Id, '');
        }
    @istest public  static void controladorCotizacionSG2()
        {
            Test.startTest();
            List<Product2> pd=[SELECT Name,Family, DSales_Tipo_de_Producto__c FROM Product2 WHERE DSales_Tipo_de_Producto__c='Producto' LIMIT 1];
            
            Quote qt2=[SELECT Id, DSALES_EmailCliente__c FROM QUOTE WHERE NAME='DannySg2' LIMIT 1	];
            System.debug('quote: '+qt2.Id);
            List<QuoteLineItem> qline =[SELECT Id, QuoteId,UnitPrice,Quantity,PricebookEntryId,Product2Id FROM QuoteLineItem];
            DSALES_Generador__c gene=[SELECT Id,Name,DSALES_Plantilla__c FROM DSALES_Generador__c WHERE Name='DSALES_EnvioCotizacionSm' LIMIT 1];
             System.debug('generador: '+gene.Id);
            PageReference pageRef = Page.Cotizacion;
          
            Test.setCurrentPage(pageRef);
           
            // put the certificado id as a parameter
           
            ApexPages.currentPage().getParameters().put('quoteId',qt2.Id);
            // Call your apex method here and you will get code coverage
            
            DSALES_ControladorCotizacionGex controlador = new DSALES_ControladorCotizacionGex();
            
           
            Test.stopTest();
            System.assertEquals(qt2.Id, qt2.Id, '');

        }
        
}