force-app/main/default/objects/dsalesCiudad__c/dsalesCiudad__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nombre de Ciudad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesCiudad__c/fields/dsalesActivo__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dsalesCiudad__c/fields/dsalesRegion__c.field-meta.xml
<CustomField>
    <fullName>dsalesRegion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Región</label>
    <referenceTo>dsalesRegion__c</referenceTo>
    <relationshipLabel>Ciudades</relationshipLabel>
    <relationshipName>Ciudades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dSalesGerente__c/fields/DSalesCiudad__c.field-meta.xml
<CustomField>
    <fullName>DSalesCiudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>dsalesCiudad__c</referenceTo>
    <relationshipLabel>Gerentes</relationshipLabel>
    <relationshipName>Gerentes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesRegion__c/dsalesRegion__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nombre de Región</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesCiudad__c.field-meta.xml
<CustomField>
    <fullName>dsalesCiudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>dsalesCiudad__c</referenceTo>
    <relationshipLabel>Tiendas</relationshipLabel>
    <relationshipName>Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dSalesGerente__c.field-meta.xml
<CustomField>
    <fullName>dSalesGerente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relaciona la Tienda con El Gerente de Zona</description>
    <label>Nombre Gerente de Tienda de Zona</label>
    <referenceTo>dSalesGerente__c</referenceTo>
    <relationshipLabel>Tiendas</relationshipLabel>
    <relationshipName>Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_TiendaGexRequestTest.cls
@isTest
public with sharing class DSALES_TiendaGexRequestTest {
    @TestSetup
	static void setUp()
    {
        Tienda__c tienda= new Tienda__c(Name='Dani',DSales_TiendaID__c='54');
        insert tienda;
        dsalesRegion__c region= new dsalesRegion__c(Name='Coahuila',dsalesActivo__c=true);
        insert region;
        dsalesCiudad__c ciudad= new dsalesCiudad__c(Name='Monterrey',dsalesActivo__c=true,dsalesRegion__c=region.id);
        insert ciudad;
        dSalesGerente__c gerente= new dSalesGerente__c(Name='Danny');
        insert gerente;
    }
    @isTest static void crearRegistro()
        {
            RestRequest peticion= new RestRequest();
            RestResponse respuesta= new RestResponse();
            String cuerpo='{"idTienda":"54","activa":true,"tiendaBase":"1","telefonoTiendaBase":"111","nombreTienda":"Coppel","direccion":"Charcasvallerojo","estado":"Nuevo León","telefono":"1234","codigoPostal":"66051","ciudad":"Mérida","region":"Yucatán","division":"DIVISIÓNTIENDASI","nombreGerente":"DanielSanMiguelCardona","numeroCelular":"12345678","emailGerente":"dsanmiguel@deloittemx.com","banco":true,"optica":true,"moduloAfore":false,"fechaApertura":"2023-09-15","ultimaRemodelacion":"2023-09-15","tipoDeTienda":"Propio","formato":"TIENDACOPPEL"}';
           peticion.RequestURI='/apexrest/insertTienda';
            peticion.HttpMethod='POST';
            RestContext.request=peticion;
            peticion.requestBody=Blob.valueOf(cuerpo);
            RestContext.response=respuesta;
            DSALES_TiendaGex.tiendaRequest tiendaRegistro =  (DSALES_TiendaGex.tiendaRequest)JSON.deserialize (cuerpo,DSALES_TiendaGex.tiendaRequest.class);
            Test.startTest();
            DSALES_TiendaGexRequest.crearTienda();
            REstContext.Request=peticion;
            RestContext.Response=respuesta;
            System.debug('RESPUESTA ES: '+respuesta);
            Test.stopTest();
            
            
        }
     @isTest static void crearRegistro2()
        {
            RestRequest peticion= new RestRequest();
            RestResponse respuesta= new RestResponse();
            String cuerpo='{"idTienda":"55","activa":true,"tiendaBase":"1","telefonoTiendaBase":"111","nombreTienda":"Coppel","direccion":"Charcasvallerojo","estado":"Nuevo León","telefono":"1234","codigoPostal":"66051","ciudad":"Monterrey","region":"Coahuila","division":"DIVISIÓNTIENDASI","nombreGerente":"Danny","numeroCelular":"12345678","emailGerente":"dsanmiguel@deloittemx.com","banco":true,"optica":true,"moduloAfore":false,"fechaApertura":"2023-09-15","ultimaRemodelacion":"2023-09-15","tipoDeTienda":"Propio","formato":"TIENDACOPPEL"}';
           peticion.RequestURI='/apexrest/insertTienda';
            peticion.HttpMethod='POST';
            RestContext.request=peticion;
            peticion.requestBody=Blob.valueOf(cuerpo);
            RestContext.response=respuesta;
            DSALES_TiendaGex.tiendaRequest tiendaRegistro =  (DSALES_TiendaGex.tiendaRequest)JSON.deserialize (cuerpo,DSALES_TiendaGex.tiendaRequest.class);
            Test.startTest();
            DSALES_TiendaGexRequest.crearTienda();
            REstContext.Request=peticion;
            RestContext.Response=respuesta;
            System.debug('RESPUESTA ES: '+respuesta);
            Test.stopTest();
            
           
        }
}