force-app/main/default/objects/dsalesCiudad__c/dsalesCiudad__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nombre de Ciudad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/dsalesCiudad__c/fields/dsalesActivo__c.field-meta.xml
<CustomField>
    <fullName>dsalesActivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dsalesCiudad__c/fields/dsalesRegion__c.field-meta.xml
<CustomField>
    <fullName>dsalesRegion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Región</label>
    <referenceTo>dsalesRegion__c</referenceTo>
    <relationshipLabel>Ciudades</relationshipLabel>
    <relationshipName>Ciudades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dSalesGerente__c/fields/DSalesCiudad__c.field-meta.xml
<CustomField>
    <fullName>DSalesCiudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>dsalesCiudad__c</referenceTo>
    <relationshipLabel>Gerentes</relationshipLabel>
    <relationshipName>Gerentes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dsalesRegion__c/dsalesRegion__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nombre de Región</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>dsalesActiva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Banco__c.field-meta.xml
<CustomField>
    <fullName>dsalesBanco__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indica si la  tienda tiene sucursal de banco</description>
    <inlineHelpText>Indica si la  tienda tiene sucursal de banco</inlineHelpText>
    <label>Banco</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>dsalesCiudad__c</fullName>
    <label>Ciudad</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Estado__c.field-meta.xml
<CustomField>
    <fullName>dsalesEstado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>CAMPECHE</fullName>
            </value>
            <value>
                <fullName>CHIAPAS</fullName>
            </value>
            <value>
                <fullName>CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>CIUDAD DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>COAHUILA</fullName>
            </value>
            <value>
                <fullName>COLIMA</fullName>
            </value>
            <value>
                <fullName>DURANGO</fullName>
            </value>
            <value>
                <fullName>ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>GUERRERO</fullName>
            </value>
            <value>
                <fullName>HIDALGO</fullName>
            </value>
            <value>
                <fullName>JALISCO</fullName>
            </value>
            <value>
                <fullName>MICHOACÁN</fullName>
            </value>
            <value>
                <fullName>MORELOS</fullName>
            </value>
            <value>
                <fullName>NAYARIT</fullName>
            </value>
            <value>
                <fullName>NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>OAXACA</fullName>
            </value>
            <value>
                <fullName>PUEBLA</fullName>
            </value>
            <value>
                <fullName>QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>SINALOA</fullName>
            </value>
            <value>
                <fullName>SONORA</fullName>
            </value>
            <value>
                <fullName>TABASCO</fullName>
            </value>
            <value>
                <fullName>TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>TLAXCALA</fullName>
            </value>
            <value>
                <fullName>VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Fechadeapertura__c.field-meta.xml
<CustomField>
    <fullName>dsalesFechaApertura__c</fullName>
    <label>Fecha de apertura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Optica__c.field-meta.xml
<CustomField>
    <fullName>dsalesOptica__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica las susucursales que tienen servicio de óptica</description>
    <inlineHelpText>Indica las susucursales que tienen servicio de óptica</inlineHelpText>
    <label>Óptica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>dsalesRegion__c</fullName>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSALES_Tienda_Base__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaBase__c</fullName>
    <description>Indica el folio de la Tienda Base</description>
    <inlineHelpText>Indica el folio de la Tienda Base</inlineHelpText>
    <label>Tienda Base</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>dsalesTiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesAnoDeUltimaRemodelacion__c.field-meta.xml
<CustomField>
    <fullName>dsalesAnoDeUltimaRemodelacion__c</fullName>
    <description>Indica el año de última remodelación</description>
    <inlineHelpText>Indica el año de última remodelación</inlineHelpText>
    <label>Año de última remodelación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesCiudad__c.field-meta.xml
<CustomField>
    <fullName>dsalesCiudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>dsalesCiudad__c</referenceTo>
    <relationshipLabel>Tiendas</relationshipLabel>
    <relationshipName>Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesEmailGerenteDeTiendaDeZona__c.field-meta.xml
<CustomField>
    <fullName>dsalesEmailGerenteDeTiendaDeZona__c</fullName>
    <description>Indica el email del Gerente  de Tienda Zona</description>
    <inlineHelpText>Indica el email del Gerente  de Tienda Zona</inlineHelpText>
    <label>E-mail Gerente de Tienda de Zona</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dSalesGerente__c.field-meta.xml
<CustomField>
    <fullName>dSalesGerente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relaciona la Tienda con El Gerente de Zona</description>
    <label>Nombre Gerente de Tienda de Zona</label>
    <referenceTo>dSalesGerente__c</referenceTo>
    <relationshipLabel>Tiendas</relationshipLabel>
    <relationshipName>Tiendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesModuloAfore__c.field-meta.xml
<CustomField>
    <fullName>dsalesModuloAfore__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica las tiendas que cuentan con este servicio</description>
    <inlineHelpText>Indica las tiendas que cuentan con este servicio</inlineHelpText>
    <label>Módulo AFORE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/dsalesTelefono__c.field-meta.xml
<CustomField>
    <fullName>dsalesTelefono__c</fullName>
    <description>Campo para ingresar el numero de teléfono de la tienda</description>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/Tipo_de_Tienda_Inmueble_Renta__c.field-meta.xml
<CustomField>
    <fullName>dsalesTipoTiendaInmuebleRenta__c</fullName>
    <label>Tipo  de Tienda Inmueble / Renta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propio</fullName>
                <default>true</default>
                <label>Propio</label>
            </value>
            <value>
                <fullName>Rentado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_TiendaGexRequest.cls
@RestResource(urlMapping='/insertTienda/*')
Global with sharing class DSALES_TiendaGexRequest {
    @HttpPost
    global static DSALES_TiendaGex.tiendaResponse crearTienda()
    {
        DSALES_TiendaGex.tiendaResponse responsePayload = new DSALES_TiendaGex.tiendaResponse();
        if(RestContext.request!=null)
        {
            String body=System.RestContext.request.requestBody.toString();
            if(String.isNotBlank(body))
            {
                try {
                    DSALES_TiendaGex.tiendaRequest tienda = (DSALES_TiendaGex.tiendaRequest) JSON.deserialize(body,DSALES_TiendaGex.tiendaRequest.class);
                    responsePayload=upsertTienda(tienda);
                    
                } catch (Exception e) {
                    responsePayload.exito=false;
                    responsePayload.mensajeError='Error: '+e.getMessage()+ e.getLineNumber();
                }
            }
        }
        return responsePayload;
    }
    global static DSALES_TiendaGex.tiendaResponse upsertTienda(DSALES_TiendaGex.tiendaRequest tiendaRecord)
    {
        Tienda__c tienda = new Tienda__c();
        Boolean exito=false;
        String mensaje='';
        String idTienda='';
        string codigoError='';
        List<Tienda__c> tiendaUpsert = new List<Tienda__c>();
        if(!String.isEmpty(tiendaRecord.idTienda)&& tiendaRecord.idTienda!=null)
        {
            tiendaUpsert=[SELECT Id,DSales_TiendaID__c FROM Tienda__c WHERE DSales_TiendaID__c=:tiendaRecord.idTienda LIMIT 1];
        }
        if(tiendaUpsert.size()>0)
            {
                tienda.id=tiendaUpsert[0].id;
                mensaje='Tienda actualizada';
            }
        
            dsalesCiudad__c ciudad= new dsalesCiudad__c();
            dsalesRegion__c region= new dsalesRegion__c();
        dSalesGerente__c gerente= new dSalesGerente__c();
            try {
                region=[SELECT Id,Name,dsalesActivo__c FROM dsalesRegion__c WHERE Name=:tiendaRecord.region LIMIT 1];
                 ciudad=[SELECT Id,Name,dsalesActivo__c,dsalesRegion__c,dsalesRegion__r.Name FROM dsalesCiudad__c WHERE Name=:tiendaRecord.ciudad LIMIT 1];
                gerente=[SELECT Id,Name,dsalesEmailGerenteDeTiendaDeZona__c,dsalesNumeroCelular__c	 FROM dSalesGerente__c WHERE Name=:tiendaRecord.nombreGerente LIMIT 1];
            } catch (Exception e) {
                system.debug('Try catch ciudad/region/gerente: '+e.getMessage());
            }
     	if(!String.isEmpty(tiendaRecord.ciudad) && (!String.isEmpty(tiendaRecord.region) && (!String.isEmpty(tiendaREcord.nombreGerente))))
            {
			 	if(gerente.id==null)
                {
                    gerente.name=tiendaRecord.NombreGerente;
                    gerente.dsalesEmailGerenteDeTiendaDeZona__c=tiendaRecord.emailGerente;
                    gerente.dsalesNumeroCelular__c=tiendaRecord.numeroCelular;
                    if(schema.SObjectType.dsalesRegion__c.isCreateable()){
                                insert gerente;
                                system.debug('Gerente Creado');
                            }
                }
                 
                if(region.id==null)
                {
                    region.name=tiendaRecord.region;
                    region.dsalesActivo__c=true;
                    if(schema.SObjectType.dsalesRegion__c.isCreateable()){
                                insert region;
                                system.debug('Región Creada');
                            }
                }
                if(ciudad.Id==null)
                    {
                        ciudad.dsalesActivo__c=true;
                        ciudad.Name=tiendaRecord.ciudad;
                        ciudad.dsalesRegion__c=region.Id;
                        try{
                            if(schema.SObjectType.dsalesCiudad__c.isCreateable()){
                                insert ciudad;
                                system.debug('Ciudad Creada');
                                 
                            }
                               }
                               catch(Exception e)
                               {
                                   mensaje=DSALES_Utility.INTERNAL_ERROR_MSJ+e.getMessage() + e.getLineNumber();
               						 codigoError=String.valueOf(DSALES_Utility.INTERNAL_ERROR_CODE);
                               }
                        
                        
                    }
                else{
                     system.debug('Ciudad ya existe');
                    Boolean check=false;
                    if(ciudad.dsalesRegion__c!=null&&!ciudad.dsalesRegion__r.Name.Equals(region.Name))
                    {
                        ciudad.dsalesRegion__c=region.Id;
                        check=true;
                        
                    }
                   else if(ciudad.dsalesRegion__c==null)
                       {
                           ciudad.dsalesRegion__c=region.Id; 
                           check=true;
                       }
                    if(Schema.SobjectType.dsalesCiudad__c.isUpdateable() &&check)
                        {
                            update ciudad;
                            system.debug('Región actualizada');
                            
                        }
                    
                }
                tienda.dsalesCiudad__c=ciudad.id;
                tienda.dSalesGerente__c=gerente.Id;
            }
        tienda.DSales_TiendaID__c=tiendaRecord.idTienda;
        tienda.Activa__c=tiendaRecord.activa;
        tienda.DSALES_Tienda_Base__c= tiendaRecord.tiendaBase;
        tienda.dsalesTelefonoTiendaBase__c=tiendaRecord.telefonoTiendaBase;
        tienda.Name=tiendaRecord.nombreTienda;
        tienda.dsalesDireccion__c=tiendaRecord.direccion;
        tienda.DSALES_Estado__c=tiendaRecord.estado;
       // tienda.DSALES_Region__c=tiendaRecord.region; //picklist
        tienda.dsalesCodigoPostal__c=tiendaRecord.codigoPostal;
        tienda.DSALES_Ciudad__c=tiendaRecord.ciudad;
        tienda.dsalesDivision__c=tiendaRecord.division;
        tienda.dsalesNombreGerenteDeTiendaDeZona__c=tiendaRecord.nombreGerente;
        tienda.dsalesNumeroCelular__c=tiendaRecord.numeroCelular;
        tienda.dsalesEmailGerenteDeTiendaDeZona__c=tiendaRecord.emailGerente;
        tienda.dsalesTelefono__c=tiendaRecord.telefono;
        tienda.DSALES_Optica__c=tiendaRecord.optica;
        tienda.dsalesModuloAfore__c=tiendaRecord.moduloAfore;
        tienda.DSALES_Fechadeapertura__c=tiendaRecord.fechaApertura;
        tienda.dsalesAnoDeUltimaRemodelacion__c=tiendaRecord.ultimaRemodelacion;
        tienda.Tipo_de_Tienda_Inmueble_Renta__c=tiendaRecord.tipoDeTienda;
        tienda.DSALES_Formato__c=tiendaRecord.formato;
        tienda.DSALES_Banco__c=tiendaRecord.banco;
        
        
        try{
            if(schema.SObjectType.Tienda__c.isCreateable() || schema.SObjectType.tienda__c.isUpdateable())
            {
                upsert tienda;
                
            }
            if(String.isEmpty(mensaje))
                {
                     mensaje='Tienda creada';
                }
           
            idTienda=tienda.id;
            exito=true;
            
        }
        catch (Exception e)
            {
                mensaje=DSALES_Utility.INTERNAL_ERROR_MSJ+e.getMessage() + e.getLineNumber();
                codigoError=String.valueOf(DSALES_Utility.INTERNAL_ERROR_CODE);
                
            }
       DSALES_TiendaGex.tiendaResponse responsePayload = new DSALES_TiendaGex.tiendaResponse();     
        responsePayload.mensajeError=mensaje;
        responsePayload.idTienda=idTienda;
        responsePayload.codigoError=codigoError;
        responsePayload.exito=exito;
        
        return responsePayload;
    }
}